### ISSUE TITLE
Focus is set to last tab after restart

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1007]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Active tab (when active tab is not the highest numbered tab) is not being maintained. i.e. you have 10 tabs open and the 3rd tab is active. Close/Reopen and the 10th tab is now the active tab.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad and iPhone

- Brave Version:
1.4 (17.07.31.11)

- Steps to reproduce:
    1. Open several tabs.
    2. Make any tab but the highest numbered tab the active one. (if you have 5 tabs open, make tab 1, 2, 3, or 4 the active tab)
    3. Close Brave so it is not running in the background.
    4. Relaunch Brave.
    5. Highest numbered tab is now the active tab.

- Actual Behavior
Last active tab isn't maintained, highest numbered tab is active.

- Expected Behavior
Last active tab should remain last active tab.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Weird still seeing this issue on 17.08.01.15. reopening the issue again

**Comment by srirambv** [comment]
Verified and working on 1.4(17.08.03.10)
