### ISSUE TITLE
Some tab names blank after restart

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1008]
- Did you search for similar issues before submitting this one?
yes

- Description:
Some tab names are blank after restart.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad

- Brave Version:
1.4 (17.07.31.11)

- Steps to reproduce:
    1. Open multiple tabs (you need to be able to scroll through the tabs, so you want 12+ tabs)
    2. Verify each tab has a tab name visible under the URL bar.
    3. Close/Reopen Brave.
    4. Tabs visible when you first open the app have tab names, but when you scroll back to the beginning, some of those tab names are blank. Number of tabs which are blank depends on how many tabs you have open.

- Actual Behavior
Tabs at the beginning have blank tab names.

- Expected Behavior
All tabs should display their names.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes (number of tabs that have blank names vary)

- Extra QA steps:
    1. When you tap on a tab with a blank name, tab and tab name load.
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
![img_0028](https://user-images.githubusercontent.com/28145373/28788959-18bc498c-75f1-11e7-9277-943d325b35bb.PNG)

- Any related issues:

**Comment by jhreis** [comment]
Fixed per https://github.com/brave/browser-ios/commit/bda35f69ee5028670b04310732329373bfadeb45

**Comment by alexwykoff** [comment]
I can reproduce this on 1.4.1 (17.08.24.14)

**Comment by alexwykoff** [comment]
Clarification : issue noticed was with sites which do not have a title
