### ISSUE TITLE
Preferences in BRAVE

### ISSUE THREAD

**Issue by Donadam2016** [brave/browser-ios#101]
Why can't I set my Preferences in BRAVE?

**Comment by garvankeeley** [comment]
In the iOS browser, settings are currently under the tab tray view, tap to view tabs, then tap the gear icon. Hopefully we can move these to system settings so we don't have to find a place in-app for the gear icon.

**Comment by garvankeeley** [comment]
Closing, feel free to reopen if you have more questions about this
