### ISSUE TITLE
Lion head is not shown when orientation changes for private tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1016]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Lion head is not shown when orientation changes for private tabs

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10.3.2)

- Brave Version:
1.4 (17.07.31.11)

- Steps to reproduce:
    1. Open a Private tab and visit a site
    2. Change orientation to landscape and close the tab
    3. Lion head is shown in between Tracker count and HTTPS count
    4. Open a new tab in landscape mode, doesn't show the Lion head in between the badge

- Actual Behavior
Lion head is not shown when orientation changes for private tabs

- Expected Behavior
Should either show/not show the lion head when orientation changes

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jamesmudgett** [comment]
@srirambv this was done by design since the lion head takes up vertical space and is used decoratively... An alternative would have been to scroll page or decrease the lion image size, both would push content further down into fold.

**Comment by jamesmudgett** [comment]
Lion head should always be hidden in private tab (landscape mode), fixed issue in PR.
