### ISSUE TITLE
Bookmarks not always displayed in left well after being added

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1021]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Bookmarks aren't always displayed in the left well after they are added. If you close/reopen Brave the left well is updated with the added bookmark.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad

- Brave Version:
1.4 (17.08.01.15)

- Steps to reproduce:
    1. Clean install of 1.4 (17.08.01.15)
    2. Open BraveBeta and tap on bookmark icon next to the URL bar.
    3. Tap on Settings icon. Tap on Done.
    4. Tap on new tab on right side of screen, tap on one of the top tiles (such as Amazon).
    5. Add site as a bookmark, tap on right side of screen.
    6. Add a new tab and tap on a different top tile (such as Wikipedia).
    7. Add second tab as a bookmark. 
    8. Second site does not display in left well with other bookmark.

- Actual Behavior
Second bookmark added does not appear in list of bookmarks.

- Expected Behavior
Second bookmark added should appear in list of bookmarks without having to restart BraveBeta.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
![img_0034](https://user-images.githubusercontent.com/28145373/28847418-2a26d6dc-76dd-11e7-8299-9a87296c4b31.PNG)

- Any related issues:

**Comment by srirambv** [comment]
Should be fixed by 71539a8
