### ISSUE TITLE
Privacy Policy link broken in Settings

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1032]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Privacy Policy cannot be accessed from settings.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone, iPad

- Brave Version:
1.3.3, 1.4

- Steps to reproduce:
    1. Nav to settings.
    2. Tap Privacy Policy.
    3. Link error is displayed.

- Actual Behavior
403 error.

- Expected Behavior
Privacy Policy should be displayed.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
![img_4485](https://user-images.githubusercontent.com/28145373/28975696-fa7129e6-7908-11e7-953f-a4c429d3b6d3.PNG)

- Any related issues:

**Comment by Jacalz** [comment]
Just found a strange thing when testning this, there is no no fancy ui when accesing the private policy in 1.4 😅

**Comment by Jacalz** [comment]
I see this fixed as of now, closing this 😉
Let’s reopen if you still see the issue 🙂
