### ISSUE TITLE
Facebook displays a warning (indicates Brave is an unsupported browser)

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1042]
- Did you search for similar issues before submitting this one?
Yes

- Description:
www.facebook.com on the iPad shows a warning, iPhone does not show this warning. 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad

- Brave Version:
1.4 (17.08.04.18)

- Steps to reproduce:
    1. Clean install of beta build on iPad.
    2. Open www.facebook.com
    3. 

- Actual Behavior
Warning message is displayed at the top of the screen.

- Expected Behavior
Warning message should not be displayed.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down?  Yes
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? Yes, also occurs on Firefox but not Dolphin.

- Screenshot if needed:
1.4 (17.08.04.18)
![img_0047](https://user-images.githubusercontent.com/28145373/29045342-444a20ba-7b91-11e7-9b61-b4695a373c9e.PNG)

![img_0050](https://user-images.githubusercontent.com/28145373/29045527-e163dc06-7b91-11e7-961c-0e4a5630a47b.PNG)

1.3.3 (17.05.10.13)
![img_0048](https://user-images.githubusercontent.com/28145373/29045352-4d41ae9a-7b91-11e7-9a66-d514f139f89c.PNG)

- Any related issues:

**Comment by Jacalz** [comment]
Same thing happens on iPhone too, hur need to change the rotation to lanscape sometimes and also see the exact same behavior like in Firefox, find it strange that they haven’t gotten a bug report yet 😅

**Comment by Jacalz** [comment]
Changed the name since I see this on iPhone too 🙂

**Comment by jamesmudgett** [comment]
Looks like the push 82be22b likely doesn't impact this at all; however, this message hasn't appeared in further testing on both iOS and Android.

**Comment by LaurenWags** [comment]
Still experiencing this on 1.4.1 (17.08.21.09)

![fb_unsupported](https://user-images.githubusercontent.com/28145373/29529429-a3344182-866d-11e7-94a1-75ec18cbcb3d.gif)

**Comment by Jacalz** [comment]
To be honest, I am not seeing this on the latest build 😅

**Comment by Jacalz** [comment]
On iPhone the warning is gone but have yet to chbe close on iPad 😉 @laurenwags

**Comment by srirambv** [comment]
Closing as its working on iPad with iOS 11

**Comment by LaurenWags** [comment]
Still experiencing this on 1.5 (17.10.24.14) on an iPad with iOS10.

**Comment by srirambv** [comment]
Looks to be an issue with iPad on iOS 10. I don't see the error on iPhone running iOS 10.

**Comment by LaurenWags** [comment]
I concur, I also don't see it on an iPhone using iOS 10.

**Comment by srirambv** [comment]
Still shows on iPad(iOS 11) on 1.5.1 but not on iPhone(iOS 11)
