### ISSUE TITLE
Pull down refresh doesn't reload when focus is on input field

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1043]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Pull down refresh doesn't work when focus is on input field

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (10.3.3)

- Brave Version:
1.4 (17.08.04.20)

- Steps to reproduce:
    1. Install/Upgrade to 1.4
    2. Visit facebook.com and tap on login field, so that keyboard pops up
    3. Pull down refresh doesn't reload the page

- Actual Behavior
Pull down refresh doesn't reload when focus is on input field

- Expected Behavior
Should reload irrespective of what field is in focus

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down?  N/A
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?  Yes verified on Puffin and reloads the page. Firefox/Dolphin doesn't have pull down refresh

- Screenshot if needed:

- Any related issues:
cc: @jamesmudgett @jhreis

**Comment by jhreis** [comment]
We are removing pull to refresh, so this is fixed :D

**Comment by Jacalz** [comment]
It is one of those feature that is a must have some times and very annoying sometimes 🙂
