### ISSUE TITLE
 handle / or no / at the end of urls for HTTPS Everywhere

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-ios#105]
Hi @garvankeeley,

Please verify those two links. As it doesn't give me https version for #1 but gives for #2 and the website loads incorrectly in #2 case. So I just remove '/' at the end of host when search for rulesets.

**Comment by garvankeeley** [comment]
Thanks, based on this tip I added code to handle / or no / at the end of urls, and added a test case. 
Regardless, news.yahoo.com does not redirect for me to https

**Comment by garvankeeley** [comment]
Edited title, the links to confirm that comment 1 refers to are http://news.yahoo.com and http://news.yahoo.com/
