### ISSUE TITLE
visiting any of the about: pages crashes Brave

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-ios#1050]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Visiting any of the about: pages will cause Brave to instantly crash.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6s running iOS 10.3.3 - Reproduced
iPhone 6s+ running iOS 10.3.3 - Reproduced
iPad Mini 4 running iOS 10.3.3 - Reproduced

- Brave Version:
v1.4 (17.08.08.08) - Reproduced on all of the above devices
v1.4 (17.08.04.18) - Reproduced on all of the above devices

- Steps to reproduce:
    1. In the URL bar, visit about:brave, about:bookmarks, about:adblock etc..
    2. Brave will instantly crash

- Actual Behavior
Brave crashes/closes instantly whenever an about: page is being loaded.

- Expected Behavior
From what I remember, in the past we would just load a blank page for about: pages that weren't supported under iOS. Brave shouldn't be crashing.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes, issue is 100% reproducible following the above STR.

**Comment by kjozwiak** [comment]
bt: [backtrace.txt](https://github.com/brave/browser-ios/files/1223989/bt.txt)

**Comment by kjozwiak** [comment]
I can still reproduce this using the following builds, including the latest master ec94ec0958fa650dca59c78b662f7bf86c0ba9d5:

Brave Version:
v1.4.1 (17.08.24.18) - Reproduced (BETA build currently being listed under Crashlytics
v1.4.1 (17.08.25.08) - Reproduced (current RC)
v.1.4.1 (17.08.28.10) - Reproduced (lastest master ec94ec0958fa650dca59c78b662f7bf86c0ba9d5 )

Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6s+ running iOS 10.3.3 - Reproduced
iPad Mini 4 running iOS 10.3.3 - Reproduced

I went through the git log and ensured that the fix was committed:

> commit 72e686ee9713e8058be7d8357450cd90a9fcc192
> Author: Joel Reis <joelhreis@gmail.com>
> Date:   Tue Aug 15 16:42:38 2017 -0400
> 
>     Fix #1050: Forced unwrapping of URL host on reload, was causing crash.

Attached Stack: [Crash Stack](https://github.com/brave/browser-ios/files/1258072/btSack.txt)

**Comment by jhreis** [comment]
Thanks for rechecking this. Glad it didn't get lost!
