### ISSUE TITLE
Prisjakt search engine does not work

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#1052]
## STR for QA to test
1. Set device region to Sweden
2. Set prisjakt as default search engine
3. Type ASUS in adress bar and hit search
4. Make sure that it searched for ASUS on the website

### Original Description
- Did you search for similar issues before submitting this one?
Yes
- Description:
The Swedish search engine called "prisjakt" does not work to search with because the browser makes the wrong url to search with.

This is how it should look like:
https://m.prisjakt.nu/search/yoursearchhere
How it look in firefox ios and brave ios:
https://m.prisjakt.nu/?mobil_search=yoursearchhere
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Iphone 5s and Ipad Air 2
- Brave Version:
1.4 and 1.3.3
- Steps to reproduce:
    1. Search using prisjakt
    2. you will see that you just come to the start page with whatever you typed
    3.

- Actual Behavior
You come to the start page
- Expected Behavior
It should search for the word you typed
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 
I did check in firefox ios and the same thing happens there

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
I do not see prisjakt  as search engine when language set to Swedish. Not very clear on the expected result. This is what I see on iPad 
![image](https://user-images.githubusercontent.com/17010094/32234406-8fc6964e-be54-11e7-8236-4b7ccc19766d.png)

**Comment by Jacalz** [comment]
That is the correct behavior, you need to set region to Swedish 😅 My bad on that, I forgot to change it 🙂😉

**Comment by Jacalz** [comment]
I updated the STR on top, issue might be iPhone specific. Will have a look 👀
