### ISSUE TITLE
4chan shows a blank page

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#1054]
- Did you search for similar issues before submitting this one?
Yes

- Description:
A user from community has reported that 4chan.org shows a blank page.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone6s+

- Brave Version:
1.4

- Steps to reproduce:
    1. Visit 4chan.org

- Actual Behavior
Blank page is shown

- Expected Behavior
The page should render properly

- Is this an issue with Beta build?
No

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
Yes

- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 
Yes

- Screenshot if needed:

- Any related issues:

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/4chan-org-does-not-load-at-all-on-brave-ios/5579?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/iphone-brave-cannot-open-certain-websites/10833?u=eljuno

**Comment by iccub** [comment]
FYI: 4chan works fine without HttpsEverywhere enabled.

Will try to fix it this week.

**Comment by iccub** [comment]
Small update: so the issue is fixed, but won't be shipped with the next version(1.5.2), it requires us to use different regex library for parsing httpse rules and we need more time to test it.

We plan to ship it with 1.5.3
