### ISSUE TITLE
Copy url does not work sometimes on 1.4 17.08.08.08

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#1058]
- Did you search for similar issues before submitting this one?
Yes
- Description:
Sometimes the url bar copy paste stops working and the browser needs a restart to function properly again...
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 5s
- Brave Version:
1.4 17.08.08.08
- Steps to reproduce:
    1. Go to random site
    2. Copy paste issue from the url bar
Alternative 2. Copy paste by pressing and holding on a url on a web page
3. Go to slack and paste

- Actual Behavior
Does not copy
- Expected Behavior
Paste should work
- Is this an issue with Beta build?
Have not seen it yet
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
No
- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by Jacalz** [comment]
Assigned this to 1.4.1 milestone since I have seen it happened a lot of times but please re assign to another milestone if needed 🙂

**Comment by jonathansampson** [comment]
This sounds eerily similar to an issue reported on Twitter today.

![image](https://user-images.githubusercontent.com/815158/33251870-baf6e548-d2ff-11e7-8e3c-8a8b12c0d15a.png)

Source: https://twitter.com/tsunamino/status/935005621669076995

**Comment by iccub** [comment]
Moving to 1.5.2, did some testing and it will be most likely fixed by #1314

**Comment by jhreis** [comment]
User's issue from Twitter is actually this:
https://github.com/brave/browser-ios/issues/1239

**Comment by jhreis** [comment]
Any update on this (cc'ing @Jacalz)?

**Comment by Jacalz** [comment]
Have definitely not noticed this since, I belive it is fixed 🤗

**Comment by jhreis** [comment]
Sounds good, closing for now.
