### ISSUE TITLE
refreshing a page that was shared via another app before it loads crashes browser

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-ios#1059]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Refreshing a page that's still being loaded into Brave from another application crashes the browser. If a user manages to refresh the page while it's still completely white and hasn't started loading content, the browser will end up crashing.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6s+ using 10.3.3 - Reproduced
iPad Mini 4 using 10.3.3 - Reproduced

- Brave Version:
v1.4 (17.08.08.08) - Reproduced
v1.4 (17.08.04.18) - Reproduced
v1.4 (17.08.14.21) using the latest branch -> 5b2e10e377cf9991977c18c824a5c5664a185af9 - Reproduced

- Steps to reproduce:

1. open https://www.gog.com in safari
2. tap on the "share" button and select Brave
3. once Brave starts loading the page, quickly swipe down and refresh the page when it's still attempting to establish a connection and hasn't loaded any content

- Actual Behavior
Brave crashes when attempting to refresh pages that haven't been completely loaded.

- Expected Behavior
Brave shouldn't be crashing and should attempt to refresh the page even though it hasn't been loaded

- Is this an issue with Beta build?
Yes (also happens with the latest 5b2e10e377cf9991977c18c824a5c5664a185af9 branch)

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes, 100% reproducible

- Screenshot if needed:
Example of issue: [https://youtu.be/jJfla5iOMWQ](https://youtu.be/jJfla5iOMWQ)
stack trace of crash while using 5b2e10e377cf9991977c18c824a5c5664a185af9: [stack trace](https://github.com/brave/browser-ios/files/1224146/bt.txt)

Any related issues:

Possibly related to #926 as they're both using "Open in Brave". The difference is that in #926, Brave crashes instantly and with this particular case, the user needs to refresh. I'll try getting a stack trace for #926 as I've reproduced it a few times in the past.

**Comment by kjozwiak** [comment]
I can't reproduce this issue anymore using `1.4.2 (17.09.07.20)` with the STR mentioned above.

Devices being used:

* iPhone 6s+ using iOS 10.3.3 - Couldn't Reproduce
* iPad Mini4 using iOS 10.3.3 - Couldn't Reproduce

**Comment by jhreis** [comment]
Closed via fix from #1136
