### ISSUE TITLE
Top Sites Tiles cleared after exiting 'Private Browsing Only'

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1063]
- Did you search for similar issues before submitting this one?
Yes

- Description:
I had top sites tiles prior to using the 'Private Browsing Only' setting. However, after exiting Private Browsing Only (and going back to normal mode), my top tiles sites were gone.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad

- Brave Version:
1.4 (17.08.08.08)

- Steps to reproduce:
    1. Verify top sites tiles exist.
    2. Open settings and enable 'Private Browsing Only'.
    3. Open several tabs and navigate to some sites.
    4. Close from background. Relaunch Brave.
    5. Go to settings, turn off 'Private Browsing Only'. 
    6. On the new tab that is displayed, no top sites tiles are shown.

- Actual Behavior
No top site tiles displayed when you go back to normal mode.

- Expected Behavior
Prior top site tiles should be displayed.

- Is this an issue with Beta build?

- Is this an issue in the currently released version? in 1.4 yes

- Can this issue be consistently reproduced?

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
Should be retested with top sites being replaced by favorites.

**Comment by LaurenWags** [comment]
Could not reproduce on iOS10 iPad or iPhone both using version 1.6.2 (18.05.29.10)
