### ISSUE TITLE
Keyboard and TextFields Issue with some sites

### ISSUE THREAD

**Issue by kunalverma25** [brave/browser-ios#1077]
- Did you search for similar issues before submitting this one?
Yes

- Description:
When clicked on a TextField in an overlay from a page, the textfield goes behind the HTML content and below the Keyboard.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad Air, iPhone 6, Simulator

- Brave Version:
Current Git Clone (1.4.1 Beta)

- Steps to reproduce:
    1. Open BraveBeta in iPad Landscape Orientation (iPhone with desktop tab)
    2. Go to https://groceries.morrisons.com
    3. Tap Login Button from the top panel
    4. Tap the e-mail field

- Actual Behavior
Textfield goes below keyboard, when scrolled HTML content from behind overlay comes up.
Screenshot Attached - 

![simulator screen shot 22-aug-2017 6 06 20 pm](https://user-images.githubusercontent.com/5118260/29565698-a0e9fc6c-8764-11e7-803a-a15dad9d7be0.png)

- Expected Behavior
Textfield should remain above Keyboard with the overlay element.
Screenshot Attached (Taken with a simple UIWebview loading the same page) -
![simulator screen shot 22-aug-2017 6 09 54 pm](https://user-images.githubusercontent.com/5118260/29565814-22f69e0e-8765-11e7-9b9b-871ac75cd92d.png)

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
Yes, Still same issue

- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 
Yes, checked with a simple UIWebView in XCode, works as intended.

- Screenshot if needed:
Attached above with behavior details

- Any related issues:
N/A

**Comment by kunalverma25** [comment]
Same issue with many sites with overlays.
Eg. ocado.com (open in desktop mode)
Click login from top menu.
Follow same steps as above and the issue comes up.

Its a similar issue as 216.
Can be avoided if setBottomInset(h) is not called.
But not a permanent solution.
Many sites use overlays on iPads.

**Comment by jhreis** [comment]
Not currently seeing this on iPhone, so probably an iPad only issue, unless I am just not seeing it.

Can you please include a commit hash if you are working directly off of master?

**Comment by kunalverma25** [comment]
@jhreis 
Steps to recreate on iPhone - 

1. open https://groceries.morrisons.com
2. Tap share icon and open in desktop tab
3. Tap login button on top.
4. Tap E-mail textfield

If setBottomInset(h) is commented out, then the textfield will be in view, but if not, the issue is visible.

**Comment by srirambv** [comment]
This will be an issue on smaller screen size devices. 
![image](https://user-images.githubusercontent.com/17010094/30210466-acbe9948-9494-11e7-9b95-81a8c46541f7.png)

**Comment by kunalverma25** [comment]
@srirambv 
Still its better than not getting to see the forms at all.
But yeah on smaller screens this sort of situations will arise on every webview.
