### ISSUE TITLE
Check adblock on particular sir

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#108]
It's not clear if it's intermittent or not, pls try. You might need to back-post an issue to abp-filter-parser-cpp and close this if the problem is there.

From a friend:
> So I was reading an article about Paul Allen's boat messing up the reef when I noticed that the ads were still appearing for that particular website.. I double checked and made sure that the ad-blocker was enabled and also visited slashdot to make sure ad's weren't appearing.. Attached two images as well from the same session.

> STR:
> load https://caymannewsservice.com (you'll notice ads are appearing)
> load https://slashdot.org (Brave placeholders on the ads)

![adsappearing](https://cloud.githubusercontent.com/assets/831718/12695794/c53d3da4-c726-11e5-8fbf-6ffa4a7dc259.PNG)

![noadsappearing](https://cloud.githubusercontent.com/assets/831718/12695798/cc809b10-c726-11e5-9eea-17545cbd3a8a.PNG)

**Comment by garvankeeley** [comment]
closing, same on desktop:
<img width="1039" alt="screenshot 2016-01-30 14 06 39" src="https://cloud.githubusercontent.com/assets/5495083/12726441/98dfed04-c8e5-11e5-8bbf-ffd641b3e14e.png">
