### ISSUE TITLE
site not loading in selected tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1082]
- Did you search for similar issues before submitting this one?
Yes

- Description:
If you attempt to reuse an older tab to navigate to a new site (ex. a tab that's been open since your previous session), the site doesn't open in the reused tab, it loads in the last tab in your tabset, overwriting whatever was open in that tab.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad and iPhone6

- Brave Version:
1.4.1 (17.08.21.17)

- Steps to reproduce:
    1. Clean install of 1.4.1.
    2. Open several tabs (I had 4 open with 4 different sites: Facebook, Amazon, Wikipedia, Twitter).
    3. Close Brave from running in the background.
    4. Wait at least 5 minutes.
    5. Relaunch Brave.
    6. Navigate to a tab that was not the active tab.
    7. In the URL bar, type a new URL.
    8. New site doesn't load, tab stays white.
    9. Go to the last tab, it is loaded with the site you tried to access.

- Actual Behavior
Site is not loaded in the tab you chose, it is loaded in a different tab overwriting what was open in that tab previously.

- Expected Behavior
Site should be loaded in the tab you chose.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Yes, 1.4 (17.08.08.08)

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by iccub** [comment]
Cannot reproduce this, but similar thing happened to me while updating app store version.

Had 1.4 installed but wasn't using it too much, downloaded update, opened app, don't remember if there was any tab opened but I couldn't go to any website, just white screen and had to kill the app to make it work.

**Comment by srirambv** [comment]
Not reproduced on appstore build on iOS 11
