### ISSUE TITLE
Pin input controller

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-ios#1089]
# Test plan

    1. should work with various screen sizes.
    2. lock portrait on iPhones, enable landscape display on iPad

# 

![image](https://user-images.githubusercontent.com/318119/29629630-24b5c932-87ff-11e7-9f92-2828702c7044.png)

## Setting Pin

- Setting a new pin, tap “Pin” from settings menu when BrowserLock is enabled.
- If no pin is set, prompt user with “Enter New Pin”, then confirm with “Re-Enter New Pin”
- If a pin is set, prompt user to “Enter Existing Pin”, then proceed with previous steps to set new pin.

## Pin Controller UX

- always display active digit in indicator, display input digit as solid.
- after input of last digit all indicators should be solid
- shake animation to be called in error state.
- support title changes above indicators
- can be used in a viewcontroller (settings) or as an overlay view (app launch)

## Testing

- should work with various screen sizes.
- lock portrait on iPhones, enable landscape display on iPad

**Comment by srirambv** [comment]
Browser orientation change doesn't apply when browser pin is set. Test plan step 2 fails.
