### ISSUE TITLE
URL bar doesn't always display URL

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1107]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Found while testing https://github.com/brave/browser-ios/issues/1008. Tabs all display titles now, but if you tap on one of the first tabs in the tabset, the tab loads and the URL bar is blank. Reload icon in URL bar and share menu are both inaccessible.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad (landscape mode), iPhone (landscape mode)

- Brave Version:
1.4.1 (17.08.24.09)

- Steps to reproduce:
    1. Open multiple tabs (you need to be able to scroll through the tabs, so you want 12+ tabs)
    2. Close/Re launch Brave. 
    3. Scroll back to the beginning of the tabs. 
    4. Tap on one of the first tabs.
    5. Page loads, but URL bar doesn't contain URL.

- Actual Behavior
URL bar doesn't contain URL. Reload icon in URL bar and share menu are both inaccessible (tapping on them doesn't work). You must leave this tab and come back to see the URL.

- Expected Behavior
URL bar should contain the URL of the site loaded in the tab.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

![img_0062](https://user-images.githubusercontent.com/28145373/29672656-e82bfec0-88ba-11e7-8548-ddec4eb2662b.PNG)

- Any related issues:

**Comment by srirambv** [comment]
Happens on tab which is not partially loaded upon relaunch. Verified on iPhone too.

**Comment by srirambv** [comment]
Happens when exiting from private tabs also

**Comment by jhreis** [comment]
This is a much larger issue than just the URL bar. It is actually in a broken state, it seems to think it is sitting on localhost or some such nonsense. The refresh, action, and bookmark options are all disabled as well. 

You can force a refresh by selecting the URL bar, and hitting `return` (it won't display anything initially).

**Comment by LaurenWags** [comment]
Still seeing this issue as described.

![img_0068](https://user-images.githubusercontent.com/28145373/29685754-69e0dcb4-88e4-11e7-8074-04fd5e48b827.PNG)

**Comment by LaurenWags** [comment]
Did not encounter this while testing 1.4.1 (17.08.24.18) on iPad or iPhone6.

**Comment by Jacalz** [comment]
Yeah I can confirm that this is fixed when using (17.08.24.18) 👍
