### ISSUE TITLE
Reader mode settings not shown after relaunching the app

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1109]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Reader mode settings not shown after relaunching the app

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (10.3.3)

- Brave Version:
1.4.1 (17.08.24.09)

- Steps to reproduce:
    1. Visit http://theverge.com, open an article in reader mode
    2. Change backgorund from reader mode settings and close the app from background
    3. Relaunch the app, reader mode settings is missing

- Actual Behavior
See Screenshot

- Expected Behavior
Should always show the reader mode setting

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/29674651-b6860e80-88ea-11e7-9f31-e48e97f4d524.png)

- Any related issues:

**Comment by LaurenWags** [comment]
removed iPhone tag since I reproduced on iPad

**Comment by srirambv** [comment]
Switching tabs shows the setting option again similar to #1107

**Comment by srirambv** [comment]
Still happens on the RC build. After app is relaunched, swipe back doesn't work although the page history back button is enabled. Pull down reload clears the reader mode and makes it a new tab.
