### ISSUE TITLE
macworld.com links not loading

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#111]
Needs more investigation, shutting off adblock and TP makes it work

**Comment by bbondy** [comment]
macworld.com and possibly other sites don't work properly when the images are blocked.

Using a 1px transparent image is cleaner and also we can remove some preload script which hides the canceled images. So net it should be faster.

See details here:
SergeyZhukovsky/tracking-protection#5

Doing this on laptop works for me.

**Comment by bbondy** [comment]
Fix needs to be done for each platform though and not in the TP lib.
