### ISSUE TITLE
Blocked ad frame shown on theverge.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1110]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Blocked ad frame shown on theverge.com

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (iOS 10.3.3)

- Brave Version:
1.4.1 (17.08.24.09)

- Steps to reproduce:
    1. Visit https://theverge.com
    2. Main page shows blocked ad frame
    3.

- Actual Behavior
See screenshots

- Expected Behavior
Should block the frame as before

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only:  Yes
- did you check with Brave Shields down?  N/A
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?  N/A

- Screenshot if needed:
1.4 (17.08.08.08)
![image](https://user-images.githubusercontent.com/17010094/29674943-92010cc6-88eb-11e7-9bcf-1486e8c1c286.png)
1.4(17.08.24.09)
![image](https://user-images.githubusercontent.com/17010094/29674975-a84d0b56-88eb-11e7-8913-73080e129ed3.png)

- Any related issues:

**Comment by jhreis** [comment]
I don't think there is anything here for us to do. The ad request is blocked, but the verge has decided to render a location for it in the HTML anyway. This is more like a first party ad that would require DOM manipulation. Probably not something we'll be dealing with anytime soon. Most certainly is just a website change.

**Comment by srirambv** [comment]
Works as expected. Script block removes the frame. Closing the issue
