### ISSUE TITLE
Add pocket integration

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#1124]
- Did you search for similar issues before submitting this one?
Yes
- Description:
Add pocket integration to save pages for offline reading 👍

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/share-to-pocket-does-not-work-on-ios/7239?u=eljuno

**Comment by Melvillian** [comment]
+1 It's the only thing stopping me from using Brave full time on iOS

**Comment by iccub** [comment]
Pocket share extension works on the newest Brave version(1.5)

Enable it the same way as on safari https://help.getpocket.com/article/919-enabling-the-pocket-share-extension-in-ios

Let us know if you'll encounter any problems using Pocket with Brave

**Comment by kjozwiak** [comment]
Created #1335 when going through Pocket Integration.
