### ISSUE TITLE
Save Login UI issues 

### ISSUE THREAD

**Issue by kunalverma25** [brave/browser-ios#1129]
- Did you search for similar issues before submitting this one?
Yes
- Description:
UI issues
- Device
iPhone6, Simulator
- Brave Version:
1.4.1 beta
- Steps to reproduce:
    1.
    2.
    3.

- Actual Behavior
![img_1137](https://user-images.githubusercontent.com/5118260/29717457-ddd53e38-89cc-11e7-895f-18f0635bbc93.PNG)

- Expected Behavior
Password saving option should be properly visible.
- Is this an issue with Beta build?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
Please include the full version for beta builds. This should be fixed latest version: 1.4.1 (17.08.24.18)

See: https://github.com/brave/browser-ios/issues/1113

If this issue still exists, please use original reference. Great find btw!
