### ISSUE TITLE
Can't access settings or private mode unless a tab is open

### ISSUE THREAD

**Issue by JoshAtAvenza** [brave/browser-ios#113]
The buttons to access settings and private mode are on the tab selector pane.  I can't access that unless I have at least one tab open.  Was a little confusing on first run as I was trying to find private mode and couldn't.  Usually I do have at least one tab open, so this is minor

**Comment by garvankeeley** [comment]
Settings is now accessible in the side panel. Private mode we are still working on the UI for, so I'll close this for now
