### ISSUE TITLE
Clear Cache + reload page (button/shortcut) - suggestion

### ISSUE THREAD

**Issue by guategeek** [brave/browser-ios#1132]
**Clear Cache+reload page option**

As a web developer its annoying to have to go into preferences to clear the cache. It would be nice if you could hit the reload button with a modifier key held down to reload the page with a clear cache automatically done before hand. And/Or have a keyboard shortcut for clearing the cache and then reloading the page.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Mac OS

**Comment by jhreis** [comment]
@guategeek This is the Brave iOS repo, this appears to be intended for the desktop repo:
https://github.com/brave/browser-laptop

Closing, will reopen if there is a misunderstanding.

**Comment by guategeek** [comment]
Oh my bad, sorry for the hassle, I have posted this on the desktop version.
