### ISSUE TITLE
Launch Delays

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#1135]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Launching Brave application takes far too long

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All

- Brave Version:
1.4.1 (was introducing 1.4)

- Steps to reproduce:
    1. Make sure Brave is removed from memory (e.g. swipe up)
    2. Launch Brave
    3. Observe slow launch times

- Actual Behavior
Launches slow

- Expected Behavior
Launch fast

- Is this an issue with Beta build?
N/A

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-ios/issues/1064: This was in response to _massive_ launch delays. It has greatly improved beyond this, but still needs much more work.

**Comment by jamesmudgett** [comment]
Related: https://github.com/brave/browser-ios/issues/1192
