### ISSUE TITLE
Google Search Sponsored Ads  

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-ios#114]
Can't open/click on Google Search Sponsored Ads while Ad Blocked is enabled.  When disabling Ad Blocking, the links work fine.

**Comment by garvankeeley** [comment]
Thanks for report, confirmed, should be due to this:
https://github.com/bbondy/abp-filter-parser-cpp/issues/19

**Comment by garvankeeley** [comment]
Fixed by  	7bc8aa1
Which led to this:
https://github.com/brave/browser-ios/issues/121
Which is also fixed :)
