### ISSUE TITLE
brave crashes when closing large amounts of tabs via the tab manager

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-ios#1150]
**- Did you search for similar issues before submitting this one?**

Yes

**- Description:**

Brave often crashes when closing a large amount of tabs in quick succession. Stack crash:

```
 frame #1: 0x00000001002d6aa0 Client`Browser.deleteWebView(isTabDeleted=true, self=0x0000000133b8d7e0) -> () at Browser.swift:297
 frame #2: 0x00000001002d759c Client`Browser.__deallocating_deinit(self=0x0000000133b8d7e0) at Browser.swift:324
 frame #3: 0x00000001002d7600 Client`@objc Browser.__deallocating_deinit at Browser.swift:0
 frame #4: 0x0000000100361f30 Client`___lldb_unnamed_symbol827$$Client + 40
 frame #5: 0x00000001003620d4 Client`block_destroy_helper at FaviconManager.swift:0
```

[Full Crash Stack available here.](https://github.com/brave/browser-ios/files/1279515/crashStack.txt)

**- Device (iPhone5, iPhone6s plus, iPad 3, ?):**

iPhone 6s+ using 10.3.3 - Reproduced

**- Brave Version:**

1.4.1 (17.09.05.20) using 9ddc4929252f639e4145a7d1392ec66af3b8af88 - Reproduced (local build)

**- Steps to reproduce:**

1. Open Brave -> Settings -> Load All QA Tabs
2. Repeat (you should have 45 tabs opened at the same time
3. click on the "Tab Manager" and start closing tabs one by one in quick succession

**- Actual Behavior**

Brave crashes when a user is closing a lot of tabs in quick succession

**- Expected Behavior**

Brave shouldn't be crashing when a user is closing a lot of tabs in quick succession

**- Is this an issue with Beta build?**

I couldn't reproduce it after a several tries but it's a lot harder to get 45 tabs opened without the "Load All QA Tabs" feature that's integrated into the local build.

**- Is this an issue in the currently released version?**

I couldn't reproduce it after a several tries but it's a lot harder to get 45 tabs opened without the "Load All QA Tabs" feature that's integrated into the local build.

**- Can this issue be consistently reproduced?**

Yes, you can usually reproduce the issue on the local build when using the "Load All QA Tabs" feature.

**Comment by kjozwiak** [comment]
@jhreis I didn't stick this into a milestone due to not being able to reproduce the issue on the currently released version. However, it could still be in that version but it's a lot harder to reproduce as you need a large amount of tabs opened. It's easier to reproduce locally using the "Load All QA Tabs" feature.

Let me know if you want me to pull the changeset for the release build and see if I can reproduce it there.

**Comment by srirambv** [comment]
Not crashing on the appstore version. Loaded QA tabs twice with a few existing tabs making tab count upto 53 tabs. Closed all tabs in quick succecssion but didn't crash.

**Comment by kjozwiak** [comment]
I've tried this countless of times with the latest iOS build and couldn't reproduce it either on iOS 10 & iOS 11.
