### ISSUE TITLE
Opening a link in a new tab shows blank tab before loading the page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1156]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Opening a link in a new tab shows blank tab before loading the page

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 11)
iPhone 7+ (iOS 10.3.3)

- Brave Version:
1.4.2 (17.09.07.20)

- Steps to reproduce:
    1. Open any page in a new tab
    2. Long press on any link and tap on open in a new tab
    3. Immediately switch to the new tab, entire tab is blank momentarily before loading the page

- Actual Behavior
Opening a link in a new tab shows blank tab before loading the page

- Expected Behavior
Should load the page immediately 

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by LaurenWags** [comment]
I have not been able to repro this on iPad or iPhone6.
