### ISSUE TITLE
Share via extension

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#116]
From a friend:
Currently, there's no way of sending links from Twitter and other apps into Brave via "Share Via..". 

Example of other browsers:
Chrome:
- has an "Open in Chrome" icon
Safari:
- has "Open in Safari" icon
Firefox
- has "Add to Reading List" icon
- has "Send to Tab" (needs to signed into Firefox Accounts) icon
- has a "Firefox" icon that lets you "Add to Reading List, Add to Bookmarks"

Right now, the only way to view links via Twitter and other applications under Brave is copying the link and pasting it into Brave which isn't a great experience.

**Comment by garvankeeley** [comment]
+1
