### ISSUE TITLE
Browser asks for pin when app overview is selected 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1167]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Browser asks for pin when app overview is selected 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad (iOS 11)

- Brave Version:
1.4.3
- Steps to reproduce:
    1. Enable browser lock pin
    2. Swipe up to view apps
    3. Browser pin lock notification is shown

- Actual Behavior
See attached recording

- Expected Behavior
Should only prompt for pin when app is made active
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
N/A
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
https://drive.google.com/open?id=0B5ts9vcrIgmiR2NlM2liY3ROXzQ
- Any related issues:

**Comment by jamesmudgett** [comment]
@srirambv any other iPad versions you can test with? This seems like an iOS 11 bug given it's still not out of beta, doesn't happen on other iOS versions.

**Comment by srirambv** [comment]
I only have iOS11 running on iPad. @laurenwags or @kjozwiak could you try it on iPad running iOS 10

**Comment by kjozwiak** [comment]
>  @LaurenWags or @kjozwiak could you try it on iPad running iOS 10

I couldn't reproduce this with iOS 10.3.3 on my iPad Mini 4 using `1.4.3 (17.09.14.16)`. Double clicking the "Home" button correctly shows all the applications that are currently opened without receiving a Brave verification modal. I also switched between several different applications while Brave was running locked in the background without any issues.

As @jamesmudgett mentioned above, this looks like an iOS 11 issue.

**Comment by srirambv** [comment]
@jamesmudgett should the app request or pin even when the control center is accessed with brave as active app?
