### ISSUE TITLE
Unable to close background app when browser lock is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1168]
- Did you search for similar issues before submitting this one?
Yes
- Description:
Unable to close background app when browser lock is enabled
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad (iOS 11)
- Brave Version:
1.4.3(17.09.12.16)
- Steps to reproduce:
    1. Enable browser lock for Brave
    2. Background the app and swipe up to see app overview 
    3. Try closing the background app, browser lock pin is shown
    4. Even if you swipe up to kill process, browser-lock pin brings back the process

- Actual Behavior
See the end of the recording
- Expected Behavior
Should allow user to kill the app from background
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
https://drive.google.com/open?id=0B5ts9vcrIgmiR2NlM2liY3ROXzQ

- Any related issues:
#1167

**Comment by jamesmudgett** [comment]
related https://github.com/brave/browser-ios/issues/1167
