### ISSUE TITLE
Settings suggestions

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#117]
Suggestions from a friend:

This isn't really a big deal right now as there isn't a lot of settings available right now, but I think "Block Ads, Tracking Protection, HTTPS Everywhere, Accept Cookies" should all go into another category inside the settings named "Security" or "Privacy". You should really include a "Clear History" as the only way of doing it right now is going through each entry individually and removing them under the "History" tab.

**Comment by garvankeeley** [comment]
+1

**Comment by garvankeeley** [comment]
Fixed by b82bc4e38fe609858a3277424dbd09e8b68888c6
