### ISSUE TITLE
Confirm old pin before setting new pin

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1171]
# Test plan
1. Set browser pin
2. Tap on set pin
3. Ensure it asks for existing pin before setting up a new pin
# 
- Did you search for similar issues before submitting this one?
Yes
- Description:
@jhreis suggested to confirm old pin before setting new pin
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All
- Brave Version:
1.4.3(17.09.12.16)

- Screenshot if needed:

- Any related issues:

**Comment by LaurenWags** [comment]
Not being asked to confirm old pin prior to setting a new one STR:
Clean install of 1.5 (17.10.12.08)
Go to Settings
Tap on Pin.
Enter and confirm pin, you are taken back to main settings page.
Tap on Pin again.
You are asked to 'Enter a New Pin' not enter current pin/confirm current pin (something to that effect).

**Comment by srirambv** [comment]
Working as per test plan. Verified on iPad iOS 11 and iPhone 7+ iOS 10
