### ISSUE TITLE
Crash after switching to PB only (restoring non-private tabs in background?)

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-ios#1174]
- Did you search for similar issues before submitting this one?
Yes
- Description:
follow steps here https://github.com/brave/browser-ios/issues/1075 attempts to load non-private site tabs then crashes.
- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:
1.4.5/1.5
- Steps to reproduce:
    1.
    2.
    3.

- Actual Behavior

- Expected Behavior

- Is this an issue with Beta build?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by LaurenWags** [comment]
Could not reproduce on iOS10 iPhone both using version 1.6.2 (18.05.29.10)
