### ISSUE TITLE
Long press new private tab option for iPhone

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1189]
- Did you search for similar issues before submitting this one?
Yes
- Description:
Long press on new tab icon to show new private tab similar to close tab popup option
- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:
1.4.3

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/30589899-ef0bdcf2-9d59-11e7-9326-9c0974b6d910.png)

- Any related issues:

**Comment by jamesmudgett** [comment]
Good idea
