### ISSUE TITLE
Tab limit and context menu option

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#119]
So this is expected, but seems like it's confusing. How do other browsers handle?

From a friend:
> Seems like there's a limitation with "Open in New Tab", if you open 9 tabs, the "Open in New Tab" choice will disappear when you tap and hold on links.. STR:
Tap on a link and select "Open in New Tab" (do this 9 times so you have 9 tabs opened in the browser)
Tap on the 10th link and you'll notice "Open in New Tab" has disappeared and "Copy Link" and "Share Link" are the only choices that are left
I'm not sure if this is a bug or a limitation, but I think it should be fixed.. Attached a video of the issue

https://youtu.be/UObGpTDnmV0

**Comment by garvankeeley** [comment]
They keep 9 tabs as active UIWebView objects, the rest as just an url and a screenshot. If the user chooses a non-UIWebView backed tab, then the oldest UIWebView tab gets turned into an url and a screenshot, the history extracted and saved to a data structure, and a new UIWebView is created and the url for the selected tab is loaded. 
For non-UIWebView-backed tabs, they can't save page state, the page just loads fresh. They also need to reconstitute their history state, which is very complicated to do.

**Comment by bbondy** [comment]
More on this from him:
> Ya but let's say for my use case... I'm about to go on the subway and I know I'll lose the signal... So I load tons of articles that I would like to read before losing the signal. Loading only 9 tabs is a pretty bad limitation imo. With Safari/Firefox, you can load as many as you would like.

NP just sharing feedback about it.

**Comment by garvankeeley** [comment]
I agree, but even Safari did this until iOS 8 and I am not sure this was a common complaint. All UIWebView-based browsers do this AFAIK.

**Comment by garvankeeley** [comment]
fixed in 1.1
