### ISSUE TITLE
Support for blocking cross-site tracking?

### ISSUE THREAD

**Issue by rogersachan** [brave/browser-ios#1190]
**Did you search for similar issues before submitting this one?**
Yes

# Feature Request
Seeing as Apple is doing this now, I see good reason to be one of the first **cross-platform** solutions to do this.

# Sources
* https://webkit.org/blog/7675/intelligent-tracking-prevention/
* https://techcrunch.com/2017/06/05/apple-adds-a-tracker-blocker-to-desktop-safari/
* https://9to5mac.com/2017/09/16/apple-ad-tracking-statement/
* https://www.engadget.com/2017/09/16/advertisers-are-upset-with-safaris-new-anti-tracking-features/

**Comment by jhreis** [comment]
Brave on all platforms currently blocks all trackers and ads, we even blocks 3rd party cookies by default. Additionally, with HTTPSE we also push all resources to load via HTTPS whenever possible, and provide fingerprint protection.

If you find any issues with Brave's implementation about the above features, please file a new ticket and let us know!
