### ISSUE TITLE
On startup webpages of all tabs simultaneously fetched leading to slow loading of webpage

### ISSUE THREAD

**Issue by artella-coding** [brave/browser-ios#1192]
- Did you search for similar issues before submitting this one? Yes

- Description: Upon a fresh start, brave browser seems to fetch all tabs simultaneously which results in slow fetching of the webpage of the current tab. It would be good if only the website associated with the current tab is fetched, and the other websites of the other tabs are only fetched when one visits the relevant tab

- Device (iPhone5, iPhone6s plus, iPad 3, ?): Iphone 4s in ios 9.3.5

- Brave Version: 1.4.2

- Steps to reproduce:
    1. Open many tabs
    2. Close app and remove from background
    3. Notice how long the webpage of the current tab takes to load when one opens brave browser

- Actual Behavior
Slow loading of webpage. When one switches to another tab, one notices that the websites of the other tab has already been fetched, indicating that the webpages of all tabs are fetched simultaneously

- Expected Behavior
I would expect only the webpage of the current tab to be fetched (this results in faster rendering of the webpage and possibly less memory consumption)

- Can this issue be consistently reproduced? Yes

**Comment by Jacalz** [comment]
+1 from me, great thing to add :+1:
