### ISSUE TITLE
New install causes wrong top tiles to show up

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1196]
- Did you search for similar issues before submitting this one?
Yes
- Description:
New install causes wrong top tiles to show up
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+
- Brave Version:
1.5 (17.09.25.16)
- Steps to reproduce:
    1. Clean install 1.5 build
    2. Shows wrong top tiles upon launch
    3.

- Actual Behavior
See screenshot
- Expected Behavior
Should show proper site favicons
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/30854478-625fb7bc-a2cf-11e7-9177-fe6c13b515c9.png)

- Any related issues:

**Comment by jamesmudgett** [comment]
fixed https://github.com/brave/browser-ios/commit/9125dad84f6be5c31d66ef0e0c8a7ff89246172d

**Comment by Jacalz** [comment]
This works for me with the latest build

**Comment by srirambv** [comment]
Works fine on latest build. Closing the issue
