### ISSUE TITLE
Sweden regional ad blocking should default to on 

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#1201]
- Did you search for similar issues before submitting this one?
Yes
- Expected behavior
 I suggest that regional ad blocking should be default

**Comment by jhreis** [comment]
Any specific regions? We only auto-enable regional adblocking when we have the ability to vet that region carefully.

**Comment by Jacalz** [comment]
Sweden would be good to add as standard 🇸🇪🙂

**Comment by jhreis** [comment]
@Jacalz Have you been using the Swedish regional ad blocking for awhile? Does it seem to work reliably, and consistently?

**Comment by Jacalz** [comment]
I have been using it since about January and it has been working very good, I have not had any issues 🙂 The consistency have been good as far as I know 👍

**Comment by LaurenWags** [comment]
iPad on iOS10

![img_0114](https://user-images.githubusercontent.com/28145373/33096182-1de622fc-ced4-11e7-8a41-1ea3ea605c85.PNG)
