### ISSUE TITLE
Add more options to the tab tray action menu

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#1202]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Add more options to the tab tray action menu that makes the user experience faster, such as:
* Close all tabs (Text should be red and it should show x amounts of tabs)
* Close current tab (Text should be red) (See #1176)
* Private mode (This should say normal mode when in private mode)

- Any related issues:
#1176

**Comment by Jacalz** [comment]
This was per discussion with @jamesmudgett

**Comment by srirambv** [comment]
> Private mode (This should say normal mode when in private mode)

I feel it should not provide normal tab option. If user enables private tab only from setting then this option doesn't make sense. Only for normal tabs it should provide private tab option but not the otherway around.
