### ISSUE TITLE
Add ui support for Iphone X

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#1209]
- Did you search for similar issues before submitting this one?
Yes
- Description:
Brave should have support for Iphone X ui before the phone gets released. 
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Iphone X

- Screenshot if needed:
This is how it looks at the moment:
![namnlost](https://user-images.githubusercontent.com/25466657/31092287-2ec2bbc8-a7ae-11e7-8d29-c224da2e6f2b.jpeg)

![namnlost2](https://user-images.githubusercontent.com/25466657/31092291-31e359e8-a7ae-11e7-979e-710c350eb892.jpeg)

![namnlost3](https://user-images.githubusercontent.com/25466657/31092292-31f99d16-a7ae-11e7-9e3f-ac7730f93cec.jpeg)

**Comment by jhreis** [comment]
We will not be supporting the iPhone X.

**Comment by Jacalz** [comment]
This will be in 1.5 and it is fixed so closing

**Comment by jhreis** [comment]
Closing, if there are layout issues file a new bug ticket.

**Comment by kjozwiak** [comment]
Unfortunately the QA team doesn't own an iPhone X... I'm going to see if there's anyone under the "#testers" channel that owns an iPhone X and could verify this issue.

In the meantime, I'll test this within the simulator as well, but it would be nice to get this checked on a real iPhone X.

**Comment by petemill** [comment]
Tested on real iPhone X in 17.11.06.14 and 17.11.07.17 - Brave looks perfect now. It has the most space dedicated to content out of all the browsers - so, thanks for that!

![img_0118](https://user-images.githubusercontent.com/741836/33144270-4e6eea60-cf71-11e7-95b4-7d2c86aac821.png)
![img_0120](https://user-images.githubusercontent.com/741836/33144271-4e879eb6-cf71-11e7-9d6b-24b22c4b7c82.png)
![img_0121](https://user-images.githubusercontent.com/741836/33144272-4ea17a2a-cf71-11e7-9ae5-96e0b6bb269f.png)
