### ISSUE TITLE
Share to notes.app freezes Brave

### ISSUE THREAD

**Issue by iccub** [brave/browser-ios#1213]
- Did you search for similar issues before submitting this one?
Yes
- Description:
Can't share link to notes.app, after tapping on share to notes whole app doesn't respond to touches.
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7, iPad Air 2, both on the newest iOS, can't test on simulator as theres no notes.app
- Brave Version:
1.4.2/1.5(latest development)
- Steps to reproduce:
    1. Visit any website
    2. Tap on share action, select notes.app

- Actual Behavior
App freezes.
- Expected Behavior
Should open notes.app
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

- Website problems only: 
- did you check with Brave Shields down? 
Yes, it's the same
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 
It works on firefox iOS

**Comment by Jacalz** [comment]
See same thing here on iPad Air 2
