### ISSUE TITLE
Share page/url doesn't always work

### ISSUE THREAD

**Issue by kunalverma25** [brave/browser-ios#1216]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Go to any webpage, Tap Share btn below, Share with Whatsapp
The shared text is the title of the page, not the URL

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 8, iPhone 6

- Brave Version:
1.4.2

- Steps to reproduce:
    1.Go to any page
    2.Share URL from below
    3.Share to whatsapp

- Actual Behavior
Shared the Page Title

- Expected Behavior
Should share the URL

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
No

- did you check with Brave Shields down? 
Same

- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 
Works in FF

- Screenshot if needed:

- Any related issues:

**Comment by iccub** [comment]
Hey, my PR https://github.com/brave/browser-ios/pull/1214 should help you. It fixes all recent share extension issues.

I don't have whatsapp to verify it, can confirm though that sharing links on Telegram started to work again.

Hopefully it'll get merged for the next release.

**Comment by kunalverma25** [comment]
@iccub
Yeah that does work..
Thanks..

**Comment by iccub** [comment]
@jhreis I think it can be closed, #1214 fixed this.

**Comment by jhreis** [comment]
Closing per https://github.com/brave/browser-ios/pull/1214
