### ISSUE TITLE
Add launcher screen

### ISSUE THREAD

**Issue by iccub** [brave/browser-ios#1221]
- Did you search for similar issues before submitting this one?
Yes

- Description:
App doesn't have a launch screen. Adding it would make waiting for the app to open more pleasant. 
Simple brave logo on white background or white logo on orange background should be enough.

**Comment by srirambv** [comment]
This was removed as part of  #896 (https://github.com/brave/browser-ios/commit/ea6ce37107e9715ddfd37b96c51b59391c499a4a). Not sure if this will be added back

cc: @jamesmudgett

**Comment by jhreis** [comment]
These are actually different things. One is the first-time launch screen, and the other is the "loading" screen. 

@iccub We do want to add a launch screen. We would prefer to use a simplified version of the UI, over a logo. Given how simple our boilerplate layout is it shouldn't be too difficult to replicate in a xib file. Thanks for creating a ticket for this.
