### ISSUE TITLE
Update ISSUE_TEMPATE to match laptop

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1227]
- Did you search for similar issues before submitting this one?

- Description:

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Actual Behavior

- Expected Behavior

- Is this an issue with Beta build?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by Jacalz** [comment]
++ Thanks får opening it 👍
