### ISSUE TITLE
Most recent page navigated to is not saved

### ISSUE THREAD

**Issue by zapturk** [brave/browser-ios#1231]
- Did you search for similar issues before submitting this one?
   Yes

### Description:
When reopening Brave after closing it the most recent page navigated to is not saved.

### Steps to Reproduce

  1. On a tab with a website open click on a link to another page (picture 1 in pictures below i clicked on sun)
  2. Let that page load (picture 2)
  3. double tap home and close Brave (picture 3 and 4)
  4. Reopen Brave and it will load the original page (picture 5)

**Actual result:**
When I open Brave I was back on the Saturn wiki page.
**Expected result:**
When I open Brave I would be on the last page I visited

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time. 

### Brave Version:
1.4.2 (17.09.08.16)

### Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6

### Is this an issue in the currently released version?
yes

### Is this an issue with Beta build?
Not sure

### Additional Information
If you press home 1 time, then press home 2 times to close it, then close it, and finally reopen Brave the page will be your last one you were on.
 
![image](https://user-images.githubusercontent.com/6806789/31514064-16184f0c-af56-11e7-9eef-1d8235215118.png)
![image](https://user-images.githubusercontent.com/6806789/31514075-1d9c4300-af56-11e7-903e-6707af580db5.png)
![image](https://user-images.githubusercontent.com/6806789/31514086-2411f860-af56-11e7-9fe6-5431606d5567.png)
![image](https://user-images.githubusercontent.com/6806789/31514093-28872104-af56-11e7-9f7b-3348bb937925.png)
![image](https://user-images.githubusercontent.com/6806789/31514100-2c23c916-af56-11e7-963c-f4bd745e1a3d.png)

**Comment by srirambv** [comment]
Cant reproduce on the release build. See attached recording
[1231.zip](https://github.com/brave/browser-ios/files/1386894/1231.zip)

**Comment by zapturk** [comment]
Here is video of the bug.
[1231Bug.zip](https://github.com/brave/browser-ios/files/1387538/1231Bug.zip)

**Comment by zapturk** [comment]
Should I uninstall and reinstall to see if this still occurs?

**Comment by srirambv** [comment]
cc: @jhreis
