### ISSUE TITLE
Always ask for Pin when enabling Browser Lock for the first time (and after fresh install)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1232]
### Description:
 Enabling browser pin switch doesnt ask pin until app restart

### Steps to Reproduce

Scenario 1
  1. Clean install beta build
  2. Enable browser pin, doesnt ask for setting up pin
  3. Remove app from memory, relaunch, asks for pin
  4. Entering pin sets the pin but doesnt ask for confirmation
 
Scenario 2
  1. Clean install beta build
  2. Enable browser pin, doesnt ask for setting up pin
  3. Tap on set pin
  4. Asks to enter current pin which is not set
  5. Entering random pin shows set new pin page

### Brave Version:
1.5(17.09.29.18)
### Additional Information

#1171 #1166

**Comment by jamesmudgett** [comment]
To give more clarity here, your pin is stored in the iCloud keychain for the brave app, so it’s persisted even when you delete/reinstall the app. If the keychain contains your pin we don’t re-ask when you enable Browser Lock. Only time we ask for new pin is on first use and when changing pin.
