### ISSUE TITLE
Copy webpage URL copies the URL into the clipboard twice

### ISSUE THREAD

**Issue by jessepollak** [brave/browser-ios#1239]
### Description:

When clicking the Copy button from the Share panel, the URL gets copied into the clipboard twice. 

### Steps to Reproduce

  1. Visit a web page
  2. Tap the share panel button on the bottom action bar
  3. Tap the Copy button

**Actual result:**

URL is copied into the clipboard twice (like https://google.comhttps://google.com). 

**Expected result:**

URL is copied into the clipboard correctly. 

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Brave Version:

1.4.2

### Device (iPhone5, iPhone6s plus, iPad 3, ?):

iPhone 7+

### Is this an issue in the currently released version?

Yes

### Website problems only: 
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Comment by srirambv** [comment]
I cant reproduce this on iPhone 7+.  Also where are you pasting the copied URL which shows duplicates? Is it on brave or some other app?

Could you provide the complete version number 1.4.2(??.??.??.??) and the iOS details

**Comment by jessepollak** [comment]
It's Version 1.4.2 (17.09.08.16).

The copied URL shows as duplicate whenever I paste it in a variety of places:

* The Brave URL bar
* An iMessage text field
* A new Gmail email

It doesn't show up when I paste it in:

* The in-page search bar in Brave at google.com

**Comment by srirambv** [comment]
cc: @jamesmudgett @jhreis

**Comment by jamesmudgett** [comment]
This looks to be an iOS 11 bug, same thing happens in Apple maps when copying an address. We don’t have an ability to change the output as we only pass in a single IRL.
