### ISSUE TITLE
History shows wrong favicon, or wrong title

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#124]
I saw this in my history. I notice that first I was in youtube (which didn't get a favicon in the history), then went to bing, and bing got assigned the favicon from youtube:

<img width="205" alt="screenshot 2016-02-09 12 32 52" src="https://cloud.githubusercontent.com/assets/5495083/12924683/4a577630-cf29-11e5-9873-bfdc6f5bebc4.png">

**Comment by garvankeeley** [comment]
@ElissaBeth another one to look out for, and see if you come across reliable steps to repro

**Comment by garvankeeley** [comment]
from @bradleyrichter:
![slack_for_ios_upload_720](https://cloud.githubusercontent.com/assets/5495083/13131160/a9beac9e-d5b7-11e5-8584-7f5834c7fac0.jpg)

![slack_for_ios_upload_720-1](https://cloud.githubusercontent.com/assets/5495083/13131162/abcfd418-d5b7-11e5-9ccc-bf4963d54249.jpg)

**Comment by garvankeeley** [comment]
@bradleyrichter do your recall what loads when you tap these? The page according to the title, or the url displayed?

**Comment by bradleyrichter** [comment]
It tries to load the URL shown. And then fails to load. The current page remains and is reloaded if using pull to reload.

**Comment by garvankeeley** [comment]
fixed by 6c291cd07979743d51b14ba4c3fb6902119d20a7

**Comment by bbondy** [comment]
\o/

**Comment by garvankeeley** [comment]
This is much better in 1.2.2, but still happening. I am working on catching additional edge cases.

The issues on this bug:
• UIWebView reports load completion incorrectly, and can report load completion before the page can be queried for document.title. Sites that use history push navigation like thestar.com will exhibit this. Unfortunately this behaviour only happens once in every 3-4 loads. Internal to UIWebView, there is a async behaviour that is happening out-of-sequence

• Also in the above case, UIWebView's request.URL property will be out-of-sync with the js window.location, with the latter being more accurate. This is bad, as code will preferably use the non-JS location, JS calls on the webview are best avoided due to performance and stability problems. Calling the JS window.location is a solution but must be done very selectively.

• Finally, the underlying DB system has lack of validation that the reported favicon and page title are for the correct page. It is possible that a favicon for a page with URL1 is async returned while the page is now moved on to URL2. Favicons are assumed to be for the currently page URL, in the UIWebView case,with all its unreliable notification states, this is not a reliable assumption.

**Comment by garvankeeley** [comment]
With the latest round of fixes, I am no longer seeing this. Once again I will try closing.
