### ISSUE TITLE
Empty tabs lost after relaunching app

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1241]
### Description:
Empty tabs lost after relaunching app

### Steps to Reproduce

  1. Install the latest beta
  2. Open 6-7 empty tabs
  3. Remove the app from memory
  4. Wait for 5-8 secs before launching app again, all tabs are lost
  5 Visit couple of sites in 2 different tabs, open 3-4 new tabs
  6. Remove the app from memory
  7. Wait for 5-8 secs before launching app again, new tabs are lost but retains the tabs which had site vited

**Actual result:**
Empty tabs lost after relaunching app

**Expected result:**
Should retain all tabs when app is removed from memory

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version:
1.5(17.10.13.15)
### Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad & iPhone (iOS11 & iOS 10)

### Is this an issue in the currently released version?
No
### Is this an issue with Beta build?
Yes
### Website problems only: N/A
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Comment by jhreis** [comment]
I understand this behavior is not intentional nor conventional. But it this behavior useful? I personally hate opening my tab tray and seeing _any_ empty tabs in there. Any real reason to retain these?

**Comment by jhreis** [comment]
Confirmed with @jamesmudgett. We are on the same page, this behavior is fine. We are going to move ahead with current behavior.
