### ISSUE TITLE
Added Share Option for Images

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#1244]
We would like to add an option to Share images. This would add an option to the long-press image menu (see photo below), giving the user to "Share Image".

![iScreenshot of current image options](https://user-images.githubusercontent.com/2781690/31689343-1ffeb41a-b35d-11e7-8e1b-3ed62bd0d04c.jpg)

**Comment by longoria** [comment]
@jhreis Got it.

**Comment by Jacalz** [comment]
Closing and assigning to 1.5 since merged

**Comment by srirambv** [comment]
Functionality still doesn't work on iOS 10. Clicking Share image doesn't do any thing

**Comment by jamesmudgett** [comment]
@srirambv can we get a new issue to track bug in iOS 10 instead of using this ticket?
