### ISSUE TITLE
Click to call doesn't switch to phone app

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1245]
### Description:

Click to call doesn't switch to phone app
### Steps to Reproduce

  1. Open any site with a contact number
  2. Tap on the phone number
  3. Select call in popup menu, doesnt switch to phone app

**Actual result:**

Click to call doesn't switch to phone app
**Expected result:**
Should dial the number
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version:
1.4.2(17.09.08.16)
### Device (iPhone5, iPhone6s plus, iPad 3, ?):
All
### Is this an issue in the currently released version?
Yes

### Additional Information

https://community.brave.com/t/click-to-call-link-dont-work/8405

**Comment by srirambv** [comment]
Issue not reproducible on iOS 11. Second tap on the call alert switches to the phone app.

**Comment by LaurenWags** [comment]
Not reproducible on iOS10 by myself or @kjozwiak . Same result as https://github.com/brave/browser-ios/issues/1245#issuecomment-345822899, second tab on the call alert switches to the phone app.
