### ISSUE TITLE
Issue with the messaging functionality on Facebook.com

### ISSUE THREAD

**Issue by ElissaBeth** [brave/browser-ios#125]
Messaging functionality works to send initial message. However it breaks once the user is in a thread. To replicate - go to the inbox and send a message (inbox style messaging not chat style messaging.) The black bar on the bottom prevents the user from being able to type into the messaging bar on the bottom of the Facebook page.

**Comment by ElissaBeth** [comment]
Actually, there are two variations where the user can't send a message. both are attached as screenshots. 
![cant_send_message_2 copy](https://cloud.githubusercontent.com/assets/2620022/12937295/2968520e-cf5c-11e5-9825-695260f25154.png)
![can t_send_message_1 copy](https://cloud.githubusercontent.com/assets/2620022/12937303/3a8de3d2-cf5c-11e5-92e6-1fed6d4e320f.png)

**Comment by garvankeeley** [comment]
Thanks for the report, what happens with brave shields down? 
Do you have Puffin/Dolphin/Mercury/Opera/Maxthon/Adblock (any one will do) to try it in?

**Comment by garvankeeley** [comment]
Dolphin browser does the same thing.

**Comment by garvankeeley** [comment]
I have a site specific workaround. Not thrilled with it, I would prefer a more general solution so I'll see what I can come up with.

**Comment by garvankeeley** [comment]
@ElissaBeth please try in the build just released.

**Comment by garvankeeley** [comment]
@ElissaBeth confirming: is this working for you?

**Comment by garvankeeley** [comment]
@bbondy this might be the same bug again https://twitter.com/brianbondy/status/704010187800223744
@ElissaBeth can you try again and see?
