### ISSUE TITLE
Clear private data => unable to clear data from disk error

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#126]
From a friend:

STR:
open the Brave app
once opened, tap on the "History" icon in the top left hand corner
select the setting "gear" icon
select "Clear Private Data"
select "Clear Private Data" button
You'll receive the following error message every single time: (see screenshot)

Error clearing data
Unable to fully clear data from disk.

![img_0569](https://cloud.githubusercontent.com/assets/831718/12938117/89bd5cd2-cf7d-11e5-9440-aca354cd8809.jpg)

**Comment by garvankeeley** [comment]
Interesting, the app's Library/Caches/Snapshots dir can't be deleted. Will see what I can do about that.
