### ISSUE TITLE
Open All option for bookmarks displays misleading number in parenthesis

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1263]
### Description:
When using long press on a bookmark folder to open all bookmarks in that folder, the number displayed in () is misleading, it takes into account both bookmarks and sub folders.  

### Steps to Reproduce

  1. Have a bookmark folder with both bookmarks and at least one sub folder in it.
  2. Long press on bookmark folder to get the 'Open all' option.
  3. 

**Actual result:**
Number displayed in parenthesis takes into account both bookmarks and sub folder(s), making it misleading.

**Expected result:**
Number displayed in () should only show the number of bookmarks to be opened.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version:
1.5 (17.10.24.14)

### Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad

### Is this an issue in the currently released version?
no

### Website problems only: 
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Comment by LaurenWags** [comment]
found while testing https://github.com/brave/browser-ios/issues/1187

**Comment by srirambv** [comment]
Thinks its same as  #1237.
