### ISSUE TITLE
Turn off launcher screen when browser lock is enabled

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#1272]
### Description:

When browser lock is enabled the launcher screen shows up like the app loads but then the pin code lock shows wich gives an unpleasant experience when having the browser lock on.
### Steps to Reproduce

  1. Enable browser lock
  2. Restart Brave (See how launcher screen shows up for a second and then gets all blurry because of the browser lock)

**Actual result:**

Launcher screen shown
**Expected result:**
Launcher screen should not be shown
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version:
1.5 (17.10.26.08)
### Device (iPhone5, iPhone6s plus, iPad 3, ?):
All
### Is this an issue in the currently released version?
No
### Is this an issue with Beta build?
Yes

### Additional Information

cc @jamesmudgett

**Comment by iccub** [comment]
This is not technically possible, launch screen is loaded before the app loads, so you can't check for app's state.

The same goes for private-only browsing option.

**Comment by Jacalz** [comment]
Aha, well let’s mark this as wontfix then 🙂

**Comment by iccub** [comment]
It's up to you. If the user experience is really bad we can just throw away the current launch screen and use something simple like Brave logo on white/orange background.

But maybe it's not that bad, on my iP7 Brave loads under 1sec, on simulators though, it takes few seconds, so the impression is different(at least for me)

**Comment by Jacalz** [comment]
I have an iphone 5s so it is quite slow but let us see what @jamesmudgett has to say about it :)

**Comment by jhreis** [comment]
Despite current behavior being non-optimal. I personally think it is our best option. Will let James chime in if he wants.
