### ISSUE TITLE
setting "browser lock" and not entering a pin will lock users out of Brave

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-ios#1273]
### Description:

When a user enables "Browser Lock" and goes back into the settings via the "Settings" button without setting a PIN, they'll be locked out of Brave as it's going to ask you for a PIN but one hasn't been set. If the phone as touch ID enabled, they'll be able to unlock the phone, however users without the touch ID will get locked out of the browser.

### Steps to Reproduce

  1. launch Brave and go into "Settings"
  2. enable "Browser Lock" and you'll be prompted to enter a PIN
  3. go back into settings via the "Settings" button without setting a PIN

You'll notice you'll be prompted for PIN's, however the user never set a PIN.

**Actual result:**

You'll be prompted for a PIN code whenever launching Brave but the user never set one, which basically locks them out.

![pinissueios](https://user-images.githubusercontent.com/2602313/32073633-b18270e4-ba64-11e7-87fc-5e0d156a1331.gif)

**Expected result:**

If a user enabled PIN's via the "Browser Lock" toggle and doesn't set a PIN, going back into settings should disable "Browser Lock".

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% reproducible using the above STR.

### Brave Version:

Using `v1.5 (17.10.24.17)`

### Device (iPhone5, iPhone6s plus, iPad 3, ?):
* iPhone 6s+ using iOS 10.3.1 - Reproduced (but recoverable with Touch ID)
* iPhone 5 & iPhone 5s using 10.3.1 - Reproduced

### Is this an issue in the currently released version?

Nope, the PIN feature is being introduced in `v1.5` and not available under `v1.4.2 (17.09.08.16)`

### Is this an issue with Beta build?

Yes, currently only on the BETA.

**Comment by kjozwiak** [comment]
@jhreis I put this into the `v1.5.1` milestone. However, if we're still have fixes that are going into the `1.5` milestone, this should probably tag along and get bumped into `1.5`. Users will basically shoot themselves in the foot if they don't set a PIN when enabling "Browser Lock" which is pretty bad.

**Comment by jhreis** [comment]
Moving this into 1.5. This is pretty bad.
