### ISSUE TITLE
Launching app needs smooth transition

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1274]
### Description:
Launching app needs smooth transition

### Steps to Reproduce
  1. Clean install 1.5(17.10.26.08)
  2. Launch the app
  3. Tool bar has weird transition that looks bad

**Actual result:**
[Launchapp.zip](https://github.com/brave/browser-ios/files/1421775/Launchapp.zip)

**Expected result:**
Should have proper transition during launch

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version:
1.5(17.10.26.08)

### Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone and iPad 

### Is this an issue in the currently released version?
No

**Comment by jhreis** [comment]
Fixed per: 34c3bce45f181fa330f6be39d9db38f5f81c2dec
