### ISSUE TITLE
Ads leaking through on 1.5 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1275]
### Description:
Ads leaking through on 1.5 

### Steps to Reproduce
   1. Install 1.5(17.10.26.08)
   2. Visit slashdot.org
   3. Ads shown on page

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/32103019-aa709d5a-bb16-11e7-809f-e5c126c613a7.png)
![image](https://user-images.githubusercontent.com/17010094/32103026-af3a79b4-bb16-11e7-862c-2a183caa0056.png)

**Expected result:**
Ads should be blocked

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version:
1.5(17.10.26.08)

### Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad and iPhone

### Is this an issue in the currently released version?
No

**Comment by srirambv** [comment]
Issue started with  1.5(17.10.26.08). Verified from build  1.5(17.10.12.08) onward, no leakage of ads.

**Comment by kjozwiak** [comment]
I've been seeing the same thing over the weekend on several different websites as well:

![image uploaded from ios](https://user-images.githubusercontent.com/2602313/32177425-b3a123da-bd60-11e7-9f2b-a2484de49894.png)

**Comment by jhreis** [comment]
Fixed per: 0e7d9aa68824b84429917ac5782151662952c7fc
