### ISSUE TITLE
target=_blank links open in same tab

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#128]
If you go to brianbondy.com then click on the bug (bugzilla) icon on the top right, most browsers open this in a new tab.  We open it in the same tab. 

I'd prefer if this wasn't fixed until we have better >9 tab handling though.

**Comment by garvankeeley** [comment]
Good point, without >9 tab handling, this would be a problem

**Comment by garvankeeley** [comment]
Added mentored bug tag if a contributor wants to start on this. There is lots of info on the web on injecting JS to detect these links so the web view can handle them. We can have a debug pref to turn it on/off until >9 tab handling lands

**Comment by garvankeeley** [comment]
This should work ok:
http://www.icab.de/blog/2009/08/05/webkit-on-the-iphone-part-2/

JS injected that modified _blank link targets to have custom href that can be filtered by the UIWebView shouldStartLoadWithRequest.
I am not convinced it will catch all circumstances, but I think it will cover most common cases.

**Comment by garvankeeley** [comment]
fixed a68b4feeb45576bef9cec7dfb710d7841964733a
