### ISSUE TITLE
Saving an image causes browser to crash

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1282]
### Description:
Saving an image causes browser to crash

### Steps to Reproduce
  1. Install 1.5 (17.10.30.12)
  2. Open any page with image
  3. Long press on image, select save image, browser crashes

**Actual result:**
[save_image_crash.zip](https://github.com/brave/browser-ios/files/1431703/save_image_crash.zip)

**Expected result:**
Should save the image and not crash

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version:
1.5(17.10.30.12)

### Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad (iOS 11)

### Is this an issue in the currently released version?
No

**Comment by kjozwiak** [comment]
@LaurenWags and myself couldn't reproduce the issue under iOS10.. However I also managed to reproduce in my iPad Mini 4 using iOS 11.0 with `1.5 (17.11.03.09)`. Seems iOS11 specific.

**Comment by Jacalz** [comment]
I can reproduce on `1.5 (17.11.03.09)` using iPad Air 2 with iOS 11.1
