### ISSUE TITLE
Open link in a new tab causes empty tabs bar 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1284]
### Description:
Open link in a new tab causes empty tabs bar 

### Steps to Reproduce

  1. Install 1.5 (17.10.30.12)
  2. Open https://github.com/brave/browser-ios/issues/1279 
  3. Scroll down so that the tabs bar and URL bar is hidden
  4. Long press on any link and open in a new tab
  5. Links open in a new tab but the tabs bar is hidden with white border 

**Actual result:**
[tabsbar.zip](https://github.com/brave/browser-ios/files/1432361/tabsbar.zip)
![image](https://user-images.githubusercontent.com/17010094/32249580-79589010-be81-11e7-90f7-cb364de6dfcf.png)

**Expected result:**
Should show the tabs bar when a link is opened in a new tab

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version:
1.5 (17.10.30.12)

### Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad (iOS 11), iPhone 7+ (iOS 10)

### Is this an issue in the currently released version?
No

### Additional Information
Only happens when you have a single tab and try to open a link in new tab

**Comment by kjozwiak** [comment]
I'm still seeing the same behaviour with my iPhone 6s+ iOS 10.... When opening tabs via `open in a new tab` using the long press gesture, sometimes the URL bar doesn't appear when a new tab is created.

Example: https://youtu.be/I-nX_tG_G6M

You'll notice from the above example that on the initial `open in a new tab` correctly displays the URL bar but on subsequent tries it doesn't. Looking through the above comments, the URL bar should be displayed every time.. 

@srirambv and @LaurenWags, are you guys seeing this as well?

**Comment by kjozwiak** [comment]
@srirambv mentioned he was seeing the same behaviour... After talking to @jhreis, I believe this is still broken and the URL bar should be appearing anytime a user opens a tab via `open in a new tab` using the long press gesture....

@jhreis, if that's not the case, please move this back into the 1.5.1 roadmap and apply the `QA Checked` labels that have been removed.

**Comment by srirambv** [comment]
Seeing this only on private tabs

**Comment by LaurenWags** [comment]
appears resolved on iOS10 iPad for both normal and private tabs
