### ISSUE TITLE
URL doesn't update when navigating back on YouTube

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1295]
### Description:

URL doesn't update when navigating back on YouTube

### Steps to Reproduce

  1. Clean install 1.5 (17.11.03.09)
  2. Visit YouTube and open any video, ensure URL shows has `/watch?v=<videoID>`
  3. Navigate back using the back button, URL doesn't update still remains on the video opened from step 2

**Actual result:**

[YouTube URL.zip](https://github.com/brave/browser-ios/files/1445798/YouTube.URL.zip)

**Expected result:**
URL should update when navigating back 

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**

1.5(17.11.03.09)

**Device details:**

iPad (iOS 11)

**Website problems only:** Yes
- did you check with Brave Shields down?
Yes
- did you check in Puffin/Dolphin (UIWebView-based browsers)? 
Yes, URL updates correctly on Dolphin
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Yes, URL updates correctly on Firefox

### Additional Information

Existing issue on the released version as well. Same problem on iPhone as well. Need to verify on iOS 10
cc: @LaurenWags @kjozwiak

**Comment by kjozwiak** [comment]
This bug also affects the History. When the URL isn't being updated, new items are not being placed into History. A user could watch 10 different videos and they'll only get the initial entry from the first video in History.
