### ISSUE TITLE
Share icon changes to password manager icon when Search in Page option is selected

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1297]
### Description:
Share icon changes to key icon when Search in Page option is selected

### Steps to Reproduce
  1. Open any page
  2. Tap on the share icon
  3. Select `Search in page`, share button changes to key, tapping opens up empty share menu

**Actual result:**
[share_menu.zip](https://github.com/brave/browser-ios/files/1450082/share_menu.zip)

**Expected result:**
Share menu icon should not change 

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easily reproduced 

**Brave Version:**

1.4.2 (17.09.08.16)

**Device details:**

iPad (iOS 11.1)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
iPad specific, as the search option hides the snackbar on iPhone so literally not possible to check 
@LaurenWags to verify on iPad with iOS 10

**Comment by srirambv** [comment]
Icon changes to which ever password manager is set in settings.

**Comment by LaurenWags** [comment]
does not occur on iPad using iOS 10 for me.
![img_0103](https://user-images.githubusercontent.com/28145373/32554650-826e9446-c468-11e7-9868-874f8bcd3ef1.PNG)

**Comment by iccub** [comment]
Can reproduce this bug only on websites with login forms.
So it doesn't occur on mobile.twitter.com, but on mobile.twitter.com/login issue can be reproduced.

**Comment by kjozwiak** [comment]
Verified the above fix using the following websites under both regular browsing and private browsing with `1.5.2 (17.12.07.15)` using iPad Mini 4 iOS 11:

* mobile.twitter.com/login - PASSED
* facebook.com - PASSED
* reddit.com - PASSED 
* linkedin.com - PASSED
