### ISSUE TITLE
Bookmarks only load when switched to the tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1299]
### Description:
Bookmarks only load when switched to the tab

### Steps to Reproduce
  1. Add multiple bookmarks inside a folder 
  2. Long press on bookmark folder, tap on open all bookmarks
  3. Bookmarks open in a different tab but doesn't load, only loads the page when you switch to the tab

**Actual result:**
[bookmaksload.zip](https://github.com/brave/browser-ios/files/1450573/bookmaksload.zip)

**Expected result:**
Should load the bookmarks immediately after opening in tabs

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easily reproduced

**Brave Version:**

1.5 (17.11.06.14)

**Device details:**

iPad/iPhone (iOS 11)

**Website problems only:** N/A
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin (UIWebView-based browsers)? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

**Comment by jamesmudgett** [comment]
After looking through this I think it would make sense that we maintain same logic as other tabs, only when attempting to load a single bookmark should we load that tab. Otherwise, we could cause issues loading potentially large folders and all bookmarks inside.

**Comment by jamesmudgett** [comment]
Will add logic to load if folder contains a single bookmark.
