### ISSUE TITLE
Module compiled with Swift 4.0.2 cannot be imported in Swift 3.1:

### ISSUE THREAD

**Issue by salamsoliman** [brave/browser-ios#1300]
/Users/tayler/Documents/source code/browser-ios-development/Shared/Extensions/KeychainWrapperExtensions.swift:6:8: Module compiled with Swift 4.0.2 cannot be imported in Swift 3.1: /Users/sulayman/Documents/source code/browser-ios-development/Carthage/Build/iOS/SwiftKeychainWrapper.framework/Modules/SwiftKeychainWrapper.swiftmodule/x86_64.swiftmodule

when I download the code zip file and open it in xcode ,it showed this error.

**Comment by iccub** [comment]
Just downloaded fresh .zip of development branch and it works for me(Xcode 9).
Which Xcode version are you using?

**Comment by Jacalz** [comment]
I believe that this is due to not running the setup script, you need to change your directory to browser-iOS/Brave and run ./setup.sh

**Comment by iccub** [comment]
Hi @salamsoliman, @jhreis fixed some compilation issues today(development branch), and everything should work for now.

Closing the issue but feel free to comment if you have any troubles.
