### ISSUE TITLE
Some visited links are not shown in history 

### ISSUE THREAD

**Issue by naira-cliqz** [brave/browser-ios#1307]
### Steps to Reproduce

  1. Login in Twitter
  2. Tap on any twit
  3. go back
 4. check the history

**Actual result:**
You'll see only twitter home page in the history, and cannot go back to the previous visited twit
**Expected result:**
To have all visited links in history and  be able to navigate back and forth. (Safari shows all visits.)
**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**
1.5.
It was working before

**Device details:**

**Website problems only:**
- did you check with Brave Shields down? - No

- did you check in Puffin/Dolphin (UIWebView-based browsers)? - No

- did you check in Safari/Firefox (WkWebView-based browsers)?  - Yes

**Comment by iccub** [comment]
Hi @naira-cliqz, thanks for your report, we fixed the issue, fix will go live in Brave 1.5.1 or 1.5.2.
