### ISSUE TITLE
Share image doesn't work

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1315]
### Description:
Share image doesn't work

### Steps to Reproduce

  1. Install 1.5
  2. Open any page with image
  3. Long press on image, Share image, nothing happens

**Actual result:**
Share image doesn't work

**Expected result:**
Share menu should open

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy

**Brave Version:**

1.5 (17.11.07.17)

**Device details:**

iPhone 7+ (iOS 10)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Works fine on iOS 11
#1244

**Comment by iccub** [comment]
Cannot reproduce on simulators 10.0 and 10.3.1

**Comment by LaurenWags** [comment]
Could not reproduce on iOS10 iPad or iPhone both using version 1.6.2 (18.05.29.10)
