### ISSUE TITLE
URL not visible when a link is opened in a new private tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1319]
### Description:
URL not visible when a link is opened in a new private tab

### Steps to Reproduce
  1. Install 1.5.1 
  2. Visit any page and long press on a link and open in a private tab
  3. Link opens but URL is not visible
  4. Clicking on the URL bar shows the link again and becomes visible when clicked outside of URL

**Actual result:**
[private_tab_url.zip](https://github.com/brave/browser-ios/files/1483044/private_tab_url.zip)

**Expected result:**
Should show the URL 

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easily

**Brave Version:**
1.5.1 (17.11.17.10), Not reproducible on 1.5(17.11.07.10)

**Device details:**
iPhone 7+ (iOS 11)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @kjozwiak @LaurenWags to verify on iOS 10

**Comment by LaurenWags** [comment]
Could not reproduce using iOS10 on iPad.

**Comment by kjozwiak** [comment]
Couldn't reproduce the issue with iOS10 on the iPhone 6s+ using `1.5 (17.11.17.10)`. However, I couldn't reproduce this under iOS11 using an iPad Mini 4....

@srirambv are you seeing this on an iPad as well? Or just the iPhone?

**Comment by srirambv** [comment]
Only on iPhone with iOS 11

**Comment by iccub** [comment]
Can reproduce but only when url bar is hidden, website scrolled down a bit. 
iOS11, can't repro on iOS 10 and 9 simulators.

**Comment by srirambv** [comment]
@iccub  still happens when url bar is visible in normal tabs. Here's the screen record of the issue
[1319.zip](https://github.com/brave/browser-ios/files/1501995/1319.zip)
