### ISSUE TITLE
Settings items should look clickable

### ISSUE THREAD

**Issue by iccub** [brave/browser-ios#1327]
### Description:

Three buttons in settings: 'Report a bug', 'Privacy policy', 'Terms of use' don't look like they are actionable. Look at Apple's settings screen on the right. Actionable items have disclosure indicator or use global tint color to show that they can be tapped.
Cells without any of those looks like a regular label.

Report a bug should be colored, as it open a new tab in browser.
Privacy policy and terms of use should have disclosure indicator, they use push navigation to show next page.

<img width="567" alt="zrzut ekranu 2017-11-20 o 17 57 54" src="https://user-images.githubusercontent.com/6950387/33030725-5ecc5bf0-ce1c-11e7-89b9-fc3676bfbd67.png">

### Steps to Reproduce

  1. Open settings

**Actual result:**

Cells don't look actionable.
**Expected result:**
Cells should look actionable.
**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**

1.5 (17.11.07.17)
**Device details:**

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Liunkae** [comment]
PR: #1400
