### ISSUE TITLE
Clear private data should require confirmation before clear

### ISSUE THREAD

**Issue by iccub** [brave/browser-ios#1328]
### Description:

Clear private data setting is a destructive action. It should warn user that doing that will erase all his history etc. Currently you can missclick it and all your history is gone
### Steps to Reproduce

  1. Open Settings -> Clear private data
  2. Tap on clear private data button

**Actual result:**

Clears data without any confirmation

**Expected result:**
Should warn user before destructive action

**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**

1.5 (17.11.07.17)
**Device details:**

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Liunkae** [comment]
PR: #1401
