### ISSUE TITLE
Adding iOS Data for Retention 

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#1330]
- On the app's first launch store the date of the previous Monday. If first launch happens on Wednesday the 15th of March, we need to store the installation date as 2017-03-13 (minimizes targeting granularity)
- This date should be sent on _all_ pings as a parameter called `woi=2017-03-13` (week of installation)

Look at `BraveApp:updateDauStat` for where this should be implemented.

**Comment by kjozwiak** [comment]
@jhreis is there anything QA can do here in terms of testing? If not, lets mark this as `QA/No-QA required`.
