### ISSUE TITLE
sharing links via "long press" shares the page that's currently opened and not the link that was selected

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-ios#1335]
### Description:

Sharing links on from a page via the long press action shares the current website and not the link that was selected.

### Steps to Reproduce

  1. install `1.5.1 (17.11.20.17)` and ensure you have Pocket installed
  2. visit cnn.com and long press any article
  3. You'll notice the specific link of the article being displayed including several other options
  4. Select "Share Link" and tap on "Pocket" (or any other app)

You'll notice that the link that was shared was the website that's currently opened and NOT the link that was selected/shared.

**Actual result:**

The correct link should be shared when long pressing links on websites rather than sharing the page that's currently opened.

* https://youtu.be/why4yu6gTB0

You'll notice in the above example that taping on an article on CNN and ZeroHedge added `cnn.com` and `zerohedge.com` rather than the specific articles that were being shared.

**Expected result:**

The specific article should be added rather then the page that's currently opened.

**Reproduces how often:** [Easily reproduced/Intermittent issue]

100% reproducible using the above STR.

**Brave Version:**

Using `1.5.1 (17.11.20.17)`.

**Device details:**

* iPhone 6s+ using iOS 10.3.3 - Reproduced
* iPad Mini 4 using iOS 11 - Reproduced

**Comment by LaurenWags** [comment]
Reproduced using iPad on iOS10

**Comment by srirambv** [comment]
Reproduced on iPhone 7(iOS 11)
