### ISSUE TITLE
Opening new tab hides tab controls

### ISSUE THREAD

**Issue by indutny** [brave/browser-ios#134]
When opening new empty tab, no tab controls are visible. It is impossible to close it or to get back to other tabs.

**Comment by garvankeeley** [comment]
Thanks for the report, we have had this comment a few times now, we should fix the UI here. 

It seemed wierd to have all the toolbar buttons disabled except for the tabs button -which someone just used to create a tab- but users are saying it is wierder to hide the tabs button, they may want to switch back a tab before deciding what page to go to next on the newly created tab.

**Comment by indutny** [comment]
Yeah, I spent about 2 minutes trying to figure out what to do next :)

Thank you for a prompt reply!

**Comment by indutny** [comment]
Fantastic!
