### ISSUE TITLE
Wrong order of action sheet actions upon long press on image.

### ISSUE THREAD

**Issue by iccub** [brave/browser-ios#1342]
### Description:

After you long press on image link, image related actions are at the top and navigation actions(new tab, new private tab) are in the middle.

Navigation actions should be always at the top. They are on both Safari and Firefox
### Steps to Reproduce

  1. Open https://en.m.wikipedia.org/wiki/Sea_mink
  2. Scroll down a bit and long press on image of this animal.

**Actual result:**

Actions are in order(top to bottom):
- Save image
- Copy image
- Share image
- New tab
- New private tab
**Expected result:**
- New tab
- New private tab
- Save image
- Copy image
- Share image
**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy
**Brave Version:**

1.5(17.11.07.17)
**Device details:**

iPhone 7
**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 
Order is good on Safari and Firefox

### Additional Information

<img width="492" alt="zrzut ekranu 2017-11-22 o 17 35 13" src="https://user-images.githubusercontent.com/6950387/33138762-92a183a2-cfab-11e7-9832-b1ff8430f1ec.png">

**Comment by jamesmudgett** [comment]
@iccub this was done intentionally
