### ISSUE TITLE
UX for bookmarking is poor

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#137]
Should be able to add a bookmark without opening the bookmarks panel.
https://twitter.com/viviancromwell/status/701139325929394176

Currently you have to click a bookmark-like button to open the panel, then click a button to bookmark.

The panel is also a bit confusing as is when it opens, it's hard to figure out how to close it. 

As a user I want to add a bookmark for later but don't want to see my other bookmarks, there's no need for the panel at the time of bookmarking.

**Comment by garvankeeley** [comment]
I agree that on the iPad there isn't enough visual indication as to the panel close button. Safari makes their panel open/close button standout by inverting it when the panel is open.

**Comment by seeam** [comment]
@bbondy, I faced the same problem and I was referring this kind of problem on my tweet. I also think settings button should not be hide inside bookmarks icon. Also giving a feedback while a site is bookmarked will be a nice to have feature. At first few times, while I try to close panel (as I wasn't sure how to close)  I have clicked on add bookmark icon accidentally. And later I discovered that I have bookmarked those page. Also may be there is no way to search for bookmarks and history.

**Comment by garvankeeley** [comment]
We are closer to Safari style in terms of bookmarking UI than Fx iOS style. We should look closer then at Safari to see how they handle this.

**Comment by seeam** [comment]
@garvankeeley I forget to mention, I'm on my iPad. Safari doesn't have any bookmark button on nav bar but it's inside share icon. But it also shows a confirmation tab. Safari also have easy to differentiate close and open panel switch and most importantly when the panel is opened, the other parts of the page is hidden. It also allows search bar for bookmarks.

**Comment by garvankeeley** [comment]
Agreed, the close/open on Safari is much clearer, I'll file that seperately

**Comment by bradleyrichter** [comment]
FX has only flat bookmarks and this seems frustrating/limiting but it is efficient, although takes up toolbar space.

Safari has far too many clicks to make a bookmark but you have hierarchy and organization.

@seeam and others, what do you think about this middle-ground approach that allows for single-tap +access to organized bookmarking? (see attached spec images)

Regarding showing an indicator that the page is already bookmarked, we will add this in 1.2 if possible. Planned but needs a new button state with custom code.

![screen shot 2016-02-25 at 4 06 04 pm](https://cloud.githubusercontent.com/assets/13509546/13338944/f0dc27fa-dbd9-11e5-880f-ed35c2aea9f5.png)


![screen shot 2016-02-25 at 4 06 31 pm](https://cloud.githubusercontent.com/assets/13509546/13338957/0859953e-dbda-11e5-8ab6-c160897b1e66.png)


Thanks for the feedback...
Brad

**Comment by seeam** [comment]
It looks good but as a user I am sharing my opinion. At first think people who uses iOS are already familiar with little bit of abstraction and doing all action using apple's pattern. And that icon which more looks like share icon is universal everywhere, from safari to iBooks, Photos and even in App store. So little bit of hierarchy is not a problem for iOS users.
Also in this prototype there are two issue or confusion:
- Sliding panel is for finding my current bookmarks, history and reading list, so if I tap to see my bookmarks it will also add the page as bookmark, that's somewhat confusing.
- What if I just want to bookmark the page, not interested in putting it into any folder?

**Comment by bradleyrichter** [comment]
@seeam Great feedback. Thanks.

I think I need to clarify a couple of things in the spec now to address your points above.

1. The normal tap to open the panel is retained as it works today. The tap-hold or tap-swipe would be the shortcut for the quick bookmark action. Also, it will glow orange to indicate when the current page is already bookmarked. 

2. Need to allow flat bookmarking as you suggested. I'll add that.

Also, we may be able to allow the safari bookmarking approach as well by using the Share button. (which has become a random access place for many things)

Next I will work on a clickable prototype and do more user testing. It may be that this combination is not intuitive enough. I think the fallback of opening the panel to make a bookmark is still a shorter and more visibly connected approach than either FX or Safari is currently using.

**Comment by diegodoval** [comment]
closed in https://github.com/brave/browser-ios/pull/379
