### ISSUE TITLE
find in page bar being hidden when attempting to navigate

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-ios#1376]
### Description:

When searching for words using "Find in Page", pressing the "next" button sometimes hides the entire search bar. You'll have to scroll up a bit to get the URL bar/search back in few and then click on "next" once again to find the next word. Searching through a large page also gets very janky.

### Steps to Reproduce

  1. load https://en.m.wikipedia.org/wiki/World_War_II
  2. tap on the "Share" icon and select "Find in Page"
  3. type in "germany" and click on the bottom arrow several times to search for the next work

You'll eventually notice that the entire "Find in Page" feature becomes very janky and the search bar keeps being hidden every time you press on the "next" arrow.

**Actual result:**

When searching for words on a page, the search bar at the bottom will be hidden every time a user clicks on next to search for the next word.. This makes searching a terrible experience.

Example of the issue: https://youtu.be/9otRByvJxWk

**Expected result:**

Searching through words using "Find in Page" shouldn't be hiding the search bar at the bottom every time a user selects "next" and scrolls to the next word. Searching should also be a smooth experience.

**Reproduces how often:** [Easily reproduced/Intermittent issue]

100% reproducible using the above STR.

**Brave Version:**

* `1.5.1 (17.11.22.19)` - Reproduced (current release)
* `15.2 (17.12.07.15)` - Reproduced

**Device details:**

* iPhone 6s+ with iOS 10.3.3 - Reproduced
* iPad Mini 4 using iOS 11.2 - Couldn't Reproduce

### Additional Information

@srirambv @LaurenWags can one if you please see if this is an issue on an iPhone with iOS 11?

**Comment by srirambv** [comment]
This is same as #1344
