### ISSUE TITLE
Deleting a top tile causes tiles to shuffle around

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1377]
### Description:
Deleting a top tile causes tiles to shuffle around

### Steps to Reproduce

  1. Visit a number of sites that there are enough top tiles created apart from the default ones
  2. Long press on the top tile and delete one of them that is added
  3. A new top tile gets added at the end moving the others to previous position
  4. Tap anywhere to come out of delete mode, last row top tiles change from what is seen in step 3

**Actual result:**
https://youtu.be/rSovxwQAiBI

**Expected result:**
Should retain top tiles what is shown on the edit mode

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easily reproduced

**Brave Version:**
1.5.1(17.11.20.10)

**Device details:**
iPhone 7+ (iOS 11.1.2)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by vs77bb** [comment]
Hi @jhreis Vivek from Gitcoin here. Would this be a good candidate for a Gitcoin bounty? We'd be happy to put one up, if so, so dev's from our community see. Let us know if you'd like community eyes on another issue, instead!

**Comment by jhreis** [comment]
This would not be an issue moving forward as top sites are being swapped out for "favorites". Going to close out for now.

**Comment by jhreis** [comment]
@vs77bb No, this would be a bad issue 😝 
Ha, on a more serious note, I am sure I can dig something good up if you're still willing to bounty something 😄 

Was wondering about:
https://github.com/brave/browser-ios/issues/837

**Comment by srirambv** [comment]
Marking as `QA/no-qa-needed` as feature is obsolete
