### ISSUE TITLE
HTTPSEverywhere not redirecting to https version of some pages 

### ISSUE THREAD

**Issue by JamborJan** [brave/browser-ios#138]
See also: https://twitter.com/jamborjan/status/701145210219319301

Not working:
- meetup.com
- motherboard.vice.com

While other pages which still provide http are working e.g.:
- apple.com

Let me know when I can do / test something.

**Comment by JamborJan** [comment]
By the way: tested on iOS 9.2.1

**Comment by garvankeeley** [comment]
Thanks for the report. The green lock icon is not showing when it should, we need to fix ASAP.

**Comment by JamborJan** [comment]
Hey @garvankeeley sorry to disagree, but for me it's not only an display issue of the green lock as you say. When I analyze my network traffic I can clearly see the plain http packages being send between my mobile device running the Brave browser and meetup.com which I use as test website.

**Comment by garvankeeley** [comment]
Great thanks for checking, I hadn't looked in debug yet with the HTTPS-E logging on, but that saves some research.

**Comment by diracdeltas** [comment]
meetup.com homepage in Chrome with HTTPS Everywhere does not redirect to HTTPS. are you sure you haven't added a custom rule for it in your regular browser?

motherboard.vice.com should though

**Comment by diracdeltas** [comment]
FWIW, we are on HTTPS Everywhere 5.1.2 rulesets right now. Will update to 5.1.3 once #135 is done.

**Comment by JamborJan** [comment]
1) I believed that it was working on my Desktop while I had a https Bookmark (knowing > believing). Sorry for that
2) Now you can make a new rule
3) @diracdeltas could you imagine a way of making https the default and only if a side is not providing https make the browser load http after ensuring read shields down url bar? I don't know what this means in terms of performance of page loading when you make the extra round when loading a page which is not providing https

**Comment by diracdeltas** [comment]
3) has been discussed before on various HTTPS Everywhere threads. The problem is that just because a site is available over HTTPS doesn't mean it's not broken over HTTPS (due to mixed content usually)

**Comment by garvankeeley** [comment]
@JamborJan Interesting idea to have a mode that only loads HTTPS. I would like that as an advanced option in settings, not sure if users are ready for anything that complicated (in terms of frequency of site loading problems). Would be neat to try out.

**Comment by diracdeltas** [comment]
https-only mode (Block all HTTP) is already in chrome/firefox https everywhere. i've gotten a lot of good feedback about it from advanced users.

**Comment by JamborJan** [comment]
That is 100% a thing I would like to have. But I agree that the average user would have issues when some sides don't load properly. But I guess it will be the annoying stuff like ads and shit which is provided insecure over http anyway ... So it might really be worth a try :-)
