### ISSUE TITLE
Unable to switch to Telegram App with touch id enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1384]
### Description:
Report from twitter https://twitter.com/cryptingcow/status/941367464926916610

### Steps to Reproduce

  1. Install store app
  2. Enable touch ID(browser pin)
  3. Open Telegram group invite
  4. Prompts to switch to App
  5. Switches back to Brave and asks for touch ID

**Actual result:**
Unable to switch to Telegram App with touch id enabled

**Expected result:**
Once opened should not switch back to Brave unless tapped on `<Brave` link on the top left 

**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**

**Device details:**

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
I wasn't able to reproduce this issue on iPhone 7+ with store version. Link opened would instantly switch to Telegram app and opens the group but doesn't try to switch back to Brave

**Comment by iccub** [comment]
Tried to test it on old 1.5 version and it's the same, instantly switches to telegram with no problems, ip7 iOS 11
