### ISSUE TITLE
Close tab button hit area needs to be bigger to capture user action

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1385]
### Description:
Report from twitter https://twitter.com/brave/status/942892408160665601

### Steps to Reproduce

  1.  Not sure
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**

**Device details:**

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Should be fixed in 1.6, as we adjusted the dimensions of this button.
