### ISSUE TITLE
Top down swipe causes fingerprint prompt to popup

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1388]
### Description:
Top down swipe causes fingerprint prompt to popup

### Steps to Reproduce

  1. Install app store build
  2. Enable browser pin
  3. With app in focus pull down lock screen, prompts for browser pin to unlock
  4. Swipe up to bring control center, prompts for browser pin

**Actual result:**
https://youtu.be/1T8Q5T8AhGI

**Expected result:**
Should not prompt when the lock screen or control center screen is active

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**
1.5.2(17.12.12.15)

**Device details:**
iPhone 6/7+ (iOS 11.1.3)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Not seeing on iPad

**Comment by iccub** [comment]
Will be fixed by #1387

**Comment by srirambv** [comment]
Works fine but swipe up control center retains the overlay momentarily before clearing it
https://youtu.be/A-JrYdkEcnI
