### ISSUE TITLE
Newly added top site tiles shows URL instead of  site name

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1394]
### Description:
Newly added top site tiles shows URL instead of  site name

### Steps to Reproduce
  1. Clear browsing history so that default top tiles are removed
  2. Visit a couple of sites so that they are added to the new tab page as top site tiles
  3. Tiles shows URL instead of the site name

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/34489683-3153d2c2-efd5-11e7-8e60-8e97a9e57597.png)

**Expected result:**
Tiles should show site name instead of URL

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy

**Brave Version:**
1.5.2 (17.12.12.15)

**Device details:**

All

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Should be retested with top sites being replaced by favorites.

**Comment by LaurenWags** [comment]
Could not reproduce on iOS10 iPad or iPhone both using version 1.6.2 (18.05.29.10) when manually adding sites to favorites (using share picker).
