### ISSUE TITLE
Allow user to customize top sites

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#1397]
Currently top sites use a frequency algorithm, and are not pinnable or changable.

We want to allow the user to completely customize this. The bookmark panel will now have a static, undeletable folder called "Top Sites" (or some such name). Bookmarks stored here will now be the _only_ source for new tab top sites. If this folder is empty, the use will have no top sites.

Top Sites should be converted to a collection view to allow for an undetermined amount of bookmarks, and should prioritize bookmark name > bookmark url. Top Sites no longer need to be deletable from the top sites page either.

- [ ] Add static, undeletable Top Sites bookmark folder
- [ ] Prefill Top Sites folder with default websites
- [ ] Update Top Sites panel to be a collection view (scrollable)
- [ ] Update Top Sites to pull solely from the Top Sites bookmark folder
- [ ] Present bookmark `name` with a fallback to bookmark `url` (currently only `url` is ever shown)

**Comment by iccub** [comment]
Small note: this will also solve #1394 naming inconsistency.
