### ISSUE TITLE
hacker news: only scrollable after reload

### ISSUE THREAD

**Issue by lmcardle** [brave/browser-ios#141]
I can not scroll on https://news.ycombinator.com/ unless I put shields down.

**Comment by garvankeeley** [comment]
Thanks for the report, i see that too on initial page load. We'll have to look at it further, but it seems like the reload effect of toggling the shield is what gets the page working, as when i leave shields up, and pull down to reload, the page loads fully and i can scroll

**Comment by lmcardle** [comment]
You are right. Looks like the same issue happens with shields down on
initial load. Refreshing fixes it.

**Comment by garvankeeley** [comment]
see also #142

**Comment by garvankeeley** [comment]
fix by 965a1d6

**Comment by SeAlgoAsoma** [comment]
I've seen this same issue on a few pages over the last few hours.
