### ISSUE TITLE
Only one bookmark or folder item created 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1411]
### Description:
Bookmarks and bookmark folders are not created instantly when Sync is enabled and the device is synced to a Sync group

### Steps to Reproduce
   1. Clean install 1.5.3
   2. Create a bookmark folder on the left wall, folder is created instantly 
   3. Visit a site, add bookmark on the left wall, bookmark not added

   1. Clean install 1.5.3
   2. Visit a site, add bookmark on the left wall, bookmark is created instantly 
   3. Create a bookmark folder on the left wall, bookmark folder is not added
   
**Actual result:**
https://youtu.be/Y2JuKMuvgB4

**Expected result:**
Should create folders and bookmarks 

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Consistently

**Brave Version:**
1.5.3(18.01.20.12)

**Device details:**
iPad (iOS 11), iPhone (iOS 11)

### Additional Information
cc: @iccub @jhreis

**Comment by srirambv** [comment]
Here's another behaviour of the same bookmarks issue
https://youtu.be/aDVaLk-DFdo

**Comment by jhreis** [comment]
@srirambv this should be fixed on most recent beta build. (now 1.6). Please verify though.

**Comment by jhreis** [comment]
@srirambv Can we get this tested again, and closed if fixed or updated if still an issue. Thanks!

**Comment by srirambv** [comment]
This works on 1.6(18.04.17.16).
