### ISSUE TITLE
Top tile starts with a generic icon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1414]
### Description:
Top tile starts with a generic icon

### Steps to Reproduce

  1. Clean install and launch 1.6
  2. Facebook top tile shows some generic icon before loading the correct top tile icon
  3. Clear private data, top tiles gets realigned
  4. Open a new tab Facebook shows generic icon before loading the correct top tile icon
  5. Open a new tab, same generic icon shown for Facebook before loading the correct top tile icon

**Actual result:**
https://youtu.be/DcE5AZBkozw

**Expected result:**
Should load proper top tile icon

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy

**Brave Version:**
1.6(18.01.24.11)

**Device details:**
iPad (iOS 11)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Need to verify for iPhone

**Comment by srirambv** [comment]
This is not specific to the first top tile. Even with site suggestion it shows the generic icon.
![image](https://user-images.githubusercontent.com/17010094/35385783-7b8ef818-01ef-11e8-8148-26c249c801ef.png)

**Comment by iccub** [comment]
I fixed the facebook icon issue, search suggestions always show the generic icon aren't they?

**Comment by srirambv** [comment]
I think so yes. Used to be a different generic icon before

**Comment by srirambv** [comment]
Still an intermittent issue on iPhone but not a blocker. happened 1/5 times.
