### ISSUE TITLE
YouTube video ad reported

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-ios#1415]
### Description:
A reddit contributor has reported an ad on YouTube.com in Brave. 

https://www.reddit.com/r/BATProject/comments/7sub75/im_sorry_to_double_post_but_this_is_a_legit_ad/ 
 - Needs investigation. 
 - Needs attempt to repro 

### Steps to Reproduce

 - Opened YouTube.com in Brave
 - Prompted by an adidas banner ad to start the webpage
 - Searched “VEVO” (they run ads often)
 - Clicked a random video and was greeted by another pre-roll ad.
 - Clicked shield in the top right corner and it says I’ve blocked “35 ads and trackers, 0 https upgrades, 0 scripts, and 2 finger printing methods

**Actual result:**

**Expected result:**
no ads. 

**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**
Version 1.5.2 (17.12.12.15)

**Device details:**
Device iPhone 8 (iOS 11.2.2)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

**note: updated to include info provided by the contributor on Reddit.

**Comment by srirambv** [comment]
Seeing this on 1.6 but not on 1.5.2

**Comment by BrendanEich** [comment]
Saw on iOS today.

**Comment by lukemulks** [comment]
Was able to repro on Android - investigating. cc: @SergeyZhukovsky as an FYI.

**Comment by lukemulks** [comment]
Report from Twitter: https://twitter.com/CryptoGerald/status/959461655682756608

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/ads-on-youtube-not-being-blocked-on-brave-mobile/15493?u=eljuno

**Comment by Jacalz** [comment]
Saw this today on my iPad 😅

**Comment by Jacalz** [comment]
I saw it on 1.5.2 😅

**Comment by srirambv** [comment]
@Jacalz  are you able to consistently see the ad's ?

**Comment by jhreis** [comment]
My wife saw an ad too. Definitely something wrong. @lukemulks Have you been able to look at this? Is it a general adblock thing (wondering, as it was apparently observed on Android too), or something on iOS side?

We can investigate a bit more if needed too.

**Comment by Jacalz** [comment]
I am having trouble seeing the ads since American ads seem to be blocked but Swedish ads are getting through for me 😅 @srirambv

**Comment by jhreis** [comment]
The problem has been identified. This is due to my mistake of not running first party domains through the adblock lib. Will be releasing a hotfix shortly.

**Comment by srirambv** [comment]
No pre-roll ad seen on the YT channel videos as mentioned in https://github.com/brave/browser-ios/issues/1415#issue-291469371

**Comment by kjozwiak** [comment]
Noticed that sometimes the ad indicator quickly appears showing you that something that's about `20secs` will be played but is skipped right away and the video is correctly played. Went through about 20-30 different videos and haven't seen one ad.
