### ISSUE TITLE
Unable to setup Sync on iOS

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1417]
### Description:
Unable to setup Sync on iOS

### Steps to Reproduce

  1. Clean install 1.6
  2. Enable Sync, Create a new sync group
  3. Tap on both `Add a Mobile Device` and `Add a computer` simultaneously
  4. Shows error `Unable to create a sync group`
  5. Repeat step 3 keeps showing the loading spinner but never creates a sync group or shows error

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/35386277-7f723c5e-01f1-11e8-8830-43186f6e9e19.png)

**Expected result:**
Should only take one touch point and create a sync group 

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**
1.6(18.01.24.11)

**Device details:**
iPad (iOS 11)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @jamesmudgett @iccub

**Comment by jhreis** [comment]
This is due to that view allowing multiple user interactions, we should limit this, may need to restrict the pop animations, but we can see.

**Comment by iccub** [comment]
Fixed here https://github.com/brave/browser-ios/pull/1476
