### ISSUE TITLE
Deny camera access during sync setup freezes the Enable camera screen

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1418]
### Description:
Deny camera access during sync setup freezes the Enable camera screen

### Steps to Reproduce

  1. Scan a sync chian code
  2. Tap on enable camera
  3. Tap on `Dont allow`
  4. Go back to Sync and tap on Scan a sync chain code
  5. Tap on enable camera, nothing happens

**Actual result:**
Deny camera access during sync setup freezes the Enable camera screen

**Expected result:**
Camera access should be given even if denied the first time
**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**
1.6  (18.01.24.11)

**Device details:**
All

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Issue discovered by @iccub

**Comment by jhreis** [comment]
We will probably need to do something like popping up notifying the user that we do not have proper permissions and offer to direct them to the system preferences.
