### ISSUE TITLE
Tabs and History not sync'd between devices

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1419]
### Description:
Tabs and History not sync'd between devices

### Steps to Reproduce

  1. Create a sync group on device 1
  2. Join device 2 to the sync group
  3. Visit couple of sites on device 1 to add browsing history
  4. History doesn't get added to device 2
  5. Tabs visited in device 1 is not created on device 2

**Actual result:**
Tabs and History not sync'd between devices

**Expected result:**
Tabs and history should get added on device 2 when joined to a sync group

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**
1.6 (18.01.24.11)

**Device details:**
All

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This is currently expected. The real bug is that we show those options in the UI.
