### ISSUE TITLE
page scrolling issue

### ISSUE THREAD

**Issue by bridiver** [brave/browser-ios#142]
hashicorp.com doesn't scroll correctly on Brave. It's hard to describe the issue, but if you open the page and try to scroll down you will see it. It appears to work correctly on mobile Safari, but I didn't check against FF mobile

**Comment by garvankeeley** [comment]
I check these against Dolphin/Puffin (UIWebView browsers) to see if it is the webview or something we are doing. I'll take a look

**Comment by garvankeeley** [comment]
How this site implemented scrolling isn't cooperating with UIWebView. It seems like the scroll events that the top level div (with the line "Application delivery done right") is expecting aren't sent until the scroll is completed, as only when scroll is completed does the site render correctly.

**Comment by bridiver** [comment]
so is this a UIWebView bug? Is it worth submitting a report to Apple?

**Comment by garvankeeley** [comment]
Yup UIWebView bug, can be filed as a radar, but it would need to be isolated, only critical/widespread bugs in UIWebView are likely to get fixed though
