### ISSUE TITLE
Tap after autocomplete suggestion does not remove selection

### ISSUE THREAD

**Issue by indutny** [brave/browser-ios#1420]
### Description:

When omnibar displays an autocomplete suggestion (say: `reddit.com/`) the not-yet-typed part of the address is selected. Other browsers (including Firefox Focus) allow user to remove the selection and continue typing by tapping the address bar. However, the same action in Brave iOS does nothing.

My use case is rather simple, I'd like to type `re` to get `reddit.com/` suggestion, then deselect it and type `r/funny` or `r/gifs`, etc.

### Steps to Reproduce

  1. Type `re` in omnibar to get `reddit.com/` suggestion
  2. Tap suggestion, or after it
  3. Observe that selected text in omnibar

**Actual result:**

Selected text stays selected

**Expected result:**

Selection should disappear, and user should be left with suggestion and blinking cursor after it.

**Reproduces how often:** [Easily reproduced/Intermittent issue]

Always/Easily reproduced

**Brave Version:**

v1.5.2 (17.12.12.15)

**Device details:**

iPad Pro 12.9'' (iOS 11.2.5)

**Website problems only:**
- [x] did you check with Brave Shields down?

- [x] did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- [x] did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jonathansampson** [comment]
I'm fairly certain this is a regression. I see it too, but remember this working in the past.

**Comment by srirambv** [comment]
Is this same as  #1285?

**Comment by indutny** [comment]
@srirambv I think it has the same roots, but the scenario is a bit different.

**Comment by iccub** [comment]
@indutny I use omni bar exactly the same and also find it annoying.
Submitted pr for it [here](https://github.com/brave/browser-ios/pull/1422), if everything will go right, fix should be live with Brave 1.6. Thanks for the report

**Comment by indutny** [comment]
Thank you, @iccub!
