### ISSUE TITLE
Block all mixpanel SDK requests except for https://metric-proxy.brave.com/*

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-ios#1423]
see https://github.com/brave/mixpanel-android/issues/1 for context

the mixpanel SDK may be leaking data directly to mixpanel.com without going through our proxy server. to prevent this, our mixpanel SDK forks (https://github.com/brave/mixpanel-swift, https://github.com/brave/mixpanel-iphone) should ONLY allow requests to https://metric-proxy.brave.com/*.

**Comment by jhreis** [comment]
iOS currently does not use Mixpanel. There may be old versions that are still using it. I did revoke the AP_KEY, so requests _should_ have stopped, if there are still requests coming in, I will tear down the entire project online and build a new one if we decide to add events in the future.

**Comment by jhreis** [comment]
Just verified there was still Mixpanel data being collected, and resetting the project data does not reset the secret/key, so I have deleted the entire Mixpanel project. We can create a new one, if we ever need that in the future.

**Comment by diracdeltas** [comment]
Thanks @jhreis for looking into this! We should re-open this issue if/when we decide to use mixpanel again.
