### ISSUE TITLE
iPad Panel open: hard to find close button, Safari highlights theirs

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#143]
We have a number of complaints about this, well, not always explicitly that the button isn't highlighted, rather than closing the panel is confusing. The only difference between us and Safari in this regard is that Safari highlights the button you must press to close, we should do the same

**Comment by bradleyrichter** [comment]
1.1 fix: emulate Safari

![image](https://cloud.githubusercontent.com/assets/13509546/13338777/90b455d8-dbd8-11e5-884c-309618c01935.png)


1.2 improvement: 
- add "tap main window to close panel" like safari has

1.3 improvement: 
- add "swipe panel to close"

**Comment by garvankeeley** [comment]
fixed by 0f4bac2bfeea17e0efba2dd68ae67b598cd0c32a
