### ISSUE TITLE
iPad Camera isn't upright for scanning QR Code when device is in portrait mode 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1432]
### Description:
iPad Camera isn't upright for scanning QR Code when device is in portrait mode 

### Steps to Reproduce

  1. Enable Sync on iPad
  2. Scan QR code, enable access to camera
  3. Camera is in wrong orientation. Extremely difficult to point on QR code to scan.

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/35863724-8a8c3f4e-0b75-11e8-8974-99aa3efe8f2e.png)

**Expected result:**
Camera should be in upright position

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**
1.6(18.02.05.11)

**Device details:**
iPad (iOS 11)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @jhreis @iccub

**Comment by iccub** [comment]
Got it fixed, with one minor issue left. When you start in horizontal mode, it won't rotate until you switch orientation. Should be good enough though.

**Comment by jhreis** [comment]
@iccub can we just lock the orientation entirely? Why is this a problem to start?

**Comment by iccub** [comment]
Update: fixed all orientation issues, thanks for guiding me @jhreis.
