### ISSUE TITLE
url bar doesn't show when using scroll to top

### ISSUE THREAD

**Issue by flpwgr** [brave/browser-ios#144]
Hi!

After scrolling down any page (making the url bar hidden), if I click on the status bar to do a Scroll to the Top, the url bar doesn't show just like the screen above:

![img_2425](https://cloud.githubusercontent.com/assets/1329042/13252308/bcf65e7c-da14-11e5-9933-483e004aac63.PNG)

**Comment by garvankeeley** [comment]
Thanks for the report! I can't repro (trying it now on google search results), does it happen every time for you?

**Comment by felipew** [comment]
Hi, not every time, but it happen very often, usually when the scroll isn't finished.

Here is a video showing the problem..

![brave 1](https://cloud.githubusercontent.com/assets/1329042/13258924/e9eb18c2-da33-11e5-8014-1a852288234d.gif)

**Comment by garvankeeley** [comment]
++1000 for the vid. I see it now, you are right, the down scroll followed by the sudden upscroll bypasses the check for "should I show toolbar"

**Comment by jamesmudgett** [comment]
Requires, QA close if issue can no longer be reproduced.

**Comment by srirambv** [comment]
Works fine on 1.4.2. on both iPhone and iPad. However on iPad after scrolling up, empty div is shown but tapping on the empty space opens up the link thats hidden
![image](https://user-images.githubusercontent.com/17010094/30464653-6ba9c5e8-99f0-11e7-9bdc-87fe7043f82a.png)
