### ISSUE TITLE
Creating new bookmark folder crashes brave 

### ISSUE THREAD

**Issue by illmaticone** [brave/browser-ios#1446]
# Test plan
1. Attempt to create a bookmark folder on left wall
2. Folder should get created and browser should not crash 
3. Add a bookmark under folder, browser should not crash
4. Add a nested bookmark folder, browser should not crash

# original issue
2 closes issues found but seems like new bug.  Able to reproduced easily.  

### Description:

When creating a new bookmark folder brave crashes immediately 

### Steps to Reproduce

  1. Attempt to create new bookmark folder 
  2.
  3.

**Actual result:**

App crashes 

**Expected result:**

App should not crash and allow bookmark folder creation dialog 
**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**

Version 1.5.3 (18.02.14.13)

**Device details:**

iPhone X 
11.3 beta 2
**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Do you use any special characters or it doesn't matter how the folder is named and crashes regardless?

**Comment by illmaticone** [comment]
Never got to a prompt.   As soon as I clicked new folder it crashed.

**Comment by kjozwiak** [comment]
Can't seem to reproduce using the following:

* iPhone 6s+ running iOS 10.3.3 with `v1.5.3 (18.02.14.13)` - Couldn't reproduce
* iPad Mini 4 running iOS 11.2.5 with `v1.5.3 (18.02.14.13)`- Couldn't reproduce

Wonder if this is related to iPhone X or something that iOS 11.3 BETA 2 introduces?

**Comment by srirambv** [comment]
Reproduced on iOS 11.3 beta on iPhone 6. Tapping on New folder causes the crash. No extra steps required. 
https://youtu.be/1Nk1fTB6dFs

**Comment by illmaticone** [comment]
Thanks for verifying this.  So seems like a 11.3 beta issue.  BTW... why don’t I see any crash dumps in the analytics section under privacy? I was hoping to see one after the app crashed and post the stack trace... new  bug/ feature ?

**Comment by srirambv** [comment]
Crash reports aren't listed on the app currently

**Comment by kjozwiak** [comment]
+1 https://community.brave.com/t/cannot-create-new-bookmark-folder/19140/

Quickly checked and unfortunately this is still an issue, reproduced on the following devices:

* iPad Mini 4 on `iOS 11.3` using `v1.5.4 (18.02.23.08)` - Reproduced
* iPhone 6s on `iOS 11.3` using `v1.5.4 (18.02.23.08)` - Reproduced
* iPhone 6s+ on `iOS 10.3.3` using `v1.5.4 (18.02.23.08)` - Couldn't Reproduce

**Comment by Jacalz** [comment]
I am able to reproduce this on my iPhone 5s with 11.3

**Comment by iccub** [comment]
Fixed it here btw https://github.com/brave/browser-ios/pull/1499, we should merge it and push an update soon

**Comment by Jacalz** [comment]
I can reproduce as well using 1.6 and iOS 11.3.1.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/trying-to-create-a-folder-in-favorites-crashes-bravo/21384?u=eljuno

>I downloaded and installed Brave, added _mysite to favorites.
.Then tried to add a new folder, and Brave crashed. Bookmark folder was not created.
Retried several times , same thing.

>IOS, 11.3, iPhone 7, Brave Version 1.5.6

**Comment by datgrl** [comment]
Why is this issue closed when it’s still occurring?

**Comment by srirambv** [comment]
The issue is fixed and available in next release. Hence closed.

**Comment by kjozwiak** [comment]
> Why is this issue closed when it’s still occurring?

@datgrl are you still running into this issue? Which version are you using? We just released `1.6` which resolves the problem. You should be receiving an update in the next few days if you're not on `1.6` yet.

**Comment by Jacalz** [comment]
I can confirm that this is indeed fixed in 1.6 and workin great 👍
