### ISSUE TITLE
Incorrect browser pin accepted to unlock 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1447]
### Description:
Reported via community https://community.brave.com/t/bug-in-pin-validation-on-ios-brave-browser/16300/2

### Steps to Reproduce

  1. Clean install appstore version
  2. Enable browser pin and enter pin and confirm pin
  3. Remove app from memory
  4. Relaunch app, asks for browser pin, enter wrong pin, browser unlocks

**Actual result:**
https://youtu.be/VeB-DFjNa9M

**Expected result:**
Should not accept wrong pin when app is loaded into memory first time

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**

1.5.3(18.02.14.13)
**Device details:**

All

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

cc: @jhreis @iccub

**Comment by iccub** [comment]
@srirambv can you confirm it doesn't happen with earlier versions?
Just tested on 1.5.2 and 1.5 on simulator and can reproduce it.

**Comment by kjozwiak** [comment]
Great catch @srirambv 👍
