### ISSUE TITLE
Block First Party Domains

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#1451]
iOS currently does not run first party domains through the Adblock lib. This is unintentional and needs to be fixed. Most noticeable complaint is #1415

**Comment by jhreis** [comment]
Fixed, and closing per https://github.com/brave/browser-ios/commit/7ca33711795d79ff0a32346ea718eb00b0285ef5

**Comment by kjozwiak** [comment]
@jhreis is there anything that needs to be tested here other than ensuring that #1415 has been fixed? If there is, could you please include the test case?

**Comment by jhreis** [comment]
Please see #1415 for steps. If YT ads are blocked, then we are successfully blocking 1st party domains! 😃
