### ISSUE TITLE
Update to HTTPS Everywhere 6.0

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-ios#1460]
HTTPS Everywhere  6.0 has been deployed to S3! It adds a lot of new rules.

There is some chance this release will break things (since there was a ruleset format change), so I recommend testing it before bumping the prod version to 6.0.

Here it is: 
https://s3.amazonaws.com/https-everywhere-data/6.0/httpse.leveldb.tgz
https://s3.amazonaws.com/https-everywhere-data/6.0/httpse.leveldb.zip

test plan:
Go to http://www.haproxy.org/. It should be upgraded to HTTPS
Go to http://www.thompsonhotels.com/. Images should appear on the site.
Go to https://https-everywhere.badssl.com/. Under shields, it should show 1 HTTPS upgrade.

**Comment by diracdeltas** [comment]
it's not necessary to fix this before migration but it would be good since we're so far behind on HTTPS Everywhere upstream. it should be a 1-line change.

**Comment by iccub** [comment]
Simply bumping version to 6.0 doesn't seem to work for `thompsonhotels.com`, it doesn't load the page and closing/refreshing crashes the app, does not crash on 5.2. Two other links work ok

@diracdeltas do you have any references for the ruleset format change, I could investigate a bit more
