### ISSUE TITLE
Tab count not shown on 1.6

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1470]
### Description:
Tab count not shown on 1.6

### Steps to Reproduce
  1. Install 1.6 beta build
  2. Open 4-5 tabs and load sites in them
  3. Tab container button on snack bar doesn't show the tab count

**Actual result:**
Tab count not shown on snack bar

**Expected result:**
Should show the tab count on tab container button

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy

**Brave Version:**
1.6(18.02.27.22)

**Device details:**
iPhone 7+ (iOS 11.2.5)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jamesmudgett** [comment]
This is by design
