### ISSUE TITLE
pbxcp error when product test

### ISSUE THREAD

**Issue by sunliancheng** [brave/browser-ios#1479]
### Description:
I use Xcode later and run test

error: /Users/s/Documents/GitHub/browser-ios/brave/adblock-regions.txt: No such file or directory

CpResource brave/adblock-regions.txt /Users/s/Library/Developer/Xcode/DerivedData/Client-gmcthfikklesmwaaumepshcrnxzt/Build/Products/Debug-iphonesimulator/Client.app/adblock-regions.txt
    cd /Users/s/Documents/GitHub/browser-ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/s/Documents/GitHub/browser-ios/brave/adblock-regions.txt /Users/s/Library/Developer/Xcode/DerivedData/Client-gmcthfikklesmwaaumepshcrnxzt/Build/Products/Debug-iphonesimulator/Client.app

error: /Users/sun/Documents/GitHub/browser-ios/brave/adblock-regions.txt: No such file or directory
### Steps to Reproduce

  1.pull repo
  2../checkout.sh
  3.open xcode and run product test

### Additional Information

sorry my English , I am student, thanks for your project, I use & enjoy it

**Comment by jhreis** [comment]
You must also run the setup script, per the README:
`(cd brave && ./setup.sh your.fake.appid)`
