### ISSUE TITLE
Active tab not highlighted when exiting video full screen

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1481]
### Description:
Active tab not highlighted when exiting video full screen

### Steps to Reproduce

  1. Open 2-3 tabs so that tabs bar is visible 
  2. Open YouTube in a tab and play a video in full screen
  3. Exit video full screen, active tab is not highlighted, tapping on the webview activates the active tab 

**Actual result:**
Active tab not highlighted when exiting video full screen

**Expected result:**
Active tab should be highlighted when full screen video is closed

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy

**Brave Version:**
1.6 (18.03.01.19)

**Device details:**

iPhone 7+(iOS 11.2.6)
**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Should be retested with 1.5.5 beta, per https://github.com/brave/browser-ios/pull/1441

Although not directly related, impact could be similar.

**Comment by srirambv** [comment]
Seems fixed  in 1.6(18.04.20.10).

**Comment by srirambv** [comment]
Verified with Vimeo.com on iPad as YT doesn't go fullscreen
