### ISSUE TITLE
Doesn't open link on third party app

### ISSUE THREAD

**Issue by seeam** [brave/browser-ios#149]
For example, while visiting medium.com, they shows a header at the tab to open the link into medium app. After clicking on **Open In App** brave doesn't open the link into app, rather it's redirect to something like this: medium://p/xxxxxxxxxxxxxx
But if I search on google for a medium article and tap on the link, it opens medium app.

I have also tested with Twitter and it's first try to load twitter://timeline and then redirects to iTunes for downloading twitter app. But I have Twitter app installed.

I'm on iPad and brave version is 1.0 (16.02.12.13)

**Comment by garvankeeley** [comment]
Fixed for 1.2.6 release
