### ISSUE TITLE
Top tiles don't get updated

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1491]
### Description:
Top tiles don't get updated

### Steps to Reproduce

  1. Clean install 1.6 ((18.03.21.14)
  2. Visit a few sites repeatedly in new tabs
  3. Site favicon is not added to the top tiles

**Actual result:**
Top tiles don't get updated

**Expected result:**
Frequently visited site favicon should get added as a top tile

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**
1.6 ((18.03.21.14)

**Device details:**
iPhone 7+ (iOS 11.2.6)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @iccub

**Comment by iccub** [comment]
We replaced top sites with favorites. So now user can choose which websites he wants to pin in place of top sites. Long press on if you want to rearrange/edit them.

**Comment by jhreis** [comment]
This is new, intentional behavior.
