### ISSUE TITLE
Update Eureka dependency to 4.1.1

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-ios#1493]
Eureka 4.1.0 or later is needed to build with Xcode 9.3/Swift 4.1 ([release notes](https://github.com/xmartlabs/Eureka/releases/tag/4.1.0)).

**Comment by mzygar** [comment]
Looks like already done in #1494

**Comment by iccub** [comment]
Yes, it's been merged. The project should work on Xcode 9.3
