### ISSUE TITLE
User-Agent String: add Brave/x.x.x 

### ISSUE THREAD

**Issue by ZigZagIL** [brave/browser-ios#151]
Tested and got this:
Mozilla/5.0 (iPhone; CPU iPhone OS 9_2_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13D15

Should declare it's Brave.

**Comment by garvankeeley** [comment]
Thanks for the report, should append:  (Brave x.x) to this

**Comment by garvankeeley** [comment]
3dc8947e2a835f5940313fed1dc0881176f26f8f fixed

**Comment by bridiver** [comment]
I think we might actually want to revert this change for fingerprinting reasons cc @diracdeltas

**Comment by diracdeltas** [comment]
From a fingerprinting perspective, it would be best if Brave iOS reported the same UA string as Firefox iOS until the user numbers are higher.

**Comment by bridiver** [comment]
what about Chrome or Safari? Using Chrome may or may not eliminate the google home page message telling you to try Chrome and Safari has a much larger user base to hide in. Not sure which, if any, are using the older webview.

**Comment by diracdeltas** [comment]
yeah, reporting as chrome/safari would be better assuming it doesn't cause site compatibility issues

**Comment by bridiver** [comment]
I'm going to re-open per @BrendanEich's request to make these consistent

**Comment by bridiver** [comment]
sorry, actually I'm going to create a new ticket

**Comment by bridiver** [comment]
https://github.com/brave/browser-ios/issues/360
