### ISSUE TITLE
Back button not restoring scroll position (hard to repro)

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-ios#152]
When following a link from a fairly long page, then returning to the previous long page, Chrome returns to approximately the same offset into the long page, but Brave returns to the top.

**Comment by garvankeeley** [comment]
I have seen this happen, but I couldn't reproduce it when I would try again. If you have a site that it is consistent on let me know. Do you see this more on some sites than others?

**Comment by SLBondy** [comment]
I had a support comment about it and I have noticed it on people.com, but not consistently.  Sometimes it will load partially down the page, but not far enough to where I was in the news feed.  It seems more comment on long news feed sites.

**Comment by jamesmudgett** [comment]
No control over this, closing.
