### ISSUE TITLE
Edited bookmarks doesn't update favicon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1530]
### Description:
Edited bookmarks doesn't update favicon

### Steps to Reproduce

  1. Add a new bookmark after the page is loaded completly so that favicon and page title is added correctly
  2. Edit the bookmark, rename the title and add a valid URL 
  3. Load the bookmark in a new tab, favicon remains of the original site that was bookmarked

**Actual result:**
Edited bookmarks doesn't update favicon

**Expected result:**
Should add a generic favicon upon saving and should add correct favicon when bookmark is loaded

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy

**Brave Version:**
1.5.6(18.04.11.13)

**Device details:**
iPhone 7+ (iOS 11.3)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Liunkae** [comment]
PR: #1563

**Comment by jhreis** [comment]
@Liunkae Thanks for the PR comment. If you look right above your comment you will actually see Github automatically links to the new PR including the current status, so no need to manually do this 😃

**Comment by Liunkae** [comment]
@jhreis OK. I just have a habit of mentioning the PR so issue subscribers get notified that the problem is about to be fixed. 😉
