### ISSUE TITLE
Display notification to user that topsites have now become favorites

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-ios#1534]
![screen shot 2018-04-20 at 10 16 02 am](https://user-images.githubusercontent.com/318119/39059369-f0ee6518-4483-11e8-8a3f-898382edc55c.png)

## Steps to reproduce
1. Downgrade to older version of brave beta, pre 1.6
2. Visit some sites to create an auto generated topsite on home screen
3. Upgrade to 1.6 
4. You should see popup from the image above.

**Comment by srirambv** [comment]
Pop up shows correctly as per screenshot but clicking on keep defaults or convert causes all top tiles to be removed on 1.6.

**Comment by srirambv** [comment]
Here's an interesting update. When you click either options in the pop up all top tiles are removed but adding a bookmark causes default toptiles to be shown on a new tab.
