### ISSUE TITLE
URL Scheme crashes App (brave://open-url?url=)

### ISSUE THREAD

**Issue by ArtSabintsev** [brave/browser-ios#1537]
### Description:
I have a personal OSS library (https://github.com/ArtSabintsev/Freedom) that allows the opening of URLs in different browsers. During a routine QA test of one of the apps that The Washington Post's engineering team builds, it was discovered that opening any URL using the following scheme no longer works - the Brave app actually crashes when attempting to load an URL:

```
brave://open-url?url=https://www.washingtonpost.com/world/national-security/russia-iran-at-forefront-of-concerns-as-diplomats-from-leading-democracies-meet/2018/04/22/48828aa1-473b-4246-9696-1a8f9fc996fb_story.html
```

### Steps to Reproduce
  1. Install Brave on a device.
  2. Install any of the following apps: The Globe and Mail, The LA Times, The Salt Lake Tribune. This library is not live in The Washington Post app yet, so do not test that app.
  3. Load any article in those apps.
  4. Click share.
  5. Click "Open in Brave" in the share sheet.
  6. Opening the article crashes your app.

**Expected result:**

Expected result is for the URL to load.

**Reproduces how often:** 

Easily Reproducable

**Brave Version:**
v1.5.6 (18.04.11.13)

**Device details:**
Crashes on all devices.

### Additional Information
This used t work when I integrated this feature last year. I don't test it often so I can't tell you when it broke.

**Comment by jhreis** [comment]
Thanks for reporting. Closing per duplicate: https://github.com/brave/browser-ios/issues/1512
