### ISSUE TITLE
Navigating back causes bookmark to show up as bookmark folder

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1538]
### Description:
Navigating back causes bookmark to show up as bookmark folder

### Steps to Reproduce

  1. Create a bookmark on side wall
  2. Add a bookmark folder A
  3. Create a bookmark under folder A 
  4. Add a nested bookmark folder B under folder A
  5. Add a bookmark under folder B and create two more nested folders C,D under B
  6. Navigate back to folder A, bookmark under folder A shows as folder but clicking opens the site 

**Actual result:**
https://youtu.be/6YPlAMuhgGI

**Expected result:**
Navigating back from folder shouldn't cause bookmarks to show up as folder

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy

**Brave Version:**
1.6(18.04.20.13)

**Device details:**
iPhone/iPad (iOS 11.3)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
possibly #986 but behaviour seems opposite
Unable to check this on current build as browser crashes when creating a bookmark folder (#1446 )
@LaurenWags / @kjozwiak could you verify on iOS 10?

**Comment by LaurenWags** [comment]
Reproduced on iOS10 iPad

**Comment by jhreis** [comment]
This is taking a substantial amount of time. Given this is just a UI issue and doesn't actually break the bookmark, I am going to push this and we will readdress during our database refactor for sync v1.

**Comment by srirambv** [comment]
Not able to reproduce this on appstore build on iOS 11.
