### ISSUE TITLE
Adblocking method is in-consistent with brave-laptop [bug] [question]

### ISSUE THREAD

**Issue by seeam** [brave/browser-ios#154]
While forbes.com can be easily accessed via brave-laptop with turning on all the bravery settings, brave-iOS shows can't access forbes without turning off built-in adblocker. What is the issue here?

**Comment by garvankeeley** [comment]
1.1 has this fixed, I'll push that to Apple store tomorrow, hopefully gets approved quick.
We have to bypass the redirection 3146ddaa280ca5458bdc584e9b47498edfe9fab3, it is a bit odd

**Comment by seeam** [comment]
That's great, waiting for 1.1
