### ISSUE TITLE
Tab close button overlaps on page title

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1546]
### Description:
Tab close button overlaps on page title

### Steps to Reproduce

  1. Open enough tabs so that the page title gets truncated
  2. Switch to tab with long page title
  3. Close button overlaps on the text or the truncated elipse

**Actual result:**
1.5.6(18.04.11.13)
![image](https://user-images.githubusercontent.com/17010094/39256271-7e38fd06-487c-11e8-8752-875bfc970f08.png)

1.6(18.04.24.18)
![image](https://user-images.githubusercontent.com/17010094/39256292-87c4579e-487c-11e8-9c22-05f1c39f6fde.png)
![image](https://user-images.githubusercontent.com/17010094/39256298-89f6d654-487c-11e8-9c8a-5956c19ed570.png)
iPhone 
![image](https://user-images.githubusercontent.com/17010094/39256453-f2403912-487c-11e8-8969-7449ddf87418.png)

**Expected result:**
Close button shouldn't overlap on the page title

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**
1.6(18.04.24.18)

**Device details:**
iPad/ iPhone (iOS 11)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Fixed via https://github.com/brave/browser-ios/pull/1549
