### ISSUE TITLE
Fuzzy favicon fallback

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-ios#1551]
When detecting favicon, fallback to a single letter on colored background when minimum icon size isn't  available.

**Comment by jhreis** [comment]
I think this could just be dealt with in v2

**Comment by jamesmudgett** [comment]
small icons: quora.com, worldcoinindex.com, theverge.com
large icons: large icons: github.com, techcrunch.com, dribbble.com, coindesk.com, scienceaf.com, news.ycombinator.com

**Comment by jhreis** [comment]
When saving a favorite with a "small icon", it will now be replaced with a solid backed color and a single letter. This replaces the previous approach of using a low res image and leading to a blurry icon.

Websites that provide larger icons will continue to function as before.

See James's notes about websites that have each above.

**Comment by LaurenWags** [comment]
Is this for favorites (previously top site tiles), bookmarks, or both?

**Comment by LaurenWags** [comment]
Verified https://github.com/brave/browser-ios/issues/1551#issuecomment-389622799 - if you add to favorites and then bookmark the site, both the favorite and the bookmark share the single letter on a colored background.

However, if you bookmark the site, then add it as a favorite, the favorite displays the fuzzy icon. In the image below, kpwags.com was added to favorites, then bookmarked. quora.com was bookmarked, then added to favorites:
![img_0184](https://user-images.githubusercontent.com/28145373/40137325-18899900-5918-11e8-8231-ce22b9396e56.PNG)

**Comment by LaurenWags** [comment]
Closing per discussion - opened https://github.com/brave/browser-ios/issues/1602 for the issue mentioned in https://github.com/brave/browser-ios/issues/1551#issuecomment-389625695
