### ISSUE TITLE
Private browsing modal is blocked by keyboard when switching to PB mode

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1556]
### Description:
Private browsing modal is blocked by keyboard when switching to PB mode

### Steps to Reproduce
  1. Clean install 1.6(18.04.30.15)
  2. Switch to PB mode
  3. After PB tab is opened, keyboard popsup covering the PB info modal

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/39448753-e06a4cee-4c93-11e8-83a8-a03e4bc13f05.png)
![image](https://user-images.githubusercontent.com/17010094/39448766-e6d54b10-4c93-11e8-88c6-1d3dd4169d1e.png)

**Expected result:**
Info modal should be over the keyboard even if its shown.

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**
1.6(18.04.30.15)

**Device details:**
All

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
@jhreis, I'm still seeing the keyboard appearing when I first initially launch PB. I remember the iOS team mentioning that the initial focus on the URL will be removed when a user first launched PB. However, the keyboard doesn't cover the two buttons anymore so it's a bit of an improvement. Was this expected or was the keyboard supposed to be removed? Example:

![img_9645](https://user-images.githubusercontent.com/2602313/40183178-26f932d6-59bb-11e8-9ec1-3c45d10b6317.PNG)

**Comment by srirambv** [comment]
This only happens when you open a private tab from tabs manager. Long press on tab manager and opening a new tab doesn't show the keyboard in PB mode. Also enabling PB mode only the modal shows up before closing the side wall.

![image](https://user-images.githubusercontent.com/17010094/40186414-0440425e-59c3-11e8-82df-963b539d1fec.png)

**Comment by kjozwiak** [comment]
@jhreis these are definitely not blockers but should eventually be addressed. Moving into the `1.6.1` milestone.

**Comment by jhreis** [comment]
Fixed per DDG branch and changes.
