### ISSUE TITLE
Update Browser Placement in Settings (under Quick-search Engine) 

### ISSUE THREAD

**Issue by ElissaBeth** [brave/browser-ios#156]
Update placement of the Quick-search engines in the settings screen. 

Move DuckDuckGo from lowest placement (on the bottom)
to the top choice (above Amazon.) 

While it is still early (still collecting data) early research suggests that
DDG is is used more than Amazon, Bing etc by Brave early adopters
(for regular searches.)

**Comment by garvankeeley** [comment]
DDG moved to first item in quick search, here is all the localized files that specify this for future reference:
	modified:   az/list.txt
	modified:   cy/list.txt
	modified:   de/list.txt
	modified:   en-GB/list.txt
	modified:   en/list.txt
	modified:   eo/list.txt
	modified:   es-ES/list.txt
	modified:   es-MX/list.txt
	modified:   fr/list.txt
	modified:   gd/list.txt
	modified:   hr/list.txt
	modified:   ml/list.txt
	modified:   pl/list.txt
	modified:   ta/list.txt
