### ISSUE TITLE
Add authentication to requests to local webserver

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-ios#1561]
requests to the local server (https://github.com/swisspol/GCDWebServer) should be rejected unless they are authenticated to be from the Brave app (versus other apps on the same device). 

Proposal:
1. iOS generates a secret token at startup; for instance a 32-byte random number
2. token is shared between GDCWebServer and the context that is making requests to GDCWebServer (not sure how this is actually done)
3. When the local server gets the request, it verifies that the token is correct. If so then it completes the request. If not then it returns 401.

**Comment by jhreis** [comment]
GCDWebServer has [hooks](https://github.com/swisspol/GCDWebServer#implementing-handlers) that should allow us to redirect/kill requests we no long want (e.g. `GCDWebServerMatchBlock`)
