### ISSUE TITLE
Brave crashes anytime links are opened in it from another app

### ISSUE THREAD

**Issue by taoeffect** [brave/browser-ios#1568]
### Description:

Brave crashes anytime links are opened in it from another app.

### Steps to Reproduce

1. Visit a tweet
2. Press and hold on the link (or click the share icon)
3. Open the link in Brave

**Actual result:**

Immediate crash.

**Expected result:**

For the link to open in Brave without crashing.

**Reproduces how often:** every single time.

**Brave Version:**

1.5.7 (18.05.01.09)

**Device details:**

iPhone SE (the one that looks like an iPhone 5 but is fast like an iPhone 6)

### Additional Information

I have Brave set to do "Private Browsing Only" and I have the following other settings enabled:

- Save Logins (don't know why this was enabled, I'm going to disable it now actually)
- Block Popups
- Private Browsing Only
- Block Ads & Tracking
- HTTPS Everywhere
- Block Phishing and Malware
- Fingerprint Protection
- Send crash reports and metrics (apparently these have been being ignored, since this problem has existed for the past several updates)

**Comment by jhreis** [comment]
What iOS version do you have on your phone? 
Do you happen to have multiple versions of Brave installed?

**Comment by kjozwiak** [comment]
I couldn't reproduce this with any of the devices that I have available :( Using all the settings that @taoeffect mentioned above, I went through the STR on the following devices:

* `1.5.7 (18.05.01.09)` using an `iPhone 6s` on `iOS 11.3.1` - Couldn't Reproduce
* `1.5.7 (18.05.01.09)` using an `iPhone 6s +` on `iOS 10.3.3` - Couldn't Reproduce
* `1.5.7 (18.05.01.09)` using an `iPad Mini 4` on `iOS 11.3.1` - Couldn't Reproduce

Hopefully once @taoeffect lets us know which iOS version he's using, maybe we can see if we can reproduce it via emulation using Xcode.

**Comment by taoeffect** [comment]
Wow, it magically works now. Maybe it was the iOS update that fixed it?

> What iOS version do you have on your phone?

11.3.1

> Do you happen to have multiple versions of Brave installed?

No. (How is that possible?)

I'm closing this issue since I can no longer reproduce it anymore, which again, is weird cause I could reliably reproduce it before.

**Comment by kjozwiak** [comment]
@taoeffect thanks for checking again! If you run into the issue again, please don't hesitate to re-open this issue or creating a new one!

Thanks again for filing the issue 👍

**Comment by jhreis** [comment]
@taoeffect The main way someone would have two versions installed is if they had downloaded the source code and compiled it onto their device. 

App launching like we do often has some peculiar behavior on Apple's side. It most likely fixed itself after a device reset, but hard to know.

Regardless, to mirror @kjozwiak sentiment, thanks for taking the time to file this.
