### ISSUE TITLE
Privacy Policy and ToS in app instead of website

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#157]
From a friend: 
>  Privacy Policy and Terms of Use under settings should be static text rather than loading it from the Brave website which includes Brave's navigation hamburger menu. Loading it from the website has a bit of a delay and isn't really snappy. Not sure what the win is if it's loaded from the web.

![issue1](https://cloud.githubusercontent.com/assets/831718/13546033/775372b2-e26e-11e5-9c23-65df63a951bd.PNG)

![issue2](https://cloud.githubusercontent.com/assets/831718/13546034/8215661a-e26e-11e5-8ff5-6c9486cf00df.PNG)

**Comment by garvankeeley** [comment]
Loading from the web is OK IMHO, but ideally the page should be formatted for planing-text-only viewing, not with headers and footers.

**Comment by garvankeeley** [comment]
The formatting is better now for in-app viewing, closing
