### ISSUE TITLE
Google Search Referral Links Don't Work

### ISSUE THREAD

**Issue by GarrettS** [brave/browser-ios#1580]
### Steps to Reproduce

  1. Search Google for: insurance calls
  2a. Click the linked phone number under the ad
  2b. Click the ad link text

**Actual result:**
Blank screen 

**Expected result:**
2a. Dialog: "Call (800) ddd-dddd
2b. Redirect to page

**Device details:**
Version 1.5.7 (18.05.01.09)
Device iPhone 7 Plus (iOS 11.2.6)

**Website problems only:**
- did you check with Brave Shields down?
No.

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 
No.

- did you check in Safari/Firefox (WkWebView-based browsers)? 
Yes. It works in Safari on iOS

![image](https://user-images.githubusercontent.com/56098/39872256-41c12ece-541c-11e8-9588-862900c49a69.png)

**Comment by srirambv** [comment]
Verified on 1.6.4 ((18.08.10.17) on iPad running iOS 11.3
* Google results show up as text can't click to bring call popup 
* Visited dominos.ca and phone shows up as link, clicking on it brings up 
![image](https://user-images.githubusercontent.com/17010094/44038301-80a7ccfc-9ee4-11e8-8ad2-f024a045d7c9.png)
* Clicking it brings up `Call number ` modal 
* Click call switches to Phone App
