### ISSUE TITLE
The "Share" modal window will disappear after several seconds.

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#159]
Posting for a friend:

> Sometimes when you try sharing a website via "Twitter", the "Share" modal window will disappear after several seconds.. This doesn't happen very often. I'm assuming it's because the API attempts to load the "preview" image and when it can't, it quickly closes.. I could be wrong though...
> 
> STR: https://youtu.be/BSOuQL7etbU
> - load the following website --> http://www.zerohedge.com/news/2016-03-01/congratulations-prominent-anti-hft-critic-eric-hunsader-winning-750000-whisteblower-
> - Click on "Share" and then select the "Twitter" icon
> - The "share" Twitter modal window will appea
> - Leave it opened for a 5-10 seconds and it will quickly disappear

**Comment by garvankeeley** [comment]
I can't repro -yet- but I agree that it would be due to the preview image
