### ISSUE TITLE
Enable All Regional Blocklists by Default

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#1596]
Android has been doing this since last release without issue. iOS should do the same. We currently are already auto-enabled for: `["ru", "uk", "be", "hi", "sv"]`, but should just expand this globally.

See Adblock.swift for implementation.

**Comment by Jacalz** [comment]
When ad-block version 4 gets released and updated, we will get way better Swedish regional adblocking thanks to a commit I did 👍 The new filter list is way better maintained and should block ads a lot better 💪
