### ISSUE TITLE
fuzzy favicon displayed on Favorite tile if site is bookmarked first

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1602]
### Description:
Originally reported in https://github.com/brave/browser-ios/issues/1551#issuecomment-389625695 - if you bookmark a site with a small icon (quora.com, kpwags.com, etc) and then add the site to Favorites (formerly top site tiles), the favicon will be fuzzy. It should be a single letter on a solid background as described in #1551.

### Steps to Reproduce

  1. Navigate to a site like quora.com
  2. Bookmark the site.
  3. Now go to the share menu and add the site to favorites.
  4. Open a new tab.

**Actual result:**
Quora favicon is fuzzy.
![img_0184](https://user-images.githubusercontent.com/28145373/40139274-5cda7e44-591d-11e8-9139-0b1198056501.PNG)

**Expected result:**
It should be a single letter on a solid background like the K in the screenshot above.

**Reproduces how often:** [Easily reproduced/Intermittent issue]
easily

**Brave Version:**

1.6 (18.05.16.13)

**Device details:**

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
If you add to favorites, and then bookmark the site, you get the single letter on a solid background as the favicon.

cc @jamesmudgett @jhreis

**Comment by LaurenWags** [comment]
Reproduced issue using STR with version 1.6.2 (18.06.20.18).

**Comment by LaurenWags** [comment]
Closed, working in 1.6.3 (18.06.28.18) on iOS10.

**Comment by LaurenWags** [comment]
appears to be resolved, but once you change orientation the fuzzy icon comes back. reproduced by @srirambv

**Comment by iccub** [comment]
We are actually changing favicon logic here. If the favicon is too small, a fallback icon will be provided, this will mirror the top sites tiles behavior.
So bookmarks and topsites should show the same icon, be it fallback image or high-res favicon.
The newest test build should have this logic included already

**Comment by LaurenWags** [comment]
I tried STR from description on 1.6.3 (18.07.18.11) and I'm still seeing the issue as described.
