### ISSUE TITLE
Third-party keyboard not useable

### ISSUE THREAD

**Issue by midi** [brave/browser-ios#161]
I can't seem to use Fleksy in Brave. Instead it pops up the stock keyboard, with no option to change it to Fleksy.
Using 1.1 from the App Store.

Can use Fleksy with Safari just fine.
Remember seeing the same behavior in older Firefox versions.

**Comment by keithah** [comment]
Can't use any 3rd party keyboard with Brave.

**Comment by garvankeeley** [comment]
I think firefox iOS has fixes for this, will try to pull those in

**Comment by garvankeeley** [comment]
I have merged the fx ios code for this in, now i need to find the time to wire it up for Brave

**Comment by srirambv** [comment]
Fleksy keyboard works on the latest build. Closing the issue as third-party keyboards are now supported.
