### ISSUE TITLE
iPhone X crashes after enabling Browser Lock feature

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1610]
### Description:
Reported via community: https://community.brave.com/t/bug-crashes-on-iphone-x-with-browser-lock/22385

Enabling Browser Lock on an iPhone X causes Brave to crash. Consequently, each time you go to open Brave it will crash again, rendering Brave useless until you delete and re-install.

### Steps to Reproduce

  1. Using iPhone X enable Browser Lock Feature.
  2. Try to unlock Brave.
  3.

**Actual result:**
Brave Crashes.

**Expected result:**
Brave should not crash.

**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**
1.6

**Device details:**
 iPhone X

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Reproduced by @kylehickinson

**Comment by kjozwiak** [comment]
Unfortunately QA doesn't own an iPhone X but both @mrose17 & @davidtemkin verified that this has been fixed and isn't crashing Brave anymore.
