### ISSUE TITLE
Separate US English and UK English

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-ios#1619]
### Description:
Like Brave for desktop, Brave for iOS should have separate localizations for American English and British English. It's a little confusing to see the two dialects mixed:

"Favorite" (UI):
![](https://user-images.githubusercontent.com/19424103/40561686-ab369ba6-6023-11e8-8217-41e7dc9c078e.png)
"Favourite" (App Store What's New):
![](https://user-images.githubusercontent.com/19424103/40561615-7b0209ac-6023-11e8-8868-3eb9a9ece9d7.png)

**Comment by eljuno** [comment]
Should this be done in localization? I'm not see en_UK language projects on Transifex.

**Comment by Liunkae** [comment]
@eljuno Good idea, I just requested English (UK) on Transifex. However, this issue also includes the App Store text, which is not on Transifex.

**Comment by jhreis** [comment]
We currently do not translate "what's new" for any language (too much overhead right now). However, we would be open to translating the app store listing with a UK English.

**Comment by Liunkae** [comment]
Closing because this project is deprecated. New issues should go in the new project: https://github.com/brave/brave-ios/issues
