### ISSUE TITLE
Rendering issue with 12factor.net

### ISSUE THREAD

**Issue by toneplex** [brave/browser-ios#162]
The home page loads great, but each subsequent page, eg. http://12factor.net/dependencies only loads the top part of the page.  This affects version 1.1 (16.02.27.02)

**Comment by garvankeeley** [comment]
Getting lots of reports of this happening on various pages. If I shut off HTTPS Everywhere it doesn't seem to happen, so https redirection is having a bizarre side effect during first page load

**Comment by garvankeeley** [comment]
see also https://github.com/brave/browser-ios/issues/142

**Comment by toneplex** [comment]
You are correct.  Turning off HTTPS Everywhere, fixed it.

**Comment by garvankeeley** [comment]
Dev note on this: overriding the default behaviour for NSURLProtocol canonicalRequestForRequest() is the culprit. I am clearly doing things here that are causing wierd bugs in UIWebView loading. This function has caused me no end of headaches, I am going to take a different approach, there is other ways to redirect HTTP to HTTPS urls.
