### ISSUE TITLE
target=_blank links opens up in the same tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1632]
### Description:
target=_blank links opens up in the same tab

### Steps to Reproduce

**Case 1:**
  1. Visit https://brianbondy.com, click on Twitter icon, twitter page loads in the same tab

**Case 2:**
  1. Open Gmail and click on any link in a email, opens in same tab 

**Case 3:**
  1. Open news.google.com and click on any listed article, opens in same tab 

**Actual result:**

target=_blank links opens up in the same tab

**Expected result:**

target=_blank links should open in a new tab from the parent tab 

**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**
1.6.1(18.05.29.15)

**Device details:**
iPhone

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
https://news.google.com/ doesn't open link in a new tab either on iPad or iPhone but the same  opens up a new tab on Desktop 

Issue reproduced on all devices running iOS 10 and iOS 11

**Comment by srirambv** [comment]
On iOS 11, with a clean install clicking on twitter link in https://brianbondy.com/ opens up the link in a new tab but after couple of attempts it starts loading in the same tab.

**Comment by jhreis** [comment]
Closing per: https://github.com/brave/browser-ios/issues/1511
