### ISSUE TITLE
Update Favicon Fallback Logic

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-ios#1634]
Too many fallback icons are defaulting to Grey because they are likely returning white or lighter theme colors.

In order to more closely match desktop remove logic that defaults color to Gray when returned theme color `isLight`. Instead we should have text change from white to BraveUX.GreyH. 

Thanks!

**Comment by iccub** [comment]
Any examples of sites with light color fallbacks?

**Comment by srirambv** [comment]
@jamesmudgett any QA steps for this issue?
