### ISSUE TITLE
HTTPSE: Login modal not appearing for MLS Live Fantasy website

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#165]
Posted for a friend:

The MLS Live Fantasy website doesn't seem to be working correctly. I can't get the "Login" modal window to appear when taping on "Start Playing". This is also affecting Chrome but works fine within Firefox. I've attached a short video to demonstrate the issue:

https://youtu.be/xvBIbvcd4Rw

**Comment by garvankeeley** [comment]
I had to go shields down. I'll toggle the settings for AB/TP/HTTPSE and see which one is the cause, and I'll check this on android and see what happens there.

**Comment by garvankeeley** [comment]
HTTPSE is the cause, haven't looked further just yet

**Comment by garvankeeley** [comment]
Fixed in upcoming 1.2 release (not sure which commit, was rechecking bugs and found this fixed)
