### ISSUE TITLE
sometimes Pin modal doesn't display when entering Private Browsing for the first time

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1658]
### Description:
Found while testing https://github.com/brave/browser-ios/issues/1649, if I follow the STR in that issue, when I go to Private Browsing for the first time, I am not notified about the ability to set a pin.

### Steps to Reproduce

  1. Clean install of 1.6.3 (18.06.28.16)
  2. Navigate to settings
  3. Set search engine for Private tabs to DDG
  4. Open a Private tab

**Actual result:**
No modals appear. 

**Expected result:**
I would expect the one about a pin to display, but not the one for DDG.

**Reproduces how often:** [Easily reproduced/Intermittent issue]
easily

**Brave Version:**
1.6.3 (18.06.28.16)

**Device details:**
iPad iOS10

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc @srirambv @kjozwiak

**Comment by srirambv** [comment]
Doesn't show up on iOS 11 as well. If the default search engine isn't changed in settings before loading a private tab, the modal shows up after the DDG modal is dismissed. So looks like its should be independently shown irrespective of DDG modal is shown or not
