### ISSUE TITLE
HTTPSE: Delta.com not loading

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-ios#166]
A few issues with this site

1. Have trouble getting ONLY the main page www.delta.com to load with shields up.  Loads fine with shields down.  But if loading to a different branch of the main site (ie. www.delta.com/air-shopping/searchflights.action) from a google search, that page will load fine.

2.  When trying to search flights, the to/from airports won't recognize or change to the proper airport code with shields up so you can't complete a search at all unless you already know the airport code.  With shields down, the site automatically adjusts the airport code and you can complete the search.

The site works fine on the desktop browser.

**Comment by garvankeeley** [comment]
Confirmed this is HTTPS-E causing this

**Comment by garvankeeley** [comment]
This auto-updates in the app, and I confirmed delta.com loads ok now
