### ISSUE TITLE
Update ad block to 4.x

### ISSUE THREAD

**Issue by iccub** [brave/browser-ios#1664]
https://github.com/brave/ad-block

Test plan:
Test against popular websites to see if it's blocking ads correctly.
Testing non-english regional filter ads would be nice too, compare old and new builds in terms of blocking quality.

**Comment by iccub** [comment]
I tested Polish regional filters and looks good to me.

Results, left screen: shields on, right screen: shields off(ad visible)

<img width="1010" alt="zrzut ekranu 2018-07-27 o 22 06 16" src="https://user-images.githubusercontent.com/6950387/43344252-5f6c1e24-91e9-11e8-83e2-70c86b8478cb.png">

**Comment by kjozwiak** [comment]
Thanks @iccub! QA also went through the following cases:

- [ ] ad-blocking is correctly working on several of the most popular web pages
- [ ] brave stats are correctly being logged under `about:newtab`
 - [ ] ensure that ad-blocking still works correctly after restarting the app several times (Example: visit a few sites and ensure ad-blocking is working, restart and visit a few more websites and ensure ad-blocking is working.. Repeat 3-4 times)
 - [ ] restarting the application several times doesn't clear the current brave stats
 - [ ] ensure that there's no crashes during startup
 - [ ] ensure that the session isn't being lost when restarting several times (including active tab)

The manual passes can be found here:

* https://github.com/brave/browser-ios/issues/1690
* https://github.com/brave/browser-ios/issues/1689
* https://github.com/brave/browser-ios/issues/1688
* https://github.com/brave/browser-ios/issues/1687
