### ISSUE TITLE
Replace private tab icon with updated glasses

### ISSUE THREAD

**Issue by rossmoody** [brave/browser-ios#1679]
Swap in the updated version of the sunglasses icon in private tabs.

**Comment by kjozwiak** [comment]
Old icon that's being replaced:

![img_9689](https://user-images.githubusercontent.com/2602313/43024974-012371ec-8c3e-11e8-9147-f690c2459112.PNG)

New icon that should be used instead:

![img_9690](https://user-images.githubusercontent.com/2602313/43024993-11d6843e-8c3e-11e8-9e82-354c9b822dea.PNG)
