### ISSUE TITLE
Cookie warnings all the time now

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#168]
This sounds like a bug somewhere because blocking third party cookies should rarely cause problems.

Posting for a friend:

Ran into this when I was browsing articles from Sky Sports... I keep getting the "Cookie Warnings" all the time right now.

![img_0631](https://cloud.githubusercontent.com/assets/831718/13724760/5fe97cb2-e85d-11e5-8b15-de3da582f1a1.jpg)

http://www.skysports.com/football

**Comment by garvankeeley** [comment]
Thanks for the report but I can't repro this with that link. My cookie setting is the default: block 3rd party

**Comment by garvankeeley** [comment]
I have been on the lookout for this and can't repro, re-open if STR or it is still happening
