### ISSUE TITLE
URL bar getting messed up with lots of tabs

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#169]
Posting for a friend:
Also noticed that when I opened around 15 different tabs, things started going wonky... take a look at the screenshots. If you look at the top, you can see the website being cut off and a very small fraction of the Brave's URL bar is also showing... These steps are not 100% to reproduce, but this is the use case I was going through when I ran into this:

- visit http://www.skysports.com/football
- Click on "News" and open around 15-20 different tabs
- Brave will start slowing down and get a little janky
- Switch between a few tabs and you'll notice that the top is starting to get cut off etc... (attached screenshots)

![img_0643](https://cloud.githubusercontent.com/assets/831718/13724772/9ebe5714-e85d-11e5-9a5c-687695797151.PNG)

**Comment by garvankeeley** [comment]
I have also seen this, and been looking for how to reproduce, I'll try these steps and see. 
(bug is in BraveScrollController.swift, just not sure where yet)

**Comment by garvankeeley** [comment]
99% sure this is fixed by 701cbfb1e3f788122009b198edaaf5767567d4dc
It is in the 1.2 release which should be out in a week
