### ISSUE TITLE
Frequent crashes (news sites mostly)

### ISSUE THREAD

**Issue by davidblanar** [brave/browser-ios#1707]
Have you searched for similar issues on the repository?
Yes

### Description:

After the latest update (version 1.6.3), the browser crashes after a couple dozen seconds of clicking through news sites (mostly Czech and Slovak ones). The crashes sometimes happen after clicking a link, sometimes after scrolling, sometimes "out of the blue" (just reading, not scrolling or clicking). It didn't use to happen on those sites at all. The browser closes and when re-launched, the previous tabs open and it works again for a couple seconds/minutes until the next crash.

**Note:** does not seem to happen when browsing privately. Also, it only started after updating to the latest version (as of right now).
### Steps to Reproduce

  1. Open for example [this Czech news site](https://www.idnes.cz/)
  2. Open a few tabs, scroll, click on a different article, close it, go to the comments section, etc.

**Actual result:**

The browser crashes after several seconds to several minutes

**Expected result:**
Should not crash.

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Every few seconds to every few minutes of browsing.

**Brave Version:**

Version 1.6.3 (18.07.27.16)

**Device details:**

Iphone SE, iOS 11.4.1

**Website problems only:**
- did you check with Brave Shields down?
No, will check tomorrow.
- did you check in Puffin/Dolphin (UIWebView-based browsers)? 
No.
- did you check in Safari/Firefox (WkWebView-based browsers)? 
No.

### Additional Information

If I can provide any more useful info, please let me know. Thanks.

**Comment by iccub** [comment]
We fixed it and it should be all good in the next release. Sorry for that.

There's more info https://github.com/brave/browser-ios/issues/1695. Closing this one but feel free to comment, especially if the problem still persists for you after new release.

**Comment by davidblanar** [comment]
Everything works perfectly now. Just wanted to say thanks!

**Comment by iccub** [comment]
Glad it works for you. Yes the crashes happen only sometimes, but anyway, the new version should fix them completely. Thanks for using Brave browser :)

**Comment by jhreis** [comment]
@davidblanar Great to hear! And thanks for taking the time to report this on GitHub!
