### ISSUE TITLE
Security indicators for mixed passive content [hackerone]

### ISSUE THREAD

**Issue by jumde** [brave/browser-ios#1711]
https://hackerone.com/bugs?report_id=397271

**Comment by tomlowenthal** [comment]
[I'm coopting this issue and making it more expansive.] 

Now we also have https://hackerone.com/reports/402488

We should ensure that we provide the right security indicators for all the HTTPS edge cases. If we've missed two, there may be a bunch of others we fumbled. We should use badssl.com to check for as many edge cases as possible.

**Comment by diracdeltas** [comment]
Discussed in security review; we would like this prioritized for next release.

**Comment by diracdeltas** [comment]
can this be closed?
