### ISSUE TITLE
Tab count for private mode is wrong

### ISSUE THREAD

**Issue by iccub** [brave/browser-ios#1713]
STR:
- open 2 tabs in normal mode
- switch to private browsing
- open a tab

tab counter shows 3, should show 1 only for private browsing tabs
if you go back to normal mode it still shows 3 tabs

This probably needs to be fixed after private browsing mode is fully implemented.

**Comment by jhreis** [comment]
Meant for brave-ios (https://github.com/brave/brave-ios/issues/180)
