### ISSUE TITLE
Layout issues on new notch iPhone models

### ISSUE THREAD

**Issue by iccub** [brave/browser-ios#1744]
Bottom toolbar placement is wrong, and possibly other ui elements too.

<img width="498" alt="zrzut ekranu 2018-10-1 o 13 45 00" src="https://user-images.githubusercontent.com/6950387/46286669-3d50ee80-c580-11e8-8b76-26e4834a9960.png">

**Comment by srirambv** [comment]
@anthonypkeane confirmed works fine on iPhone XS. Marking as QA Pass
