### ISSUE TITLE
Adding devices to sync chain doesn't get listed immediately 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1769]
### Description:
Adding devices to sync chain doesn't get listed immediately 
### Steps to Reproduce

  1. Enable sync on iOS and keep the sync screen active
  2. Add a second device, doesn't list no matter how long you stay on the screen
  3. Go back to settings and open sync setting again, second device from step 2 is listed

**Actual result:**
Adding devices to sync chain doesn't get listed immediately 

**Expected result:**
Should list (even after delay). user should not navigate back and forth to see the devices list

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy

**Brave Version:**

Sync build

**Device details:**

iPhone 7s + (iOS 12)

### Additional Information

cc: @brave/legacy_qa

**Comment by iccub** [comment]
This will get fixed here https://github.com/brave/browser-ios/pull/1765
