### ISSUE TITLE
update to 1.6.6 wipes out data

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1803]
### Description:
Updating from 1.6.5 (app store version) to 1.6.6 via provided IPA file wipes out:
- Favorites
- Bookmarks
- History
- Session (opened tabs)

The follow appear to be retained:
- Stats
- Settings (specifically checked default search engine)
- Passwords

### Steps to Reproduce

  1. Download 1.6.5 from app store
  2. Add bookmarks, history, tabs, stats, cookies, logins/passwords, site specific shield settings, custom sites to ‘favorites/top site tiles’, set default search engine to DDG
  3. Use IPA file to update to 1.6.6

**Actual result:**
Be sad when your hard work is wiped out
![image from ios](https://user-images.githubusercontent.com/28145373/48371245-5b366680-e689-11e8-85b6-2cbdb9f4fba0.png)

**Expected result:**
All data should be retained

**Reproduces how often:** [Easily reproduced/Intermittent issue]
easily

**Brave Version:**
1.6.5 -> 1.6.6 update

**Device details:**
reproduced on devices running iOS 10, 11, 12

**Website problems only:**
- did you check with Brave Shields down? n/a

- did you check in Puffin/Dolphin (UIWebView-based browsers)? n/a

- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### Additional Information
Reproduced by @kjozwiak @srirambv 

@srirambv also mentioned seeing a 'cleaning' message when updating on iOS12. I did not see this on iOS11. 

![screen shot 2018-11-12 at 2 49 19 pm](https://user-images.githubusercontent.com/28145373/48371548-2bd42980-e68a-11e8-8b46-3d489e5a2e20.png)

**Comment by jhreis** [comment]
We have reverted much of 1.6.6, so this should not be an issue anymore.
