### ISSUE TITLE
German Translation not complete

### ISSUE THREAD

**Issue by kmichl** [brave/browser-ios#1813]
Hey,

I noticed, that the german Translation in the new tabs is not complete.

xx s Est. Time Saved --> Geschätzte Zeit gespart
Anzeigen und Trackers --> Anzeigen und Tracker (does not need the s in the end for plural in german)

![img_0718](https://user-images.githubusercontent.com/10185839/50079666-7c3f2980-01ea-11e9-81a9-b2f19c5b6fb4.jpg)

**Comment by Liunkae** [comment]
Translations for the iOS app can be changed here: https://www.transifex.com/brave

**Comment by kmichl** [comment]
Thank you for the information.
