### ISSUE TITLE
Brave Bookmark on IOS 

### ISSUE THREAD

**Issue by Anbuwestside** [brave/browser-ios#1816]
### Steps to Reproduce

  1. Add a sign in function on Brave Desktop 
  2. Add a sign in function on Brave IOS 
  3. Just sign in to sync settings, bookmarks from Desktop to IOS

**Actual result:**

**Expected result:**

**Reproduces how often:** [Easily reproduced/Intermittent issue]

**Brave Version:**

**Device details:**

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
This is a deprecated repo. Sync for iOS is in works and would be supported in future. There wont be any sign-in feature for Sync. For any iOS issue please use the new repo which https://github.com/brave/brave-ios/issues/
