### ISSUE TITLE
1Pwd activity panel leaves gray overlay?

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#182]
Posted for a friend:

When tapping on the "Sign in with 1Password", you'll get the "Activity" panel so you can select that action should happen. Once you've hit "Done" under the "Activity" panel without selecting an action, the content area of the browser will stay gray. This makes it seem like the browser is "not responding" as a gray screen usually indicates some type of issue with the application.

https://youtu.be/k4TM-mpHOlo

**Comment by garvankeeley** [comment]
Fixed by https://github.com/brave/browser-ios/commit/725cb0fab47a9420727b2d8309e31ffbfd465433, i hope
