### ISSUE TITLE
Sometimes Brave displays two "Sign in with 1Password" messages on the same page.

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#183]
Posted for a friend:

Sometimes Brave displays two "Sign in with 1Password" messages on the same page. This happens pretty often on several webpages that I've visited. I've attached multiPasses.PNG to demonstrate the issue.

STR:
- Open Brave
- Visit http://www.zerohedge.com
- Once the website loads, you should see a single "Sign in with 1Password"
- On the right hand side, click on the ZeroHedge logo and select "Open in Background"
- now that you have two of the same pages opened, refresh one of the pages and you'll notice that two "Sign in with 1Password" are being displayed

**Comment by bbondy** [comment]
![multipasses](https://cloud.githubusercontent.com/assets/831718/14270796/b968e6c8-fabf-11e5-8536-3290ebec1a0e.PNG)

**Comment by garvankeeley** [comment]
During logic cleanup, such as b589ea43e7b7dbb3a8e9ce9098d89057bb11f05a this should have been fixed. I only tried to repro with the latest code so I never did see this happen, can you try with today's build (just making one now)?

**Comment by garvankeeley** [comment]
Just got it to happen.
