### ISSUE TITLE
Can't dismiss sign in with 1Pwd

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#184]
Posted for a friend: 

There's doesn't seem to be a way to dismiss the "Sign in with 1Password" messages that are appearing on the bottom of the pages. Users should be able to dismiss the message if they don't wish to use 1Password.

I think it would be a really good idea to add the option of disabling the 1Password integration through the settings like HTTPS Everywhere.

**Comment by garvankeeley** [comment]
db1d6f601fc2db158093174a5fb532ca82ac0129
This has close button and session persistence. There is also some support in that commit for persisting in the DB which sites the popup should not be shown on, however, I am not sure how the UI should work for that so I am holding off.

I'll look now at some additional settings for disabling this integration.
