### ISSUE TITLE
Malware and Phishing protection

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#186]
Malware and Phishing protection support is now also available as a common resource.
It uses the same code as Adblock but you need a second instance of the library.

It is largely the same as adblock code with he only difference that top level URLs must also be checked (in laptop at least we always allow top level frames).

Reference implementation
https://github.com/brave/browser-laptop/commit/a6baa8df095112956dac6e97f31ae0ccbd364ca5
https://github.com/brave/browser-laptop/commit/4746ae385a75edd0b1517c5918af938dc4120810

In laptop we also show a click through page when such a page is hit:
https://github.com/brave/browser-laptop/commit/82445d66f378369177e87c97e9ab91eab74a3023

The data files are uploaded here.
https://s3.amazonaws.com/safe-browsing-data/{version}/SafeBrowsingData.dat
Where `{version}` is 1 currently.

**How it looks on laptop:**

Click through page:
<img width="704" alt="screenshot 2016-04-06 23 03 44" src="https://cloud.githubusercontent.com/assets/831718/14352172/33cebca2-fca1-11e5-8fef-651f071a89a4.png">

Bottom menu  item:
<img width="617" alt="screenshot 2016-04-06 13 43 19" src="https://cloud.githubusercontent.com/assets/831718/14352183/3c60cf0e-fca1-11e5-8ceb-c307cbd575f9.png">

**Comment by garvankeeley** [comment]
Awesome! I'll try get it in beta builds for early next week

**Comment by weems** [comment]
I'm curious as to where we get the data to block phishing and mallard.

**Comment by garvankeeley** [comment]
first work here: 211ab0f61e7d4bfcea640611689f05883c9e05d9

**Comment by garvankeeley** [comment]
@weems the lists are mentioned in this comment
https://github.com/brave/browser-laptop/issues/226#issuecomment-198577129

**Comment by garvankeeley** [comment]
@bbondy I searched the laptop source for all images and didn't see the caution icon used here, do you happen to know the source?

**Comment by bbondy** [comment]
yep that's because it's SVG, see here:
https://github.com/brave/browser-laptop/blob/b42f007219c885afc69fb8a20381ecd5bc0914eb/js/about/certerror.js#L48

**Comment by garvankeeley** [comment]
closed by b46ed1f4bd73efa1c78e29406bae01c1958241af
