### ISSUE TITLE
Private tab restoring

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#189]
Posting for a friend:

Whenever you close Brave while having several tabs opened in Private Mode, reopening Brave will load the same amount of tabs that were opened in PM but they'll be blank. Refreshing those tabs won't do anything. With this bug, someone that access to the phone might figure out someone was using PM if there's several blank tabs that can't be refreshed.

* Go into Private Mode and load several tabs
* close Brave while in Private Mode with all those tabs still opened
* load Brave once again and you'll notice that the tabs that were closed via PM are opened but are completely blank

**Comment by bbondy** [comment]
![img_0795](https://cloud.githubusercontent.com/assets/831718/14461503/e66dd242-0090-11e6-8a5b-69da150bcf46.jpg)

**Comment by garvankeeley** [comment]
Note, fix this when looking at #194
