### ISSUE TITLE
mailto: links updating urlbar

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#190]
Posting for a friend:

When pressing a mailto: button and then selecting "Cancel" on the modal window that's displayed, the mailto: url will appear under the URL bar until you either refresh the page or navigate to a different page. When a user selects cancel, the URL should be restored to the current one that's being used.

STR:

* open http://www.leasidetowers.com/ in Brave
* once opened, select the green email button at the top of the page
* you'll get a modal popup that will say "Opening mailto:leasidetowers@morguard.com"
* click on "Cancel"

You'll notice that "mailto:leasidetowers@morguard.com" is appearing under the URL bar now rather than the actual URL.

![img_0797](https://cloud.githubusercontent.com/assets/831718/14461539/0ba1e2b0-0091-11e6-845e-1a8c815e22f7.jpg)

---

Side note, I think we have this same bug in laptop

**Comment by benmosher** [comment]
I just saw something similar when clicking a link that opened the Twitter app from the issue I just opened: https://github.com/brave/browser-ios/issues/204

When I came back to Brave app to copy the issue link, I got the tweet URL instead as it was the active URL bar content.

Thus, I suspect this issue could be generalized to all URLs that open external applications, not just mailto.
