### ISSUE TITLE
Yahoo context menu bugs

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#191]
STR from a bug reporter:

iPhone 6+: 
1. Go to Yahoo.com 
2. Scroll down past the top article to one of the articles listed below 
3. Tap and hold down on a link 
4. Menu pops up above the webpage displaying options such as open, open in a new tab, etc... 
5. Before I choose an option in the menu the webpage loads behind it, which doesn't allow me to open in a new tab

iPad Mini (Original):
1. Go to Yahoo.com 
2. Scroll pass the top articles, to one of the articles listed below 
3. Tap and hold on a link to a different article 
4. Menu appears above the webpage providing only one section that is blank. This makes it hard to copy the link or open in a different tab

**Comment by srirambv** [comment]
Possibly similar to #1111. Not able to reproduce on the latest build. @LaurenWags @kjozwiak can you verify this on iPad

**Comment by LaurenWags** [comment]
unable to reproduce on iPad (10.3.1) using Brave 1.4.1 (17.08.24.18)
