### ISSUE TITLE
Where is Find in page

### ISSUE THREAD

**Issue by olimay** [brave/browser-ios#192]
Does Brave on iOS already have a 'Find in page' function? If not, that would be great to have. I used it a fair amount on my iPhone in Safari and Chrome.

Chrome on iOS implements this via a menu item, which is pretty good. Safari offers it as an option after you type text in the address bar, which is a bit more annoying. I can't find the operation in Firefox on iOS.

**Comment by garvankeeley** [comment]
It is in the "Share Menu". Not a fan of this, but perhaps if we mentioned it in the onboarding screens it wouldn't seem quite so hidden

**Comment by garvankeeley** [comment]
@bradleyrichter another item for the onboarding screens

**Comment by jamesmudgett** [comment]
Find in page added to the address bar search.

**Comment by srirambv** [comment]
Closing #192 as the feature is available now
