### ISSUE TITLE
Copying gifs only copies a still frame

### ISSUE THREAD

**Issue by davidcelis** [brave/browser-ios#196]
I haven't done enough testing to know how big of an issue this is or if it's just an issue with this particular website, but if you visit giphy.com and try to copy a GIF to your clipboard to paste into iMessage, what ends up copied (and later pasted) is just a still image as opposed to the full animated image. This same functionality works in Safari and Chrome

**Comment by garvankeeley** [comment]
Firefox iOS has a fix for this, just need to merge it in.

**Comment by garvankeeley** [comment]
Fixed in https://github.com/brave/browser-ios/commit/172e87286f672346e5e2e4b426490242fd51b005
