### ISSUE TITLE
Feature request: reload button

### ISSUE THREAD

**Issue by SeAlgoAsoma** [brave/browser-ios#199]
C'mon, guys, I've never seen a browser without a reload button.

**Comment by garvankeeley** [comment]
We have pull-to-reload, but what i don't like about the current implementation is that it requires the page to be scrolled to top. We should probably switch to a button.

**Comment by bradleyrichter** [comment]
Chrome for iOS doesn't have a reload button unless you open the menu. But I'm not against it if there is enough demand and we can afford the space.

**Comment by SeAlgoAsoma** [comment]
At the time I posted this, I wasn't aware there was pull-to-reload. For me personally, that's good enough, but a button would be nicer if more people want it.

**Comment by bradleyrichter** [comment]
Plan is to add the reload button on the inside right end of the URL box...

**Comment by garvankeeley** [comment]
Is fixed
