### ISSUE TITLE
Long press on mailto: bad url content

### ISSUE THREAD

**Issue by benmosher** [brave/browser-ios#204]
Long press on mailto concatenates host name with href. 

Discovered on http://mathmovesu.com/mobile-terms-conditions

Long press on the jennifer_k_chan@raytheon.com link pops an action sheet with

http://mathmovesu.commailto:jennifer_k_chan@raytheon.com

as the link href. 

For flavor, see https://twitter.com/benmosher/status/724221325921808384 where I initially blame the MathMovesU web team for the malformed link. 😳

Also, FWIW, the analogous long press action sheet in Safari just shows the email address, sans `mailto:` which might be ideal behavior if the likely user action is to copy the address and paste it into email client of choice.

**Comment by garvankeeley** [comment]
fixed by https://github.com/brave/browser-ios/commit/d4c54c748d8176d4f8314af3bc04b96db752f3e5
