### ISSUE TITLE
'Always load in private mode' feature

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#205]
I think this would appeal to some, for those who don't want to switch from Safari, they might use Brave as a private-mode-only browser.

**Comment by bbondy** [comment]
I was thinking like a reversed mode for OS X, where the private tab menus etc change to non private tab, and everything is private by default.

**Comment by pwnsdx** [comment]
Am I the only to think that this feature should be the highest priority for a privacy-oriented browser?

**Comment by garvankeeley** [comment]
Reminder since I was just looking at related code, this is the call to use on startup after checking the setting:
```
getApp().browserViewController.switchToPrivacyMode(isPrivate: whateverTheSettingIs)
```

**Comment by pwnsdx** [comment]
Thanks!!! :D
