### ISSUE TITLE
Instagram load more button not working

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#208]
Posting for  a friend:

It looks like the "load more" button in Instagram isn't working.. Clicking on "load more" never loads other images as it should..

STR:

- load https://www.instagram.com/FloydMayweather/ in Brave
- click on "load more"
- nothing happens

**Comment by garvankeeley** [comment]
thanks, will need to check it on another UIWebView app

**Comment by garvankeeley** [comment]
Seems to working ok on 1.2.4
