### ISSUE TITLE
Slashdot Desktop Site note loading

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#209]
Posting for a friend:

It appears that clicking on "Desktop Site" under slashdot isn't loading the desktop version and still reloads the mobile version of the website:

STR:

- load slashdot.com in Brave which should load the mobile version
- scroll to the bottom of the website and tap on "Deaktop Site"
- rather than the desktop site being loaded, the mobile version keeps loading

**Comment by garvankeeley** [comment]
thanks, will need to check it on another UIWebView app

**Comment by garvankeeley** [comment]
Fixed on 1.2.4 for me
