### ISSUE TITLE
Not enable 3rd. Party keyboard.

### ISSUE THREAD

**Issue by Chamiu** [brave/browser-ios#210]
Not enable 3rd. Party keyboard.
I tried [ATOK](https://itunes.apple.com/jp/app/atok-ri-ben-yu-ru-likibodo/id893918621?mt=8) and [mazec](https://itunes.apple.com/jp/app/mazec-shou-shuki-ri-ben-yu/id915223450?mt=8).

**Comment by Calefornia** [comment]
I'm confused. What is the problem with allowing 3rd party keyboards?

**Comment by srirambv** [comment]
Third-party keyboards works with Brave. Closing the issue.
