### ISSUE TITLE
janky to switch between home screen

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#215]
Posting for a friend: 

While Brave is opened and previewing all the tabs that are currently opened, moving between Brave and the iOS home screen seems a bit janky compared to other applications.

STR:
- open several websites using Brave (7 in my use case)
- once you have several websites opened, click on the "Tab Preview"
- while Brave is previewing all the tabs that are opened, press the middle button in the iPhone and move back to the iOS Home Screen
- If you go through the STR several times, you'll notice that sometimes the transitions appear really janky compared to other applications. I could get a video of this but I'm not sure if the video will capture the jank.

**Comment by garvankeeley** [comment]
I couldn't repo on my 5c but I'll try on my ipads and see. Once I repro the profiler should reveal the culprit.

**Comment by garvankeeley** [comment]
Can you try on 1.2.4? (assuming this was from an earlier build)

**Comment by garvankeeley** [comment]
@alexwykoff I think we can close this now, seem like an older bug we can't repro, thoughts?
