### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#229]
I find things really hard to use with a keyboard on my iPad Pro.
In particular other browsers respond to the same shortcuts as OS X even know it's in iOS.

Some of the main things I'm missing but does work in safari:
- Command+L: Focus the location bar
- Command+F: Open find in page
- Command+T: Open a new tab
- Command+W: Close a tab

There are others too but that would greatly improve usability.

**Comment by garvankeeley** [comment]
Forgot to close this when this feature added
a412841f9b127f805849750ed130727cdf4d7d4e
9ec62299006e29fe146b454d1ca081b852da1427
