### ISSUE TITLE
Clear location bar input (x) is not visible in private tabs

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#230]
In private tabs, there is no (x) in the location bar to clear the input.  Tapping on that area of the screen does clear it though.  Note that it's not that it's hard to see, it's that it is not visible at all.

**Comment by garvankeeley** [comment]
I think the refresh button may have changed something there, the (x) showing up is buggy in non-private tabs also

**Comment by bbondy** [comment]
consistent in private tabs.
