### ISSUE TITLE
Pressing enter for find in page doesn't go to the next result

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#232]
After doing a share for find in page, pressing enter doesn't go to the next entry. Shift + Enter should go to the previous.  This is probably similar to the shortcuts bug, but since they're scoped to the find bar I thought I'd post separately.

**Comment by garvankeeley** [comment]
I pulled aaf13f4c61a8ec4fd9c4f001831e6ceb9f1ffe98 from firefox, which should fix
