### ISSUE TITLE
Add request desktop site

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#233]
Some sites only give you partial functionality with the mobile User Agent specified.
Please add a request desktop site option.

I think having a hamburger menu like Chrome would work well for this and make other options more discoverable like Find in Page.

**Comment by garvankeeley** [comment]
A hamburger menu would me more discoverable than in the Share menu. Show desktop site is in the Share menu (which has now become the iOS hamburger menu) in other browsers (other than chrome). 
The Share menu is to place to put this stuff going forward, as it is the Apple-ish way. The problem I see with other browsers (and us too) is that the icon and title in the share menu is generic. So for instance, "Find in Page" has no correlation to Brave, the title and icon have no correlation to the app, making them look like they could be 3rd party features (as the Share menu mixes in-app and 3rd party features in the list).

**Comment by bbondy** [comment]
CC @bradleyrichter 
I prefer a hamburger menu like the Chrome app has but I'm not an iOS guy.

**Comment by garvankeeley** [comment]
I don't defend the Share menu == hamburger menu :), the Share menu is kooky UI. But it is the current trend AFAIK. On IPhone we have limited space, no space for the burger menu. 
We could have discovery bubbles after the app runs, to point out "Find, Print, Request Desktop site" are in the share menu. Also, making the items in the share menu look like they belong to brave would be an improvement.

**Comment by bradleyrichter** [comment]
@garvankeeley So we could add custom icons for those items?

(FWIW, chrome on iOS feels like Android in the same way that FX on iOS feels like Android) 

Yet, the burger dots may be better than the lame standard of Share Menu for your junk drawer...just not iOS standard.

**Comment by garvankeeley** [comment]
Yes we can have our own icons.

**Comment by garvankeeley** [comment]
@alexwykoff @bradleyrichter once again I need your help with naming this in the UI :).
Currently this is called in the Share menu: "Open Desktop Site tab"

FYI: The webview component we use requires an immutable UA set per-tab, so we create a new tab that has a desktop UA.

**Comment by jtsternberg** [comment]
I'm in agreement that sticking app functionality under a "share" icon/menu is highly unintuitive, even if in vogue (unless said functionality is sharing-related or outward-focused).

**Comment by garvankeeley** [comment]
Yeah, we need get on fixing this and pulling find-in-page and show desktop site, out of there
