### ISSUE TITLE
Unzooming triggers reload of page

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#236]
If you scroll down a page a bit, then zoom in, and then try to zoom out. There's a good chance you're going to get the page to reload by accident.  I think that should be only for when you scroll the page to the top most position and beyond.

**Comment by garvankeeley** [comment]
I basically forgot to remove pull-to-reload when I added the reload button in the url bar. We don't need it and it is a big chunk of complicated code I am happy to yank

**Comment by bbondy** [comment]
I think the pull to reload is a nice feature but it shouldn't be hit when zooming out.
CC @bradleyrichter for thoughts on removal for pull down (my personal pref is to keep it but I'll let Brad decide).

**Comment by bbondy** [comment]
Just to keep others updated, Brad and Garvan discussed this over DM and agreed to remove pull to reload.

**Comment by garvankeeley** [comment]
Re-adding pull-to-reload
