### ISSUE TITLE
Block pop up windows option

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#237]
Looks like Firefox has a block pop ups option available in settings, seems like something we should also have.

**Comment by garvankeeley** [comment]
Agreed. WKWebView, has a handy callback interface to let the host know of js alerts/prompts, and also has one for window.open(). Also it has https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKPreferences_Ref/#//apple_ref/occ/instp/WKPreferences/javaScriptCanOpenWindowsAutomatically

With UIWebView, so far I have only window.open() routed to our code (a68b4feeb45576bef9cec7dfb710d7841964733a). I need to investigate further true popup blocking, sites such as http://www.popuptest.com are good for that.

**Comment by garvankeeley** [comment]
I *may* have a way to separate window.open() calls that are tap/no-tap initiated (i.e. click/not clicked). That appears to be the crux of what is meant by "block popups".

**Comment by garvankeeley** [comment]
fixed by 7b92ed0e11a34885a508235ddb5caba8700747e7

**Comment by bbondy** [comment]
🎉
