### ISSUE TITLE
Some search queries are incorrectly loaded as urls

### ISSUE THREAD

**Issue by bridiver** [brave/browser-ios#239]
Steps to reproduce:
1. Clear the urlbar and type headlamp inverted
Expected:
Google search for "headlamp inverted"
Actual:
Attempts to load http://headlamp.inverted

I tried this on mobile Safari and it correctly interpreted it as a search query. Both browsers automatically inserted a "." between the words when entering them, but only Brave attempted to load as a URL. I was eventually able to coerce it into loading as a search query by going to google directly and now I can't replicate using the same keywords.

**Comment by garvankeeley** [comment]
tried to watch out for this and i can't repro, please re-open if you see again
