### ISSUE TITLE
Always get one more unnecessary character when typing chinese

### ISSUE THREAD

**Issue by yurenju** [brave/browser-ios#240]
#### STRs:
1. open brave
2. click search bar
3. use bopomofo (注音) chinese input method to type two word "中文"

#### expected:
get two chinese words "中文"

#### actually:
get three words "ㄓ中文"

#### screencast:
![brave-chinese](https://cloud.githubusercontent.com/assets/22155/15563265/7c582d28-2339-11e6-801c-7ee81921f880.gif)

**Comment by garvankeeley** [comment]
I tried to reproduce by copy+paste the characters in the bug in -one at a time- into the url bar, and the bug didn't happen, therefore the repro step requires typing in with the bopomofo input method.

**Comment by yurenju** [comment]
@garvankeeley: I believe so, because "中" is composed by ㄓ ㄨ ㄥ ，that is why we get an extra "ㄓ"

**Comment by garvankeeley** [comment]
#415 fix should work for this also

**Comment by yurenju** [comment]
It seems like the same issue, thank you!
