### ISSUE TITLE
Add DuckDuckGo as a search engine option to all locales

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#243]
For non-english locales, we are using Firefox iOS list of search engines.
Users are complaining DDG is not in certain locales.

**Comment by bbondy** [comment]
just making sure you also still have t=brave
https://github.com/brave/browser-ios/issues/155

**Comment by garvankeeley** [comment]
Yes, it is defined as part of search engine's definition in ```duckduckgo.xml```. Each search engine has an xml file that defines it's behaviour.
