### ISSUE TITLE
Add the ability to re-order bookmarks

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#245]
Requested from support.

**Comment by diegodoval** [comment]
Also, adding 'remove'
![image](https://cloud.githubusercontent.com/assets/420063/17152440/a78bafd8-532c-11e6-87f9-ca9ce76bbaf6.png)

**Comment by diegodoval** [comment]
Will close this as-is in the branch and then use the data in #301 to finish.

**Comment by diegodoval** [comment]
Final spec described in #301
