### ISSUE TITLE
Edit bookmark name/address

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#246]

**Comment by bradleyrichter** [comment]
Adding the edit button for bookmarks requires adding a lower toolbar which will hold all buttons for all side panel edit features. 

The "Add Folder" button is shown but will be defined in a separate issue.

(The same list view edit controls mode can be applied to history in the future )

spec image:
![image](https://cloud.githubusercontent.com/assets/13509546/17157449/33a09d82-5344-11e6-838e-3262ededf9bc.png)

**Comment by bradleyrichter** [comment]
[brave_icons_iOS_new-assets 2.zip](https://github.com/brave/browser-ios/files/384942/brave_icons_iOS_new-assets.2.zip)

**Comment by diegodoval** [comment]
@bradleyrichter two comments on the icons: the edit icon looks more like editing an item than the list, possible to add a few list items behind to clarify? Also the "add folder" icon" has the folder angle covered by the plus. On the phone I can't see clearly that it's 'add folder'

**Comment by bradleyrichter** [comment]
sure. Good point. I can add the same lines to the edit pencil.

Regarding the folder, did you view the ZIP? It should be improved there.

**Comment by diegodoval** [comment]
yup folder in the ZIP is much more clear!

**Comment by diegodoval** [comment]
closed in https://github.com/brave/browser-ios/pull/379
(edit can be accessed by swiping left on a bookmark)
