### ISSUE TITLE
Manual tests 1.2.6 16.06.06.15 iPad Pro

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#251]
Bookmarks
- [x] Install current store version, install new release and ensure bookmarks and history are preserved
- [x] Test add and remove bookmark
- [x] Navigate to a bookmarked page and ensure bookmark star is filled

In Settings
- [x] Verify changing the default search engine

Private Mode
- [x] Create private tab, go to http://google.com, search for 'yumyums', exit private mode, go to http://google.com search box and begin typing 'yumyums' and verify that word is not in the autocomplete list

History
- [x] On youtube.com, thestar.com (or any other site using push state nav), navigate the site and verify history is added. Also note if the progress bar activates and shows progress.
- [x] Settings > Clear Private Data, and clear all. Check history is cleared, and top sites are cleared.

Web view
- [x] Find in page in the Share menu: verify you can find a word and iterate through matches on the page
- [x] Context menu: verify you can Open in Background Tab, and Open in Private Tab
- [x] Swipe back and forward to navigate, verify this works as expected

Bravery options
- [ ] Pick a known site with ads, toggle Brave Shield and verify ads appear/disappear
- [x] Go to http://excellentmovies.net and verify it is blocked by safe browsing
- [x] Go to http://www.apple.com and make sure it redirects you to the https URL
- [x] Toggle the Brave Shield to off on a site, verify that the Shield goes up/down as you leave/show the site.

Top sites view
- [x] long-press on top sites to get to deletion mode, and delete a top site (note this will stop that site from showing up again on top sites, so you may not want to do this a site you want to keep there)

Background
- [x] Start loading a page, background the app, wait >5 sec, then bring to front, ensure splash screen is not shown

**Comment by bbondy** [comment]
Failure on:
>  Pick a known site with ads, toggle Brave Shield and verify ads appear/disappear

Seems like some kind of a caching issue.
As I play with shields up and down on m.slashdot.org and also on rd.com I can sometimes reproduce both with ads and without ads in both shields up and shields down cases.

**Comment by bbondy** [comment]
Otherwise everything is passing.

**Comment by garvankeeley** [comment]
Fixed in https://github.com/brave/browser-ios/commit/50b51515ccb64ca2f7d0edeeee7d3b0918402a06

I'll do a new release build.

**Comment by bbondy** [comment]
Confirmed fixed in 1.2.6 16.06.07.16.
