### ISSUE TITLE
Default search engine being reverted

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#259]
Posting for a friend:
I'm not sure if this is already a known issue, but sometimes when there's updates, Brave reverts the default search engine back to Google rather than keeping the user selected search engine. I've had this happen several times where Brave's search engine was reverted back to Google. Brave shouldn't be reverting users choices/settings, even if there's an update.

**Comment by garvankeeley** [comment]
Is this a BraveBeta or Brave release issue? 
I'll look for what could be causing this. Everything in the settings screen is stored in the app prefs (NSUserDefaults), when new releases come out, I check that my settings from prev are retained, however, I don't always pay attention to this setting as I change it often when testing. I'll keep an eye out for this happening.

**Comment by garvankeeley** [comment]
Marking as Top Bug, at least until we are sure it isn't serious

**Comment by bbondy** [comment]
> This happened while updating BraveBeta.. I've only seen it occur a few times (2-3) times so it might be a specific corner case and not a regular occurrence. I'll keep an eye out for this as well and see if I can get better STR. With the newest update v1.2.8 (16.06.30.18), it kept all the settings intact as expected.

**Comment by garvankeeley** [comment]
Thanks for the follow up, we'll just keep an eye on this for now and see if it re-occurs.

**Comment by garvankeeley** [comment]
Closing until it happens again
