### ISSUE TITLE
Open history entries in new tabs

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#262]
Posting for a friend:

It would be nice if you could open History entries into new tabs rather than only being able to open a history link within the tab you're currently in.

User Case:
- open the latest version of the iOS Brave browser
- tap on the menu on the left hand side and select "History"
- user has several links that they would like to open while History is opened
- user long taps on a link and gets a context menu that lets the user open that particular link within a new tab rather than the same tab

**Comment by garvankeeley** [comment]
Great idea and easy to implement
