### ISSUE TITLE
Spotify signup page broken on UIWebView, can't focus form fields

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#264]
Not sure why yet, but tapping on the form fields won't focus them.

**Comment by garvankeeley** [comment]
Brendan asked:
```could page content could be changed to work in UIWebView? ```
Spotify could change the content to work with UIWebView, not sure how reliable or maintainable it would be to try do it client side. Would need more investigation.

```Rdar report on file? Thanks.```
closed bug system, so hard to say, apple *may* indicate if bug is a dup once filed, but UIWebView compat bugs probably aren't getting fixed. To file radar effectively requires isolation of the problem, which would be time consuming.

**Comment by garvankeeley** [comment]
And now it is working, and can't repro.

**Comment by Jacalz** [comment]
Seems to work, closing

**Comment by Jacalz** [comment]
I believe that Spotify has totally remade the site since this was filled
