### ISSUE TITLE
Make tabsbar tabs draggable

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#272]
Currently tabs are fixed in position and you can't drag and re-order them.
In Chrome in contrast you can tap and hold then drag around the tab to re-order them.

**Comment by garvankeeley** [comment]
Agreed, but won't be able to do so for first release. So many layout bugs to fix still for first release.

**Comment by bbondy** [comment]
Just noting that it might be better to hold the tabs bar for this. Although it's great so far, from LB we see that unpolished feature leads to net bad reviews. E.g. more people will give 1 star because tabs aren't moveable compared to no tab bar.  Up to you though.

**Comment by garvankeeley** [comment]
yeah if the sub-feature is expected as part of normal behaviour of the larger feature, I can see that. 
Will try to get it in

**Comment by garvankeeley** [comment]
5623f0b559f37e73d7ddc44e40f9a19dbad7faa3
