### ISSUE TITLE
Stuck on on-boarding screen

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#274]
Posting for a friend:

This issue is pretty similar to bug: https://github.com/brave/browser-ios/issues/260

Rather than the browser crashing on the on-boarding screen after installing a new version, this time around I can't pass the on-boarding screen. Every time I tap on "Start Browsing", the on-boarding screen just re-appears. I tried closing the browser several times but the only way to recover is completely removing Brave and re-installing.

Video of the issue: https://youtu.be/tWUeRI5Ewno

User Case:
- had about 10 tabs opened
- was prompted several times to install the new version (selected cancel a few times)
- finally decided to update while I had about 8 tabs opened
- while the update was occurring, I closed Brave which was still opened in the background
- once the update completed, I re-opened Brave
- all my opened tabs were closed
- on-boarding screen was presented
- attempted to continue browsing via "Start Browsing" but can't pass the screen
- re-installed the entire browser via crashlytics

**Comment by garvankeeley** [comment]
Whoa,  this looks nasty. Will look to see how this could happen, the code relating to this is unchanged AFAIK, but hopefully there was a change that explains this. Tapping to close the Start Browsing should write a value into NSUserDefaults (the app settings) to not show again.

**Comment by garvankeeley** [comment]
Closing for now, during Beta I play it fast and loose, so I occasionally have a build that is not stable. If we see it again, re-open, and then I will panic :), because I have no idea how this happened.
