### ISSUE TITLE
Escaping PB mode

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#275]
Posting for a friend:

When navigating through websites via Private Browsing (PB), sometimes Brave will escape PB mode and load the popups and the target website in regular mode rather than keeping it inside PB. It usually happens during navigation. When there's a popup that opens during navigation, Brave switches back into regular mode and loads the popup and all the currently opened websites via the regular mode rather than keeping it inside PB.

Video of the issue: https://youtu.be/XljIX46wBDY

Test Case:
- Open Brave and create a new Private tab
- load http://www.popuptest.com/popuptest12.html within the private tab
- once the website completes loading all the popups, select the "Back" button on the page
- you'll notice that Brave will revert back into "regular" mode and loads one of the popups rather than keeping it inside PB mode

You'll run into this issue with adult websites as well, and everything spills over into regular mode which isn't good as users expect to stay within PB. It usually happens with websites that serve a lot of popups when navigating through pages.

**Comment by garvankeeley** [comment]
This is priority -- investigating + fixing now
