### ISSUE TITLE
Fresh tab: add overview text area to brave panel when disabled

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#277]
Tapping it does nothing, which is confusing

**Comment by bradleyrichter** [comment]
Here is a suggested improvement where we use the opportunity to provide some helpful info for the user who chooses the brave button at the new-tab page.

![image](https://cloud.githubusercontent.com/assets/13509546/17154498/25b71d1c-5336-11e6-819c-9a3c1899b101.png)

**Comment by bradleyrichter** [comment]
cc @diegodoval

**Comment by garvankeeley** [comment]
Cool idea, and I don't recall and code structure/flow issue that would make this a problem to implement (might be easy)

**Comment by garvankeeley** [comment]
fixed by https://github.com/brave/browser-ios/pull/599
