### ISSUE TITLE
Unable to resolve unicode characters in URL.

### ISSUE THREAD

**Issue by MindTooth** [brave/browser-ios#279]
Hi,
Accessing [nordølum.no](nordølum.no) (no backslash helps to force resolving) in Brave jumps straight to the search engine.
Viewing my Github Page with the URL typed & linked[1], nord%C3%B8lum.no is displayed if I hold down on the link and get the popup.
However, if you write [nordolum.no](nordolum.no), it redirects correctly the the none-unicode version.

Just to let you know :-)

[1] https://github.com/MindTooth/mindtooth.github.com

**Comment by garvankeeley** [comment]
Looks like we need to hook up https://github.com/Wevah/Punycode-Cocoa
