### ISSUE TITLE
Add fullscreen mode

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#280]
From support:

> Is it possible to show Brave full screen on iPhone?

also tickets/3602

**Comment by garvankeeley** [comment]
More than just scroll down the page to hide the toolbars? Is there another app that you like the behaviour of I can take a look at?

**Comment by luixxiul** [comment]
I don't think so..

**Comment by bradleyrichter** [comment]
I think this problem is often related to viewing images. This one of my remaining nitpicks where Safari trumps brave. 

Try viewing an image in a google image search. In safari, the chrome goes away and you can pinch-zoom on the image. In Brave, the toolbars are ever present.

**Comment by srirambv** [comment]
on 1.4.2 the image loads and then the chrome disappears for a moment and then reappear
