### ISSUE TITLE
Make settings discoverable more easily

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#281]
At first it is hard to find settings because the half star/setting icon appears just like a bookmarking button. Including the instruction how to change settings in the tour would solve the issue.

**Comment by garvankeeley** [comment]
A band-aid fix might be to put the settings in the Brave panel. Not sure if that is any better though.

(We also have a major discoverability problem with the find in page. )

**Comment by luixxiul** [comment]
> A band-aid fix might be to put the settings in the Brave panel.

+1, that's what exactly I also thought.

**Comment by bradleyrichter** [comment]
The original plan was to put it in the brave panel but we didn't have one at the time. So let's move it to the top right corner of the brave panel.

![image](https://cloud.githubusercontent.com/assets/13509546/17109336/767ebdda-524c-11e6-924e-0c0e90cd8e2a.png)

**Comment by garvankeeley** [comment]
The pane

**Comment by garvankeeley** [comment]
This panel is not accessible at all times though

**Comment by bradleyrichter** [comment]
We have a fix for that. Someone had a good suggestion to show a helpful notes paragraph when the the panel is in a non-applicable state.

**Comment by bradleyrichter** [comment]
something like this:

![image](https://cloud.githubusercontent.com/assets/13509546/17109762/3ba9f1fa-524e-11e6-981e-47483bac28de.png)

**Comment by bradleyrichter** [comment]
cc @diegodoval

**Comment by srirambv** [comment]
@bradleyrichter @jamesmudgett  is this still under consideration?
