### ISSUE TITLE
Error pages are missing

### ISSUE THREAD

**Issue by bridiver** [brave/browser-ios#286]
DNS and network errors either load a white page or change the url without changing the page content

**Comment by bridiver** [comment]
great, thanks!

**Comment by RyanJarv** [comment]
May have been a regression here? Currently going to a non-existant domain doesn't seem to show any error on the iPad/iPhone.

**Comment by bridiver** [comment]
cc @jhreis since no one was actually assigned to this ticket originally

**Comment by iccub** [comment]
@RyanJarv I can't reproduce it, tried typing random domains and visiting websites in airplane mode, both show errors properly.

Can you always reproduce it? Any steps to reproduce could be helpful.

I tried to test it on 10.3.1 simulator, the Brave app had some old tab opened already, then after visiting wrong domain it did nothing, no blank screen nor error screen, but after opening a fresh tab it worked again, so maybe something just cached badly.

**Comment by iccub** [comment]
Confirmed this happens only for restored tabs, filed a new issue that can be tracked [here](https://github.com/brave/browser-ios/issues/1393).

**Comment by RyanJarv** [comment]
Yeah, looks like I was only testing with restored tabs, opening a new tab I get the correct behavior.  Thanks!
