### ISSUE TITLE
reduce back swipe distance

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#289]
Report from twitter is that our required swipe distance (1/2 screen) is greater than Safari. We should match Safari.

**Comment by srirambv** [comment]
+1 from community community.brave.com/t/swipe-adjustment/1070

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/improved-swipe-gestures/5155

**Comment by jackturnbull** [comment]
I'll also throw in my experience on this; one of the first things I noticed when I started using Brave this week. The difference is striking coming from Safari and so much so that it did/does affect user experience.
