### ISSUE TITLE
Manual tests 1.2.10 iPod Touch

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#291]
Bookmarks
- [x] Install current store version, install new release and ensure bookmarks and history are preserved
- [x] Test add and remove bookmark
- [x] Navigate to a bookmarked page and ensure bookmark star is filled

In Settings
- [x] Verify changing the default search engine

Private Mode
- [x] Create private tab, go to http://google.com, search for 'yumyums', exit private mode, go to http://google.com search box and begin typing 'yumyums' and verify that word is not in the autocomplete list

History
- [x] On youtube.com, thestar.com (or any other site using push state nav), navigate the site and verify history is added. Also note if the progress bar activates and shows progress.
- [x] Settings > Clear Private Data, and clear all. Check history is cleared, and top sites are cleared.

Web view
- [x] Find in page in the Share menu: verify you can find a word and iterate through matches on the page
- [ ] Context menu: verify you can Open in Background Tab, and Open in Private Tab
- [ ] Swipe back and forward to navigate, verify this works as expected

Bravery options
- [x] Pick a known site with ads, toggle Brave Shield and verify ads appear/disappear
- [x] Go to http://excellentmovies.net and verify it is blocked by safe browsing
- [x] Go to http://www.apple.com and make sure it redirects you to the https URL
- [x] Toggle the Brave Shield to off on a site, verify that the Shield goes up/down as you leave/show the site.

Top sites view
- [x] long-press on top sites to get to deletion mode, and delete a top site (note this will stop that site from showing up again on top sites, so you may not want to do this a site you want to keep there)

Background
- [x] Start loading a page, background the app, wait >5 sec, then bring to front, ensure splash screen is not shown

Fingerprinting Protection Test
- [x] Test one of these sites with Fingerprinting Protection on in the Brave panel: <br>
• https://www.browserleaks.com/canvas -> 'Your fingerprint' section never gets filled out <br>
• https://panopticlick.eff.org  -> look for hash starting with 891f3debe <br>
• https://audiofingerprint.openwpm.com/ -> will show blank fingerprint values <br>
• <sub>Site possibly down? : https://amiunique.org/fp  </sub><br>
- [x] Open the Brave panel and see the 'Fingerprinting Methods Blocked' is non-zero

Javascript Blocking Test
- [x] Toggle 'Block Scripts' in Brave panel, load nearly any website and verify that the 'Scripts Blocked' number in the Brave panel is non-zero. Bonus: load a site that has a js navigation menu and verify the menu does not work.

**Comment by luixxiul** [comment]
All tests passed except:

- Open in New Private Tab is not working (it reopens the page in the same tab)
- Swipe forward from the default page is not working (it works between opened pages)

@garvankeeley, will you please confirm these two?

**Comment by garvankeeley** [comment]
I can't repro the new private tab bug. New private tab will switch the entire app into private mode, and open a single tab, so it could just be "Open in Private Mode". 

 The swipe forward behaviour is a bug since swipe was added that you just found.

**Comment by luixxiul** [comment]
I see, and I noticed that if I go back from Private Mode the private tab is cleared, which means it works as it should, right?

**Comment by garvankeeley** [comment]
Yeah, because of the older-style UIWebView, we have to globally set the application state to private or not. Leaving and entering requires deleting and recreating all the web views to set their state (private/non-private). You'll notice that leaving private mode seems a little slow, this is due to waiting for UIWebViews to totally get wiped from memory. There is no possibility of having mixed private and non-private tabs that are alive (in-memory) at the same time.

Some other UIWebView apps aren't doing this, and some state is kept in-memory, and isn't really private IMHO. For instance I found Dolphin/Puffin/Maxthon, if I type in a google search in private mode, then leave private mode, it autocompletes the private search term.

**Comment by luixxiul** [comment]
I see, so probably there should be a warning when you leave the private mode that the tabs will be cleared and cannot be restored thereafter.

**Comment by garvankeeley** [comment]
Maybe there could be an info message on the private mode tabs tray, or something that showed the first time private mode is used.
