### ISSUE TITLE
Brave panel stats all zero (not sure how to repro)

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#292]
Sometimes after page load the Brave stats are all zero. 

Not sure of the cause, I originally suspected UIWebView internal caching (my note on this):
`Aside from NSURLCache, UIWebView has its own internal cache (which is inaccessible to devs). If a site loads from this cache, I will get no network calls, and the stats will be zero.`

Need STR

**Comment by garvankeeley** [comment]
@alexwykoff one to watch for 👀

**Comment by garvankeeley** [comment]
Removing top bug status, as i am not seeing this again, and we have no STR. I thought it would be more prevalent.

**Comment by garvankeeley** [comment]
@jhreis this is the bug you mentioned in ios channel yesterday

**Comment by jamesmudgett** [comment]
QA and Close

**Comment by srirambv** [comment]
Works fine on 1.4.2. Closing as DNR. Could be that this was observed on a page that doesn't have anything blocked like facebook
