### ISSUE TITLE
Tabs bar UI bug: wrong selected tab when first tab deleted

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#293]
STR: create 3 tabs, select the rightmost tab, delete the first tab. The first tab will appear selected in the tab bar, but the last tab is the one showing.

**Comment by diegodoval** [comment]
this bug will no longer exist after the implementation of https://github.com/brave/browser-ios/issues/296 since 296 removes the ability to remove non-focused tabs. This one should probably be closed.
