### ISSUE TITLE
mp3 error: 'Plugin handled load - WebkitErrorDomain' dialog appears when playing

### ISSUE THREAD

**Issue by CameronNicolson** [brave/browser-ios#294]
Hello developers,

These errors occur after the latest update of Brave for iOS. 

I have been enjoying XFM The Ricky Gervais Show and listening from this website [website](http://www.wherewhywhen.com/xfm-the-ricky-gervais-show-seasons-1-4-complete/), which is the offender in this circumstance. When I try to open one of the mp3s then the media player crashes and a dialogue appears with 'Plugin handled load - WebkitErrorDomain'.

![img_0867](https://cloud.githubusercontent.com/assets/6314429/17101898/d883107c-526e-11e6-8af2-0fa872fed373.PNG)

Finally, thank you for supporting Brave and building a better web!

**Comment by alexwykoff** [comment]
repro'd with http://www.alexwykoff.com/2/demo/bg.mp3
