### ISSUE TITLE
add New Tab button to tabs bar

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-ios#295]
As a user, I need an efficient and intuitive method for adding a new tab while I am browsing in landscape view (or any time the tabs bar is visible).

The plus button can be added to the right end of the tabs bar.

A vertical separator line (black) is placed to the left of the New Tab button.

The button icon is the same as the new-tab button used in the normal bottom toolbar in portrait mode.

![image](https://cloud.githubusercontent.com/assets/13509546/17110576/845c2d38-5252-11e6-9005-aee8db3fbe66.png)

The button and icon should be centered to the brave icon and tab text.
(requires second task for reordering top right buttons)

![image](https://cloud.githubusercontent.com/assets/13509546/17110656/e9bcf522-5252-11e6-858e-c3e12f2753c2.png)

**Comment by bradleyrichter** [comment]
cc @garvankeeley @bbondy @diegodoval

**Comment by bbondy** [comment]
Can we get this in, it seems like low hanging fruit.

**Comment by bradleyrichter** [comment]
low, and sweet.  :   )

**Comment by garvankeeley** [comment]
added to next milestone, we are still planning what will actually get in there, may get bumped

**Comment by garvankeeley** [comment]
This is implemented for iPad only, which seems sensible, little room on iPhone, and iPhone has plus button in portrait view
