### ISSUE TITLE
modify styling and dimensions of tabs in tabs bar

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-ios#296]
Changes:

1. Increase tab height by roughly 4 pixels to match height of URL bar

2. reduce height of separator bar between tabs to match the appearance in the screen shot below (DD Addition - line should not be there to the left of the selected tab)

3. remove close buttons from non-selected tabs

![image](https://cloud.githubusercontent.com/assets/13509546/17111959/b6b011d6-5258-11e6-82cf-df374af2aa00.png)

**Comment by garvankeeley** [comment]
First test of our QA Please label, and assigning to Alex. This will keep Alex informed of front-end changes, some changes might need additional hands-on testing (such as multi-device testing), but primarily this will keep him in-the-loop as the UI changes.
