### ISSUE TITLE
"+" icon (a.k.a New Tab toolbar button) has non-obvious behavior on empty page

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-ios#298]
If you don't have a site loaded, clicking on the plus sign seems to give focus to the address bar, then removes focus, then adds the empty tab and gives it focus. From the point of view of a person tapping the button this appears to be a no-op (in reality every tap is creating a new empty tab and giving it focus, opening the list of tabs shows lots of 'home' pages with the top sites). 

Tapping 'plus' is an action that should result in the new tab being opened with focus on the address field  (expanded keyboard) and possibly other visual cues that could clarify that this is in fact a new page. 

![image](https://cloud.githubusercontent.com/assets/420063/17115867/23da3e10-526a-11e6-99ae-8ce232a2919e.png)

**Comment by bradleyrichter** [comment]
would disabling it solve this issue? We added it to remove steps for making a new tab when you want to retain the current active tab.

**Comment by diegodoval** [comment]
I think the solution is to have it give focus to the url bar and raise the keyboard. Otherwise it will remain confusing. It's not clear when it would enable if we set it as disabled.

**Comment by bradleyrichter** [comment]
this is how it works now ^^
