### ISSUE TITLE
Add an "Open in Brave" option when holding on URL

### ISSUE THREAD

**Issue by jansensan** [brave/browser-ios#300]
When keeping the finger down on a URL, options a presented to "Open in Safari", "Open in Firefox" (if installed), copy, etc. Having one to open in Brave would be quite helpful to manually avoid the default behavior of apps opening links in Safari.

![image](https://cloud.githubusercontent.com/assets/1410355/17140141/a3502136-5347-11e6-951b-a0ef463282ad.png)

![image](https://cloud.githubusercontent.com/assets/1410355/17140188/d613c582-5347-11e6-8dd6-22d8d2c48d8f.png)

**Comment by bradleyrichter** [comment]
@jansensan This should already be working. Perhaps it hasn't landed yet in the app store? Or is your app pictured above only supporting the lower choices?

![image](https://cloud.githubusercontent.com/assets/13509546/17157367/a46d3972-5343-11e6-9f85-4ee7ad2491eb.png)

**Comment by jansensan** [comment]
@bradleyrichter Actually I was only looking in the lower options because I did not know it could be part of the options of the row above. Yes indeed, this is implemented, thanks!
