### ISSUE TITLE
add edit tools toolbar to left side multipanel

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-ios#301]
The bookmarks, history, and future list views need a consistent place to access edit tools that are contextual to the current view. (ie - bookmarks)

The "Add Folder" button is shown but will be defined in a separate issue.

This toolbar should appear in both portrait and landscape views.

(The same list view edit controls mode can be applied to history in the future )

spec image:

![image](https://cloud.githubusercontent.com/assets/13509546/17160592/dbfe5c88-535a-11e6-9a15-43312cee1ebe.png)

**Comment by bradleyrichter** [comment]
@diegodoval 's prev comment:

@bradleyrichter two comments on the icons: the edit icon looks more like editing an item than the list, possible to add a few list items behind to clarify? Also the "add folder" icon" has the folder angle covered by the plus. On the phone I can't see clearly that it's 'add folder'

**Comment by bradleyrichter** [comment]
@diegodoval ----> new icons:

![image](https://cloud.githubusercontent.com/assets/13509546/17160755/5b9072aa-535c-11e6-8ea7-714567d70e95.png)

**Comment by bradleyrichter** [comment]
zip of new icons

[brave_icons_iOS_new-assets 3.zip](https://github.com/brave/browser-ios/files/385418/brave_icons_iOS_new-assets.3.zip)

**Comment by diegodoval** [comment]
closed in https://github.com/brave/browser-ios/pull/379
