### ISSUE TITLE
remove separator bar to the left of the selected tab

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-ios#302]
The separator bar is visible to the left of the selected tab - remove (related to #301)

![image](https://cloud.githubusercontent.com/assets/420063/17161183/4da93d58-5360-11e6-8ae7-7460cc6e9e6b.png)

**Comment by garvankeeley** [comment]
also to the left of the first tab
<img width="249" alt="screenshot 2016-08-01 21 08 31" src="https://cloud.githubusercontent.com/assets/5495083/17313718/31b2bcca-582c-11e6-98d9-f3f83d20f75f.png">
