### ISSUE TITLE
fix screenshot code crash (iOS 8 only)

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-ios#307]
Crash is at drawViewHierarchyInRect within the function that draws the screenshot into a UIImage context.
	
UIViewExtensions.swift line 17
UIView.screenshot(CGFloat, offset : CGPoint?, quality : CGFloat) -> UIImage?
called from: ScreenshotHelper.swift line 41
                     ScreenshotHelper.(takeScreenshot(Browser) -> ()).(closure #1)

Screenshots are used mainly by the tab functionality to have a preview of the page available. See uses of ScreenshotHelper.takeScreenshot.

**Comment by garvankeeley** [comment]
Orig. private report: https://fabric.io/brave6/ios/apps/com.brave.ios.browser/issues/573490c5ffcdc04250baac2c

**Comment by garvankeeley** [comment]
Consider dropping iOS 8 soon, we have zero testing or devices on this platform.

**Comment by garvankeeley** [comment]
My note on 15d1801 was:
```
Landing, as it is no longer labeled as a fix, just some extra guard conditions. Original bug is still open and needs more research.
```

However, I forgot to change the commit title on the bug, so it auto-closed this issue. I could rebase and edit the commit message, but not going to bother.

**Comment by garvankeeley** [comment]
Closing, until we see otherwise, no reason this code would crash with the fix. If additional refactoring planned, file bug for that
