### ISSUE TITLE
Brave panel: Long domain names handled poorly in UI

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#311]
See https://github.com/brave/browser-laptop/issues/2813

**Comment by garvankeeley** [comment]
![c341d1bc-55a2-11e6-9a75-002dbcb76bb0](https://cloud.githubusercontent.com/assets/5495083/17274122/fb3301ca-569e-11e6-95f0-aa5e7951205a.png)

**Comment by bradleyrichter** [comment]
Ok. Let's allow auto-scale down to a reasonable size and then truncate. Since the beginning of the URL should provide enough recognition, it should work fine for 99% of URLS.

**Comment by bbondy** [comment]
begging of the origin is the least important security info btw.

**Comment by bradleyrichter** [comment]
does it matter here? It's main purpose is to remind them which domain they are adjusting settings or disabling shields for...

**Comment by garvankeeley** [comment]
iOS can truncate leading, middle or tail. We know we don't want tail-truncation. Middle truncation looks the most visually appealing (IMHO), but leading truncation as Brian said is the most correct to do in this case

**Comment by bradleyrichter** [comment]
how would this truncate with leading or middle?

"https://github.com/brave/browser-ios/issues/311#issuecomment-236961344"

**Comment by garvankeeley** [comment]
link not working for me
https://github.com/brave/browser-ios/issues/311#issuecomment-236961344

**Comment by diatrevolo** [comment]
Just new to Brave, but saw this bug and figured I'd lend a hand . PR above.

**Comment by garvankeeley** [comment]
fix looks good to me: https://github.com/brave/browser-ios/pull/345
