### ISSUE TITLE
toggles should have colors for "on"

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-ios#313]
For example, in the right side panel. I've given it a shot to living with it this way since it's clearly done on purpose within the code :) but it's still confusing. Toggles on iOS are colored when on, without color when off. This panel (and perhaps other places) uses a colored version at the top and b&w versions below, which makes them all seem disabled/off (and the ones all in white below seem to indicate the component itself is completely disabled). I think we should use the standard iOS toggle colors to minimize confusion in pretty much every case -- I understand the rationale to make the 'shields up & down' toggle stand out, but others should be more clear. 

![image](https://cloud.githubusercontent.com/assets/420063/17280536/b752daf4-5746-11e6-94de-65d18a4e0dac.png)

@garvankeeley  @bradleyrichter something to consider

**Comment by bradleyrichter** [comment]
@diegodoval Thanks for bringing up the issue. Let's look at options before considering a switch to all green switches.

**Comment by diegodoval** [comment]
For reference, this is Apple's guidelines page for this component https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/UISwitch.html

**Comment by bradleyrichter** [comment]
I think it will look OK to switch to all orange tint colors in the switches:

![image](https://cloud.githubusercontent.com/assets/13509546/17301236/cdad1c68-57ca-11e6-990b-d2c36bfeb6fd.png)

Usability overrides style in this case...

**Comment by bradleyrichter** [comment]
@diegodoval 

Please go ahead and revert grey switches back to orange as shown above.

**Comment by diegodoval** [comment]
Fixed: PR is https://github.com/brave/browser-ios/pull/357
