### ISSUE TITLE
Stay in Private mode, make it a persistent app state

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#319]
Instead of resetting to non-private mode after app kill, if user was last in PB mode, return to this mode until user explicitly exits

**Comment by garvankeeley** [comment]
Also, if user does open-in-brave, ensure these keep the app in private mode. I think there is a bug here

**Comment by garvankeeley** [comment]
Removing top-bug status, we now have "Always PB mode" switch, and I can't repro this bug. 

With app in private mode, if go to another app and "Open in Brave" it opens link in priv mode as expected.
I think the issue is what should happen if the app is killed in private mode, should it re-open in private mode? I need more input from UX'ers as to whether that is expected behaviour, as to me it seems counter-intuitive.

**Comment by garvankeeley** [comment]
@marshray you mentioned this is still happening, can you mention your steps? Maybe I am doing it differently. (Although I am writing this before re-checking the bug to see if it exists, I will do that)

**Comment by jhreis** [comment]
This is no longer repro.
