### ISSUE TITLE
Home screen like UC and Opera.

### ISSUE THREAD

**Issue by chandananand** [brave/browser-ios#320]
How to customize the home screen like UC in this browser it will make it look better.

![img_1225](https://cloud.githubusercontent.com/assets/12099699/17392203/6800657a-5a39-11e6-8c4d-6631f3f86d44.png)

**Comment by bradleyrichter** [comment]
Thanks for the suggestion!

We will soon have the ability to choose a bookmarks folder for the home screen items but as of now, we don't have plans to add a news aggregator.

**Comment by LiuDeng** [comment]
@bradleyrichter we really need a  bookmarks folder for the home screen . Thank you for your great job~

**Comment by diegodoval** [comment]
moving off the bookmarks milestone, it will be a new feature.
