### ISSUE TITLE
Open in Background does not respect shield settings

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#329]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While testing the HTTPS Everywhere functionality, I visited http://www.apple.com/ by opening the context menu and selecting "Open in Background". When visiting the site, I noticed the protocol remained http instead of the default of HTTPS Everywhere being enabled.

**Expected behavior:**
The browser should use whatever shield settings are enabled.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone5

- Brave Version:
1.2.12 beta 1
- Steps to reproduce:
    1. Open a page which has a link to http://www.apple.com .
    2. Use the context menu to open the link in the background.
    3. Wait 30 seconds then switch to the newly created tab, check the protocol used.

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
Nice find. It is loading https but it isn't setting the URL bar location correctly, and thus looks like http. Not sure why just yet...
