### ISSUE TITLE
App hangs when toggling Block Phishing or shields up/down on certain sites.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#336]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When visiting http://excellentmovies.net/ and toggling the Block Phishing setting or Shields up/down, the app hangs and requires a relaunch to close the shield panel and browse.

**Expected behavior:**
The page should reload on any toggle and the user should be able to exit the shield panel at will.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Tested on iPhone5

- Brave Version:
BraveBeta 1.2.10 (16.08.04.12)

- Steps to reproduce:
    1. Visit http://excellentmovies.net/, page should be blocked
    2. Open the shield panel and turn off 'Block Phishing'
    3. Attempt to close the shield panel

- Screenshot if needed:

- Any related issues:

**Comment by diegodoval** [comment]
Interestingly when you tap 'block phishing' it is disabled and then instantly toggles back on, and the address at the top of the panel disappears.

**Comment by diegodoval** [comment]
Closed with PR https://github.com/brave/browser-ios/pull/344
