### ISSUE TITLE
Fingerprint protection is on even though the shield displays it as off.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#340]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Visiting https://audiofingerprint.openwpm.com/, if I run the test, no graphs are displayed.

**Expected behavior:**
A graph of my audio fingerprint should display.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Tested on iPhone6s plus

- Brave Version:
1.2.10 (16.08.09.13) an xcode build from sha: 9586f79f83019ed57334feceb10439479e63b61d

- Steps to reproduce:
    1. Visit https://audiofingerprint.openwpm.com/
    2. Click on the button to start the test
    3. Wait to observe if a graph has been generated

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
fixed: https://github.com/brave/browser-ios/commit/8f77969b042beba4e6f54fc79c80b42cb0540dfe
