### ISSUE TITLE
Blocked page (phishing alert) should stop a BraveWebView from continuing processing

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-ios#342]
BraveWebView keeps trying to process a page regardless of response code, including searching for favicon. It shouldn't.

**Comment by garvankeeley** [comment]
the JS injected should all be designed to handle any kind of page it is injected into, is a code cleanup item?

**Comment by diegodoval** [comment]
there's the issue of favicon search, etc. but I narrowed down this particular bug to deal with the blocked page.

**Comment by diegodoval** [comment]
Closed with PR https://github.com/brave/browser-ios/pull/344
