### ISSUE TITLE
Remove back swipe while shield panel showing

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#347]
From support:

> After loading a webpage, click on the shield button in the upper right. After the Shield Settings Page loads, in the space on the left side of the screen, where you can see the loaded webpage, swipe the webpage to the right until it goes back to localhost. Now the shield button is disabled and you can't exit the Shield Settings Page. You have to restart the app to get it out of this state.

**Comment by garvankeeley** [comment]
I am hoping that during the fix for this (which had a few bad code paths): https://github.com/brave/browser-ios/issues/341
this case was also fixed

**Comment by luixxiul** [comment]
OK I see, closing

**Comment by garvankeeley** [comment]
Is ok to keep open, I think those bugs are related, just making a note for the person who ends up looking at this bug

**Comment by garvankeeley** [comment]
Hmm they aren't related, the swipe detection should be blocked while that panel is showing

**Comment by diegodoval** [comment]
@garvankeeley they are related. The sidebar will not block anymore with the fix for #341 and #336

As to that the swipe shouldn't work... that's a different issue, specifically blocking all gestures in that invis view. It would be a different type of fix as well.

**Comment by diegodoval** [comment]
So this should be closed and perhaps a new bug opened for the other thing.
