### ISSUE TITLE
Remove 3rd Party Password Snackbar

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#349]
This was an experimental feature that has had its day in the sun.
It incomplete, and I am not convinced many are using it. 3rd party password manager users are familiar with pressing the Share button to fill in passwords.

@alexwykoff @diegodoval IIRC you both notice the lack of awesomeness of this feature.

Diego, I liked your suggestion about adding a button to keyboard top bar for PW manager access, when a login or PW field has been selected. I do find myself tapping the login field before realizing I now covered the Share button, have to tap away to close the keyboard, then select the Share button.

**Comment by diegodoval** [comment]
Cool. The addition to the top of the keyboard seems to be like a good solution (and it's roughly what Safari uses for iCloud keychain)

**Comment by bradleyrichter** [comment]
I believe this toolbar was only meant to be an extension of the keyboard. Not sure how it ended up at the bottom of the screen with no keyboard present.

original mockup:
![image](https://cloud.githubusercontent.com/assets/13509546/17606368/0d5df2d6-5fd4-11e6-9b50-3aca875ba8df.png)

**Comment by garvankeeley** [comment]
My bad. The fastest way to prototype it was to use the Snackbar code. Prototype never got revisited, prototype became release feature. Users will be much happier with the keyboard button.

**Comment by jamesmudgett** [comment]
PR: https://github.com/brave/browser-ios/pull/502
