### ISSUE TITLE
Bottom tool bar moves up to mid screen when scrolling (needs STR)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#351]
From support

> I've encountered a minor bug while using Brave for iOS on my iPhone 6. When scrolling fairly quickly on long document rich sites I've noticed the bottom Tab bar will occasionally lock up or stall mid screen.

**Comment by garvankeeley** [comment]
We have had a few reports of this (not of the 'lock up' aspect, that I am not clear on). The bottom toolbar is somehow getting animated further than it should and ending up way up the screen.
If we can repro, I can fix, it hundreds of app hours of usage, I have never seen this. I am sure there is some way to repro though.

**Comment by garvankeeley** [comment]
I just saw this when switching back to the app from another app, the bottom toolbar briefly over-translated up by 44px (it's height), but then snapped back. There is a minor bug here, probably easy to guard against by limiting the y translation of the bottom toolbar. /me looks

**Comment by srirambv** [comment]
I can consistetly reproduce this issue with the following steps on v1.2.16 (16.09.29.00)

1. Open a site, Open search from app extensions
2. Type  a search term. Without closing the search bar scroll the page up and down
3. Delete the search term and close the search bar
4. Try scrolling down the bottom tool bar scrolls upwards

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/17010094/18961846/5328ceb8-8666-11e6-91bd-58135cf83a15.gif)
