### ISSUE TITLE
Password shortcut error with LastPass

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#353]
From support:

> Version 1.2.9 for iOS. Whenever I try to sign in with LastPass, I get Password shortcut error – Can’t find item named LastPass. Also, in settings, the 3rd-Party password manager changes back from LastPass to Don’t use.

**Comment by garvankeeley** [comment]
Address as part of https://github.com/brave/browser-ios/issues/349

**Comment by jhreis** [comment]
Closing this per above. @luixxiul If you experience any additional LastPass issues please reopen or report if new.
