### ISSUE TITLE
Fullscreen on youtube sometimes not working (needs STR)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#354]
> My bug is an issue when selecting the full screen option for videos (I was on 123movies at the time) the video would not maximize.

On youtube too. I noticed other users were asking about this too

**Comment by garvankeeley** [comment]
I use youtube heavily with Brave, never had this, any more repro info? 
Likely a web compat bug, needs to be verified in Puffin/Dolphin/iCab
