### ISSUE TITLE
Redirected to old mobile site on espn

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#355]
From support:

> For some reason the latest version of Brave is being redirected to the old m.espn.go.com. If you use Safari you will see the "modern" site.
> 
> http://www.espnfc.us
> 
> This is happening in v 1.2.11 (16.07.24.00) on iOS 9.3.3

"Open in Desktop mode" could be a solution here.

**Comment by garvankeeley** [comment]
@alexwykoff can you see if other browsers do this, if so is 'web compat'
