### ISSUE TITLE
Always allow zoom

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#356]
From support:

> The only thing I can think of to make this browser better is to offer an option to always allow zoom. Those of us with poor eyes would really appreciate it!

**Comment by garvankeeley** [comment]
iCab has a feature for this, we could look at that in future for a sample implementation.

**Comment by amccary** [comment]
I cannot use the pinch to zoom setting either, I can only use the cmd + shortcut to zoom.

**Comment by jhreis** [comment]
@amccary Sounds like you may be referring to the desktop client? This is only for the iOS (e.g. iPhone) app.

If you are, you can leave a comment on https://github.com/brave/browser-laptop/issues/1364

Regardless, thanks for letting us know!

**Comment by amccary** [comment]
Thank you so much!!
