### ISSUE TITLE
user agent should be consistent across platforms and protect users from fingerprinting risks

### ISSUE THREAD

**Issue by bridiver** [brave/browser-ios#360]
Description:
The user agent for Brave should be as consistent as possible across platforms. iOS is a bit of a special case because of the platform limitations, but here are the options in order or preference
1. Copy the Chrome UA if that removes the google home page popup telling you to use Chrome and does not cause site compatibility issues
2. Copy the Safari UA if it doesn't cause site compatibility issues
3. Copy either Chrome or Firefox, preferring Chrome unless it causes compatibility issues
4 ??
cc @diracdeltas

**Comment by garvankeeley** [comment]
This link says the Chrome UA is the 'Safari UA' with CriOS section added:
https://developer.chrome.com/multidevice/user-agent

I think that is a typo, it is more likely the WKWebView UA not Safari.

```Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_1_1 like Mac OS X; en) AppleWebKit/534.46.0 (KHTML, like Gecko) CriOS/19.0.1084.60 Mobile/9B206 Safari/7534.48.3```

**Comment by garvankeeley** [comment]
Using the UA set in 60b0ead i see google search looks like chrome now, and no more popups on google.com to switch to chrome. Marking fixed.

**Comment by garvankeeley** [comment]
@alexwykoff watch for side-effects pls

**Comment by unsystemizer** [comment]
I get Mozilla/5.0 (iPad; CPU OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) CriOS/52.0.2743.84 Mobile/14B100 Safari/602.2.14 _id/000002 on panopticlick using iOS.
Very unique, and iPad vs iPhone above. Doesn't seem very consistent to me.

**Comment by garvankeeley** [comment]
Unfortunately the final id num on the UA is required to identify UIWebView to NSURLProtocol, it corresponds to the tab number. Without it, NSURLProtocol can't identify which UIWebView originated request.

**Comment by tfoil2** [comment]
As a browser that is marketed for speed, safety, and _privacy_, I'd like to advocate for a less unique UA, particularly when privacy-protective settings such as "Fingerprinting Protection" are enabled.

Current UA on iOS version 10.2, Brave version 1.2.18 (16.11.18.13) is:
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) CriOS/52.0.2743.84 Mobile/14C92 Safari/602.3.12 _id/00000*

Compare with iOS Safari UA:
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0 Mobile/14C92 Safari/602.1

I see that _id/* is unavoidable. However, it should be a small number and will change frequently, so entropy across visits, particularly when using Private Browsing, should not be excessive.

I propose that in its most private modes, Brave UA should mimic, as closely as possible, the browser its rendering behavior matches most closely, presumably Safari.

**Comment by garvankeeley** [comment]
Agreed that with more users on Safari, its UA provides greater anonymity; but we use a faked Chrome UA and I am not sure how we can further anonymize that. 
 
Background on why we use Chrome UA: because of google ads shown to 'install chrome', as well as google news and search appearing differently (in a way that users didn't like) when not using Chrome UA.
