### ISSUE TITLE
update to HTTPS Everywhere 5.2

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-ios#367]
the data file is now at https://s3.amazonaws.com/https-everywhere-data/5.2/httpse.sqlite. @garvankeeley this has your unique ruleset sqlite fix.

**Comment by garvankeeley** [comment]
👍 fixed in this commit: https://github.com/brave/browser-ios/commit/77211eb7493ad29d53fe179a4d9e2238b96c772b
