### ISSUE TITLE
for left side bar (bookmarks etc) add icons for selected state for tab bar for clarity

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-ios#369]
also, following iOS guidelines
https://developer.apple.com/ios/human-interface-guidelines/graphics/custom-icons/
Provide two versions of custom tab bar icons. Provide icons for both the selected and unselected states. 

@bradleyrichter  what do you think?

(image included to clarify the type of thing I'm talking about, not suggesting it be done this way -- just a quick & dirty mod on the original)

![tab-sample](https://cloud.githubusercontent.com/assets/420063/17748013/45d032cc-646c-11e6-84cb-12874a86851d.png)

**Comment by bradleyrichter** [comment]
agree that we need something in addition to the nub.

**Comment by diegodoval** [comment]
moving off the bookmarks milestone, this is separate

**Comment by garvankeeley** [comment]
QA for this could be to check that the selected and unselected state of the bookmarks and history icons in the left side panel looks ok.
