### ISSUE TITLE
bookmarks code - fix UI/data dependency

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-ios#375]
In onClickBookmarksButton of MainSidePanelViewController.swift there's a portion of code that relies on the state of a UI button to decide whether to add or remove the bookmark. The state of the UI should not dictate which path to take -- a DB check should

```
        if addBookmarkButton.selected {
            browserViewController?.removeBookmark(url)
        } else {
            browserViewController?.addBookmark(url, title: tab.title)
        }
```

**Comment by garvankeeley** [comment]
No plans to fix, will change inherently when code gets refactored to next gen-UI that is being planned.
