### ISSUE TITLE
App handlers are re-triggered on launch.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#382]
Description:
If an app has been launched from Brave (ex: Netflix), the next time Brave is launched, the other launched app will open and the user will have to return to Brave.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
The app handler should not re-trigger.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone6s plus

- Brave Version:
1.2.13

- Steps to reproduce:
    1. Visit Netflix.com and launch the app
    2. Return to Brave
    3. Background the tab by opening another tab
    4. Close Brave (long hold and swipe up)
    5. Re-launch Brave

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
![ios_app_handler](https://cloud.githubusercontent.com/assets/1434040/18055066/230f5006-6dcc-11e6-8b00-29cff7570147.gif)

- Any related issues:

**Comment by garvankeeley** [comment]
Closing as alex and I can't repro.
