### ISSUE TITLE
Can't scroll to see content at very bottom 

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-ios#393]
Description:
Can't scroll to very bottom of a page because the UI covers a portion of it

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
The UI should adjust the scroll offset enough that I can continue to scroll and see the bottom of the page

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone SE

- Brave Version:
1.2.13

- Steps to reproduce:
    1. Open this issue in GitHub on an iPhone SE or similar
    2. Ensure you're in the mobile view
    3. Try to scroll to bottom where the "desktop view" link is
    4. Notice you can't click it because you can never scroll down far enough :frowning: 

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
Notice the nav bar on bottom blocks the content and I can't see "switch to desktop mode".  It's right below the sign in button
![image](https://cloud.githubusercontent.com/assets/4733304/18209063/02817e9a-70e7-11e6-90e8-9011e925afac.png)

- Any related issues:

**Comment by garvankeeley** [comment]
I can't repro it with fix in for https://github.com/brave/browser-ios/issues/414, please on next beta and reopen if it happens
