### ISSUE TITLE
Individual Controls reset

### ISSUE THREAD

**Issue by pwnsdx** [brave/browser-ios#395]
Hello,

Description:

I think it could be a good idea to add a switch in "Clear Private Data" to reset individual controls settings and resetting individual controls on exit when changing it is in private mode.

Brave Version: 1.2.13

Steps to reproduce:
     1. Change Individual Controls settings for one website in Private-mode only
     2. Quit the app
     3. Go back on that website in private or normal mode, changes made to Individual Controls are still here

**Comment by pwnsdx** [comment]
Hello,

Thanks you for the "top bug!" label :smile: :+1: 

I see that you fixed the PB mode but what about normal mode? Are Individual Controls cleared upon "Clear Private Data" setting?

Regards,

**Comment by garvankeeley** [comment]
They are cleared
