### ISSUE TITLE
'Open in Brave' causing blank pages that won't reload

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#403]
Page blank, reloading does not load anything (stays blank).

User reports:

```
I open a link from Twitter and switch back into Twitter while the page is still loading in Brave.
When I switch back into Brave a few hours later when I have some time to read the articles
 that I've opened, some of them won't refresh via the two methods mentioned above.
```

**Comment by garvankeeley** [comment]
@alexwykoff i can't repro (I think the report is that this is intermittent)

**Comment by jonathansampson** [comment]
I might be seeing this myself here lately; in standard and private browsing. Usually requires me to hit the back button once or twice for it to resolve, and begin painting again. Note, in my experience I start in the browser--no transitioning from one app to another.

**Comment by srirambv** [comment]
Cant repro steps mentioned in https://github.com/brave/browser-ios/issues/403#issuecomment-277494604. Works fine on 1.4.2. Closing as DNR
