### ISSUE TITLE
Bookmarks stays in edit mode after closing panel if swipe to edit was used

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-ios#404]
Bookmarks stays in edit mode after closing panel if swipe to edit was used, STR: swipe to expose edit button, press edit, tap on webview so that panel closes, re-open panel.

**Comment by srirambv** [comment]
Reopening the issue. Brave crashes when the steps are repeated.

**Comment by diegodoval** [comment]
@srirambv the fix isn't integrated anywhere yet! :) currently we close the bug when the fix is pushed to branch at github.
