### ISSUE TITLE
Certain favicons are overflowing on topsites. 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#408]
Description:
After visiting wordcounter.net, it is added to the topsites view. It was noticed that the favicon was oversized for the bounding box.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
The favicon should match the shape of all other favicons.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Tested on iPhone5

- Brave Version:
1.2.15

- Steps to reproduce:
    1. Visit wordcounter.net.
    2. Attempt to create a new page.
    3. Observe the displayed topsites.

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
<img width="353" alt="screen shot 2016-09-07 at 12 51 50 pm" src="https://cloud.githubusercontent.com/assets/1434040/18323209/210f5742-74fc-11e6-861a-0d95f8e0fffc.png">

- Any related issues:

**Comment by jamesmudgett** [comment]
This was fixed in commit ([3de556208da90ca9c5f363c3a138ff626c7064aa](https://github.com/brave/browser-ios/commit/3de556208da90ca9c5f363c3a138ff626c7064aa)

**Comment by garvankeeley** [comment]
Nice!
