### ISSUE TITLE
Can't click link if at the bottom of a page

### ISSUE THREAD

**Issue by jkup** [brave/browser-ios#414]
Description:

**Did you search for similar issues before submitting this one?**

Yes, this seems related to #393 but somewhat different.

**Expected behavior:**

I should be able to click on the links I see at the bottom of a page.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

iPhone6s

- Brave Version:
1.2.14(16.09.03.13)

- Steps to reproduce:
    1. go to a github.com page that requires scrolling (most repos will work)
    2. try to click the "Desktop version" link at the bottom
    3. see that it brings up the new tab chrome

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
![img_4133](https://cloud.githubusercontent.com/assets/490294/18363846/b5725cf8-75c0-11e6-804b-5fc147ebde6b.PNG)

- Any related issues:

Somewhat #393

**Comment by garvankeeley** [comment]
I see it after showing bottom toolbar, the page can't be scrolled up, only on github can i repro,
sample page: https://github.com/brave/browser-laptop

**Comment by jkup** [comment]
Why was this closed? I still can't click the desktop version link. It's not that I don't see it its that clicking it triggers the toolbar.

**Comment by garvankeeley** [comment]
see above commit 53abd68, if a commit starts with "Fix #xxx" the bug is closed. So it is closed because the commit fixes the bug. Next beta will mention this bug number for reference.

**Comment by jkup** [comment]
@garvankeeley so sorry! was using github mobile web (which I'm not used to) and the hash is so subtle I didn't even see it!

**Comment by jkup** [comment]
@garvankeeley I'm having this problem again, still with long github mobile pages.

**Comment by jkup** [comment]
Any update on this? I still can't click links at the bottom. I have an iPhone 6 on version 1.2.15 of Brave. Let me know if I can help with reproducing!

**Comment by garvankeeley** [comment]
it is fixed for 1.2.16 milestone, which ready for the app store yet. I'll invite you to the beta group so you can test this out.

**Comment by jkup** [comment]
Two blunders in one ticket... I'll see myself out.

Thanks for the invite to beta @garvankeeley

**Comment by garvankeeley** [comment]
Ha! np, we are into overtime on 1.2.16, it was supposed to be out this week
