### ISSUE TITLE
The first letter is duplicated in URL bar in non-alphabet language

### ISSUE THREAD

**Issue by watarumohawk** [brave/browser-ios#415]
Description:

When users type non-alphabet languages, such as Japanese and Chinese, the first letter is duplicated.
This issue occurs when there are strings in URL bar. If URL bar is empty, this issue doesn't occur.

**Expected behavior:**

When users enter non-alphabet languages, the first letter is not duplicated.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

I think that this issue doesn't depend on kind of device.

- Brave Version:

1.2.14

- Steps to reproduce:

1. Add a new keyboard 'Japanese - Romaji' in Settings
2. Open Brave
3. Change the keyboard to '日本語ローマ字' (Japanese - Romaji).
4. Tap URL bar
5. Type something, for example 'nihongo', and tap "確定" & "開く" (Go) button. Both buttons are blue
6. After the result page is loaded, tap URL bar again
7. Type something, for example 'nihongo'
8. You can confirm that the first letter is duplicated

- Screenshot if needed:

Step 5:
After you type 'nihongo' all, you can see this.

![simulator screen shot 1](https://cloud.githubusercontent.com/assets/4612196/18375815/902e8370-7694-11e6-835f-1136c972efb6.png)

Step 6:
![simulator screen shot 2](https://cloud.githubusercontent.com/assets/4612196/18375822/95b5a2ec-7694-11e6-9307-10d3dde77dc4.png)

Step 8:
![simulator screen shot 3](https://cloud.githubusercontent.com/assets/4612196/18375825/9a1abf5c-7694-11e6-8826-0ecffaa8da77.png)

![simulator screen shot 4](https://cloud.githubusercontent.com/assets/4612196/18376124/f4c6040a-7696-11e6-9039-41c61dd4939d.png)

**Comment by garvankeeley** [comment]
Also reported here #240

**Comment by garvankeeley** [comment]
see https://bugzilla.mozilla.org/show_bug.cgi?id=1266628
