### ISSUE TITLE
Tap on hamburger menu brings down the URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#420]
Description:
Tap on hamburger menu brings down the URL bar

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Menu should slide out when tapped on the hamburger menu but shouldn't bring down the URL bar.
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
  iPhone 6
- Brave Version:
  1.2.15
- Steps to reproduce:
  1. Visit http://espnfc.com
  2. Scroll down the page so that the URL bar is hidden
  3. Tap on the hamburger menu on the top left corner 
  4. The menu slides out and brings down the URL bar

*\* Website problems only:
- did you check with Brave Shields down? Yes
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? Checked on Dolphin menu slides out without bringing down the URL bar
- Screenshot if needed:
- Any related issues:

**Comment by garvankeeley** [comment]
The menu tap on this site, is interpreted as a navigation, and on navigation events, app shows the top toolbar.

**Comment by jamesmudgett** [comment]
This is an issue with the way they coded their site and we shouldn't intervene here: Their site open navigation code sets the page height to something that's smaller than our allowed scroll height (surpasses minimum height which requires that we show the header or we'd end up with sites that are shorter than device to hide scrollbars)
