### ISSUE TITLE
Naming: 'open in background tab' should be 'open in new tab'

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#429]
Open in a new tab is more clear.  Especially when there is open in a new private tab.  A friend didn't know what background tab meant so thought we only offer open in private tabs option.

**Comment by garvankeeley** [comment]
Agreed, not a fan of the wording, @jamesmudgett and @alexwykoff for more opinions.

**Comment by bbondy** [comment]
ya I'd just go with that, the exact wording on laptop is: "Open Link in New Tab" if you wanted to keep it consistent across products.   We could alter add an option to control how it opens (in background or not), but calling it open in a new tab is not wrong, it does that whether background or not.
