### ISSUE TITLE
Make tab switches easier from about:home

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#43]
Also from a tester: 

when you're under about:home and want to switch to tab that's still currently opened, there's no way of doing that because there's no visible "tabs" UI.. 

Example:
from about:home, visit google.ca
from google.ca, open a new tab
from about:home, visit duckduckgo.com
from duckduckgo.com, open a new tab

now I'm under about:home with two tabs opened.. I want to switch to one of those tabs.. there's no way of doing that right now unless I load another page and from there, I click on the "Tab View" button from the UI that slides from the bottom

**Comment by bradleyrichter** [comment]
@bbondy Can you explain what you mean by "about:home"? Does this mean when entering text in the URL bar?

**Comment by garvankeeley** [comment]
In 1.1 the tab switcher is no longer hidden, I think this can be closed
