### ISSUE TITLE
App becomes unresponsive when a top site is not deleted after long press

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#437]
Description:
App becomes unresponsive when a top site is not deleted after long press

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
App should work as before

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10)

- Brave Version:
1.2.15

- Steps to reproduce:
    1. Long press on top sites till the delete site option is shown
    2. Do not delete any site and tap to close 
    3. Tap on new tab creates a new tab increases tab count but doesn't bring up the keyboard.
    4. Unable to open bookmarked sites 
    5. Unable to tap on any of the existing top sites

Need to kill app and restart again to work normally

** Website problems only: No
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
i just repro'd on ios 9
