### ISSUE TITLE
Brave is not available as a link-handler option for many iOS apps on long-press share destinations

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-ios#438]
Many user-links that open Safari are coming from mail and there does not appear to be any way to intercept. Although, Slack and Asana are in the share list. 

Maybe we need to spoof it with the approach slack is using?

![image](https://cloud.githubusercontent.com/assets/13509546/18685207/e9ee5094-7f2b-11e6-98dd-3550709e4e33.png)

**Comment by Jacalz** [comment]
+1 from me, really annoying

**Comment by srirambv** [comment]
+1 from community user alwillis 
https://community.brave.com/t/open-in-brave-share-option/13116/5

**Comment by bradleyrichter** [comment]
@jamesmudgett Can you dig into this one soon? We should fill as many of these holes as possible.
