### ISSUE TITLE
Disabling Private Browsing Only still creates new private tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#439]
Description:
Disabling Private Browsing Only still creates new private tabs

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
After disabling should close all private tabs and create non private tabs similar to when user manually taps on Private in the new tab screen
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
  iPhone 6 (iOS 10)
- Brave Version:
  1.2.15
- Steps to reproduce:
  1. Enable "Private Browsing Only" from settings
  2. Close App and restart to check if it has the private browsing indicator in the URL bar
  3. Disable "Private Browsing Only" from settings
  4. Tap on the + icon to create new tabs. New tab count increases and still creates private tabs
  5. User has to go to tab previews and manually remove Private to go back to non private tabs

*\* Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A
- Screenshot if needed:
- Any related issues:

**Comment by garvankeeley** [comment]
By design, but clearly is confusing. UX thought is needed here, I am not sure what to do. We could just kill all the current private tabs, but the switch isn't named to indicate that.
