### ISSUE TITLE
Search bar doesn't snap to bottom when keyboard is hidden

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#444]
Description:
Search bar doesn't snap to bottom when keyboard is hidden

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should snap to bottom of screen when user scrolls up/down when the keyboard is hidden
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
  iPhone 6 (iOS 10)
- Brave Version:
  1.2.16(16.09.22.11) Beta
- Steps to reproduce:
  1. Open any page
  2. Tap on share and tap on find on page
  3. Search for a term and then hide the keyboard, search bar is fixed at the same location, doesn't snap to the bottom of the screen

*\* Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18756068/6228c3a8-80e6-11e6-9166-d61f005283f0.png)
- Any related issues:

**Comment by jamesmudgett** [comment]
QA and Close

**Comment by srirambv** [comment]
Closing as DNR on 1.4.2
