### ISSUE TITLE
Top Sites: is based on page visits, not domain visits, see if this can be changed

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#446]
I thought the top sites frecency query was based on a domain visit count, but it is a count of visiting a specific page, which isn't what we want. Regardless of having visited site.com/url1,  site.com/url2, or site.com/url3, we want site.com to appear on the top sites.

**Comment by garvankeeley** [comment]
I think it is good enough for 1.2.17, we can bump forward

**Comment by jamesmudgett** [comment]
Our logic was refactored with switch to CoreData.

**Comment by jhreis** [comment]
Closing per above comment.
