### ISSUE TITLE
Brave crashes when bookmark is in edit mode and user tries to close the panel

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#448]
Description: Brave crashes when bookmark is in edit mode and user tries to close the panel

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should come out of bookmark edit mode and close the panel

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10)

- Brave Version:
1.2.16 Beta

- Steps to reproduce:
    1. Open bookmark panel
    2. Swipe the bookmark to left and tap on edit
    3. Tap on the vebview to close the panel when in edit mode, Brave craashes

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:

- Any related issues:

**Comment by diegodoval** [comment]
Fixed on branch bm-fixes
