### ISSUE TITLE
Navigating bookmark folder ugly: Back button title is "Bookma..." then changes to "Bookmarks"

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#463]
Description:Provide better animation when navigating between bookmark folder and back

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should show Bookmark instead of showing Bookma... and then showing Bookmark 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:

- Steps to reproduce:
    1. Open a bookmark folder
    2. The bookmark text shows Bookma... and then loads Bookmark
    3. Directly show Bookmark rather than Bookma.. and then Bookmark

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:
#436

**Comment by garvankeeley** [comment]
@jamesmudgett for this or next release, up to you, thanks

**Comment by garvankeeley** [comment]
This got fixed during last night's rush
