### ISSUE TITLE
Bookmark: Re-positioning added bookmark into a folder position behaves as a folder

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#465]
Description:Re-positioning added bookmark into a folder position behaves as a folder.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Swiping a bookmark should show edit and should not have a folder action

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.16(16.09.29.00)

- Steps to reproduce:
    1. Create 3 Bookmark folders Test1,Test2,Test3
    2.  Open a page and bookmark it.
    3. While on the page tap on edit and move the bookmark to Test2 folder location
    4. Tap on Done. Go back to menu and swipe on the bookmark behaves as a folder and naviigates into the folder and shows the folder name
    5. Tap on edit, the last folder(Test3) shows the remove icon next to it like a bookmark

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18973918/0286ab92-8698-11e6-819c-847af0e9d45c.png)

Video: http://sendvid.com/wz81ab31

- Any related issues:

**Comment by garvankeeley** [comment]
fixed by  2b99841dbfb6c1b6c5b146bd1d7276d6caa67223
