### ISSUE TITLE
Keyboard doesn't come up for new tab if the current tab is not loaded completely

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#473]
Description: Keyboard doesn't come up for new tab if the current tab is not loaded completely

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should bring the keyboard for a new tab irrespective of the current load state of the active tab
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
  iPhone 6 (iOS 10)
- Brave Version:
  1.2.16(16.09.30.10)
- Steps to reproduce:
  1. Open any page (manually type or tap on the top sites) 
  2. Wait for it to load and press + to launch a new tab keyboard comes up automatically
  3. Open a different page in a new tab 
  4. Before the page is loaded tap on + to create a new tab, keyboard doesn't automatically come up

*\* Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A
- Screenshot if needed:
- Any related issues:

**Comment by garvankeeley** [comment]
Dev note: iOS 10-only so make sure to use that when fixing

**Comment by garvankeeley** [comment]
I can't repro, is this reliably repro'd?

**Comment by jamesmudgett** [comment]
Seeing this happen after tapping + new tab on bottom toolbar, keyboard seems to try to open then closes immediately.

**Comment by srirambv** [comment]
No longer happening on 1.3.2. Closing for now.
