### ISSUE TITLE
Keyboard does't auto hide when view changes from URL to Menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#474]
Description:Keyboard does;t auto hide when view changes from URL to menu

**Did you search for similar issues before submitting this one?** Yes

**Expected behavior:**
When view is changed to menu, keyboard should automatically hide

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.16(16.09.30.10)

- Steps to reproduce:
    1. Open a new tab and make sure the keyboard pops up automatically
    2. Open menu by tapping on the hamburger menu
    3. Keyboard remains in focus until you scroll bookmarks/scroll history or tap on settings

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
Dev note: Focus is staying in the location bar, make sure it loses first responder status
