### ISSUE TITLE
Suggestion : Release Process - Start publishing betas on the /releases page so users can side-load and help with QA

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#479]
Description:
In order to scale our test efforts, we need to make it easier for users to get the latest builds onto their devices.

**Did you search for similar issues before submitting this one?**

**Expected behavior:**
Similar to laptop, we should publish our .ipa files on /releases

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All

- Brave Version:
`> 1.2.16`

**Comment by alexwykoff** [comment]
cc @garvankeeley

**Comment by garvankeeley** [comment]
Not sure I understand as we are using Crashlytics as the easy/scaleable method for Beta testing. 
With some more info as to what improvements you are looking for, I can see if we can get better use out of Crashlytics.
