### ISSUE TITLE
Highly Pixelated Fav Icons 

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-ios#481]
https://files.slack.com/files-pri/T04PX1BU8-F2J3QNUHK/slack_for_ios_upload.png 

Fav icons seem to be scaled more than usual. Find a way to improve top-sites fav icon display.

**Comment by garvankeeley** [comment]
Can you mark fixed and link the commit/PR?

**Comment by jamesmudgett** [comment]
Fix PR: https://github.com/brave/browser-ios/pull/487
