### ISSUE TITLE
Thumbnails disappearing for Sky Sports

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#49]
I'm not sure how to reproduce this but sometimes when I'm trying to browse through football news, the thumbnails aren't loaded... Trying the same thing with FX works and loads all the thumbnails without issues.. I did notice that I received a message about the website using cookies under fx.. Maybe this is affecting Brave some how?

Take a look at the screenshots.. Always happening on Sky Sports
![img_0155](https://cloud.githubusercontent.com/assets/831718/11319751/c65a0c02-904f-11e5-849a-3b5fa7b07d22.jpg)

![img_0156](https://cloud.githubusercontent.com/assets/831718/11319752/c91d5b1a-904f-11e5-8b44-416018c14266.jpg)

**Comment by garvankeeley** [comment]
Closing, I am not longer seeing this.
