### ISSUE TITLE
Brave crashes when creating a bookmark folder

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#491]
Description:Brave crashes when creating a bookmark folder

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should create bookmark folder and should not crash

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.12.16(16.10.11.13)

- Steps to reproduce:
    1. Tap on edit in the bookmark pane
    2. Tap on new folder. 
    3. Enter the folder name and tap on ok, App crashes

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
This is only crashing in the Beta or also the release?

**Comment by srirambv** [comment]
Beta. Sorry missed it while adding the issue.
