### ISSUE TITLE
Adding bookmark doesn't show it immediately in the bookmark list

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#492]
Description:Adding bookmark doesn't show it immediately in the bookmark list.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should show the bookmarked item in the bookmark list and should show the bookmark icon for the bookmarked page

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10)

- Brave Version:
1.12.16(16.10.11.13) Beta

- Steps to reproduce:
    1. Open any page 
    2. Tap on the bookmark icon, doesn't show the entry in the bookmark list
    3. Tap to close the left pane and open the bookmark menu, page is added as a bookmark
    4. Bookmark icon not shown on the page
    5. Kill the app and launch again shows the bookmark icon on the page

** Website problems only: NA
- did you check with Brave Shields down? NA
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? NA

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
Another Beta bug during Xcode8 porting, was fixed
