### ISSUE TITLE
[beta] App  becomes unresponsive when changing from Private browsing to normal browsing

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#495]
Description: App hangs when changing from Private browsing to normal browsing

**Did you search for similar issues before submitting this one?** Yes

**Expected behavior:** Should be able to select the normal tabs when private browsing is turned off

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.16(16.10.11.13) Beta

- Steps to reproduce:
    1. Open several sites on normal tabs 
    2. Open a private tab and browse to a site
    3. Close the private tab, app keeps showing the loading icon. Doesn't go back to normal tabs opened before and becomes unresponsive
    4. Background the app and relaunch, same state. 

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
still happening on v1.2.16 (16.10.12.17). Reopening the isssue

**Comment by srirambv** [comment]
Additional steps to repro 

1. Launch the app fresh
2. Go to options and enable Private mode only
3. Open 3-4 empty tabs in private mode
4. Go back to settings and disable private mode only
5. Tap on the tab count and tap on Private to exit private mode
6. App hangs in loading state

**Comment by garvankeeley** [comment]
I can't get this to hang, tried multiple times. Can you screencap it, there may be some seemingly minor detail in the process you follow that I am missing in my repro steps.
The build I am trying it with is BraveBeta 16.10.18.11, on iOS 10 iphone 5

**Comment by garvankeeley** [comment]
I have it reproduced. I start app, go into private mode, then switch to safari and do 'open in brave', then in Brave again, exit private mode.

**Comment by srirambv** [comment]
Seems to be an intermittent issue. Whenever I try to record the steps it doesn't work and when I don't record the steps it hangs. Here's what I tried now and it hanged(again didn't record this time)
1. Launch app fresh
2. Switch from normal to private mode by tapping on the tab count
3. Enable Private mode only from settings
4. Open a new tab in private mode
5. Disable private mode only from settings
6. Tap on tab count and tap on private to exit private mode
7. App hangs in loading state
