### ISSUE TITLE
Shields icon is not disabled on a new tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#496]
Description: Shields icon is not disabled on a new tab

**Did you search for similar issues before submitting this one?** Yes

**Expected behavior:**
Should show the disabled icon on a new tab. Only enable it when a site is opened
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
  iPhone 6 (iOS 10)
- Brave Version:
  1.2.16(16.10.11.13) Beta and the app store version
- Steps to reproduce:
  1. 
     2.
     3.

*\* Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?
- Screenshot if needed:
- Any related issues:

**Comment by jhreis** [comment]
I think this was taken care of by: #599 

Not disabled, but adjusted functionality.

**Comment by garvankeeley** [comment]
true, fixed as part of #599
