### ISSUE TITLE
Logic / design issue on configuration changes in the 'Settings' of Brave Browser does not 'take effect'

### ISSUE THREAD

**Issue by lccunha** [brave/browser-ios#498]
I realized that when I change the language or the home page in the browser settings changes have no effect. This only happens after restarting the browser. This is unusual and there is a warning about it in this area.

I think the ideal would be: automatically change or create a warning message that these changes will take place after restarting the browser.

**Comment by garvankeeley** [comment]
Are you sure this bug is for the iOS browser?

**Comment by garvankeeley** [comment]
I'll close as I think this bug is for a different product

**Comment by lccunha** [comment]
I actually sent to the wrong page. Excuse me
