### ISSUE TITLE
provide a method to do basic ad -> install attribution without 3rd-party tracking

### ISSUE THREAD

**Issue by bridiver** [brave/browser-ios#499]
We would like to know which sites and ads are driving Brave installs, but Brave's anonymous attribution system isn't supported by other browsers. For privacy reasons we don't want to include 3rd-party tracking in our ads so we need a reasonably anonymous alternative. A non-identifiable cookie (only contains site/ad related information and timestamp is truncated to the day) will be set on ad view/click in the brave.com domain. 

When Brave for ios is installed and run for the first time, a welcome screen will be shown that has a checkbox which allows the user to opt-out of any sharing of usage statistics with Brave. If the user does not opt out, the browser will make a request to brave.com (url TDB) in the background using the safari webview controller. We will not send the ad id or any other unique identifier in the request (this will be verifiable in the source code). No attempt will be made to link the original ad view/click with the install notification request through IP or any other method. Only the aggregate counts of ad views/clicks vs installs from each day/site/ad combination will be available. 

If users wish to opt-out of the ad -> install attribution prior to install, an opt-out url will be available at brave.com that will set the cookie value to OPT_OUT with a 1 year expiration time.  No ad views/clicks/installs will be collected that happen after the opt-out for as long the cookie still exists

**Comment by garvankeeley** [comment]
I think i have this setup, what URL do I use?

**Comment by garvankeeley** [comment]
fixed by: 71ce0e261830006d6dca9dacec9ceffb71d3aa90
