### ISSUE TITLE
Able to create bookmark folder without name

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#513]
Description: Able to create bookmark folder without name

**Did you search for similar issues before submitting this one?** Yes, didn't find any

**Expected behavior:**
Should not allow to create a bookmark folder without name
- Device (iPhone5, iPhone6s plus, iPad 3, ?): 
  iPhone 6 (iOS 10)
- Brave Version:
  1.2.16(16.10.19.15)
- Steps to reproduce:
  1. Tap on Bookmark icon
  2. Tap on Edit, Tap on newfolder
  3. Tap on save without entering name, creates a folder without any name

*\* Website problems only: NA
- did you check with Brave Shields down?NA
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?NA
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/19589874/73eb0bde-978c-11e6-9f39-47a5dafe9162.png)
- Any related issues:

**Comment by garvankeeley** [comment]
We should see how other browsers handle this. Perhaps no-name folders are actually ok?
