### ISSUE TITLE
Share action: mail has no URL in body, twitter no url either (just titles are set)

### ISSUE THREAD

**Issue by unsystemizer** [brave/browser-ios#516]
Description:

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Mail-shared page has no URL in body (just URL title is in Subject)

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad Pro 9.7"

- Brave Version:
1.2.16

- Steps to reproduce:
    1. Navigate to a page (e.g. this very page)
    2. Share the page via "Mail"
    3. Mail body is empty (except for the Mail client signature, if any)

** Website problems only:
- did you check with Brave Shields down? Yes
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? Checked in Safari, no issues

- Screenshot if needed:
No

- Any related issues:

**Comment by garvankeeley** [comment]
Twitter share has the same problem, fixing both now
