### ISSUE TITLE
shields switch has missing background image when disabled

### ISSUE THREAD

**Issue by bridiver** [brave/browser-ios#525]
Description:
In "site shield settings" if you turn shields off the switch loses the background and doesn't look like a switch anymore

**Did you search for similar issues before submitting this one?**
Yes

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iphone 6

- Brave Version:
1.2.16

![slack_for_ios_upload png](https://cloud.githubusercontent.com/assets/34129/19736442/143c7fb6-9b64-11e6-95fd-106bef42694b.jpeg)

**Comment by garvankeeley** [comment]
fixed by 145eb0c
