### ISSUE TITLE
Brave is blocking facebook images

### ISSUE THREAD

**Issue by leolorenzoluis** [brave/browser-ios#526]
Description:

When viewing facebook website the images are not loaded when block ads and tracking is on.

**Expected behavior:**

- iPhone 7

- Brave Version: latest version

- Steps to reproduce:
    1. Open facebook website
    2. View the news feed
    3. Images are not loading

** Website problems only:
- did you check with Brave Shields down? Yes
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? No
- Screenshot if needed:

- Any related issues: N/A

**Comment by garvankeeley** [comment]
Was a temporary glitch with a trackingprotection rule update, should be ok now, thanks for reporting!
