### ISSUE TITLE
1Password button looks disabled even after installing the 1Password app

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#531]
Description:
1Password button looks disabled even after installing the 1Password app

**Did you search for similar issues before submitting this one?** Yes

**Expected behavior:**
Should only be disabled when the app is not installed

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.17

- Steps to reproduce:
    1. Open any login site
    2. Tap on the input field to enable the keyboard
    3.  Shows disabled button. 

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19870250/b42cabf8-9fa7-11e6-9649-0ce6c9786a43.png)

- Any related issues:

**Comment by jamesmudgett** [comment]
PR https://github.com/brave/browser-ios/pull/534
