### ISSUE TITLE
Selecting save credentials on snackbar popup doesn't store the credentials

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#532]
Description: Selecting save credentials on snackbar popup doesn't store the credentials

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should save the credentials and auto populate on next visit

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.17

- Steps to reproduce:
    1. Open any login page and tap on 1Password button in the popup keyboard 
    2. Select stored credentials from 1Password to auto populate in the login screen
    3. Tap on login, shows the snackbar popup at the bottom of the screen
    4. Select save credentails
    5. Visit the same site, credentials are not auto populated which was saved in step 4

- Screenshot if needed:

- Any related issues:
 
 cc: @jamesmudgett

**Comment by garvankeeley** [comment]
Autofill does seem broken, tried on twitter.com. Bisecting with older build to see when it broke
