### ISSUE TITLE
[Beta]1Password button shown by default even when 3rd party password manager is set to don't use

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#535]
Description: 
1Password button shown by default even when 3rd party password manager is set to don't use

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should not show 1Password button unless it is set under 3rd Party password manager

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone6 (iOS 10)

- Brave Version:
v1.2.17 (16.10.31.18)

- Steps to reproduce:
    1. Do a clean install of v1.2.17 (16.10.31.18)
    2. Open any login page
    3. Tap on the login field to bring bring up the keyboard
    4. 1Password button is shown, go to settings, 3rd party password manager is default set to don't use

- Screenshot if needed:

- Any related issues:
 cc: @jamesmudgett

**Comment by garvankeeley** [comment]
Commit 0280f38 fixed that the button was always showing. 
Still the question remains if we should be showing the 1PW button if 1PW is detected to be installed, which it does currently. My thinking was that this would help discoverability.

**Comment by srirambv** [comment]
Is it possible to show a snackbar notification on clean launch to inform to select 1Password/LastPass if the respective app is detected?

**Comment by srirambv** [comment]
@garvankeeley This doesn't look fixed on v1.2.17 (16.11.01.17) even when the password managers disabled in the share screen. 

http://sendvid.com/v6qzojyd

**Comment by garvankeeley** [comment]
That looks correct, the password manager setting is changed for the new button behaviour.
If 1PW/lastpass is installed, the button will always show, the setting now just changes the behaviour of the button press.

![screen shot 2016-11-01 at 4 50 15 pm](https://cloud.githubusercontent.com/assets/5495083/19933997/9ef8a8c8-a0eb-11e6-96b8-07761c1341d9.png)
![screen shot 2016-11-01 at 4 50 12 pm](https://cloud.githubusercontent.com/assets/5495083/19933996/9ef8358c-a0eb-11e6-93c2-f60ab2deac7b.png)

**Comment by jhreis** [comment]
This has been improved via 21b7308.

Key icon is shown by default (opens 'share' menu), and if the user selects a password manager, that PM is set to default. If the user ever explicitly sets "Show Picker" than that sticks and will _always_ show the general Key icon.
