### ISSUE TITLE
Email/Confirm Email field hidden by keyboard on ebay.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#539]
Description: Email/Confirm Email field hidden by keyboard on ebay.com

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should scroll page and show keyboard after all form elements 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10)

- Brave Version:
v1.2.17 (16.11.01.17)

- Steps to reproduce:
    1. Visit ebay.com 
    2. Add a product to cart and checkout
    3. Enter details in the shipping address, Only fields till Mobile is visible with active keyboard
    4. Hide keyboard and tap on Email field, keyboard comes up and the field is hidden behind the keyboard.  User will have to blindly enter and hide keyboard to see if its entered correctly.

** Website problems only: Yes
- did you check with Brave Shields down? NA
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? Check on Puffin & Dolphin keyboard is shown after form elements (see attached screenshot)

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19934185/b09adbce-a10d-11e6-865d-f10bbe573bdf.png)

- Any related issues:

**Comment by srirambv** [comment]
Happens on Instagram as well. Opening a photo from a user and tap on the comment field. Keyboard pops up and hides the comment field.

**Comment by bridiver** [comment]
also Facebook and many other sites. A similar problem happens sometimes at the bottom of the screen with the navigation bar. This seems like a high-priority issue to me because it makes popular sites like Facebook almost unusable

**Comment by garvankeeley** [comment]
@jamesmudgett can you take a look

**Comment by jamesmudgett** [comment]
PR https://github.com/brave/browser-ios/pull/609
