### ISSUE TITLE
Unable add bookmark after unlocking phone with Brave as the active app

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#545]
Description:
Unable add bookmark after unlocking phone with Brave as the active app

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should be able to add it as a bookmark

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.27(16.11.01.18)

- Steps to reproduce:
    1. Open Brave and open a site, check if you can add and remove it as bookmark
    2. Lock the phone and unlock 
    3. With the active page on Brave, tapping on the bookmark icon doesn't allow you to add it as a bookmark

- Screenshot if needed:
http://sendvid.com/ej11ahn7

- Any related issues:

**Comment by garvankeeley** [comment]
Do you see history being added? If not, then we know the db is closed and not re-opening properly

**Comment by garvankeeley** [comment]
Note: History also is not updating. likely the db connection is closed, then not re-opened again

**Comment by srirambv** [comment]
Here's the screen grab for the history not getitng stored http://sendvid.com/3759zhkh
