### ISSUE TITLE
Empty div shown on Facebook chat when keyboard pops out

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#548]
Description: Empty div shown on Facebook chat when keyboard pops out

**Did you search for similar issues before submitting this one?**
yes

**Expected behavior:**
There should not be any empty space between keyboard and the chat window

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10)

- Brave Version:
1.2.17

- Steps to reproduce:
    1. Login to Facebook on Brave
    2. Open any chat
    3. Tap on the input filed, the screen moves up as keyboard pops up and has a big empty div

** Website problems only: Yes
- did you check with Brave Shields down? Yes
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? No such issue on Dolphin and Puffin

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19945531/76d70e32-a138-11e6-8a9f-1c635caed3c3.png)

- Any related issues:

**Comment by garvankeeley** [comment]
This is due to our work around for: https://github.com/brave/browser-ios/issues/125

We could try removing it and see if the case happens where sometimes the message box  is ending up behind the keyboard, with no ability to scroll the page to show it.

**Comment by garvankeeley** [comment]
Fixed in 1.2.19

**Comment by srirambv** [comment]
@garvankeeley  This is how it looks in build 1.2.19(16.12.29.15) The empty div is not shown like before but is this expected??

![image](https://cloud.githubusercontent.com/assets/17010094/21555737/bd4b15fa-ce12-11e6-8b4f-3d3698cb2af4.png)

**Comment by garvankeeley** [comment]
@jamesmudgett? IIRC this is correct behaviour. The page is scrolled up to ensure KB doesn't cover the element. I don't recall why the code over-compensates for this. Without this code, the text field is behind the KB and can't be scrolled up
