### ISSUE TITLE
Stuck on top sites screen after bringing app to foreground

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#563]
This is new in 1.2.17 AFAIK.
I don't know the STR but this is quite serious, it has happened twice since 1.2.17 has been out. 
The app is fully `live` but appears frozen as loading sites by tapping on top sites will change the url (and load in the background) but not dismiss the top sites.

@srirambv @alexwykoff help to repro?

**Comment by garvankeeley** [comment]
Maybe is due to lock screen behaviour? We saw issues with that just before 1.2.17 went out.

**Comment by srirambv** [comment]
@garvankeeley  I cant repro this on 1.2.17. Tried with PB mode and normal mode but no luck. The app is responsive all the time. Is this happening on the default top sites or the new ones that get added?

**Comment by garvankeeley** [comment]
Default or new top sites it doesn't matter, happens to both. It happened when I hadn't used my phone for a bit, 20-30 mins, unlocked, and I can't recall if Brave was foreground immediately, or if i *then* foregrounded the app. I am often switching 3g to wifi so I wonder if that had something to do with it also.

**Comment by garvankeeley** [comment]
I tried to remove any possibility of the top sites screen staying after tapping a cell. I can't confirm I fixed the bug since we can't reproduce it.
