### ISSUE TITLE
Unable to find the 'Deferred' module

### ISSUE THREAD

**Issue by UncleRic** [brave/browser-ios#571]
Description:
Attempted to compile code via Xcode.
I got a compiler error: the module 'Deferred' can't be found: "No such module: 'Deferred'.

**Comment by garvankeeley** [comment]
Any errors when following 
https://github.com/brave/browser-ios#setup

**Comment by UncleRic** [comment]
Discovered the Carthage file.... loading dependencies.  I believe that the original problem of not finding 'Deferred': didn't do a Carthage update.
