### ISSUE TITLE
Audio fingerprint test fails on iOS 10 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#577]
Description: Audio fingerprint test fails on iOS 10 

**Did you search for similar issues before submitting this one?** Yes

**Expected behavior:**
Should block audio fingerprint when fingerprint protection is enabled

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.18 RC1

- Steps to reproduce:
    1. Enable fingerprint protection globally from settings
    2. Visit https://audiofingerprint.openwpm.com/
    3. Click on fingerprint me, shows the audio fingerprint which should have been blocked

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20355205/75d3938a-ac18-11e6-88be-22e6db7d50c5.png)

- Any related issues:

**Comment by garvankeeley** [comment]
issue #556 fix caused this.

* network call happens off-main thread, based on URL set shield state on main async
* on main thread, turn on FP if that is current shield state. But due to async behaviour, may have missed window to block fingerprinting

**Comment by garvankeeley** [comment]
ca668b6 fixed
