### ISSUE TITLE
Brave crashes when print cancelled after searching for printers

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#579]
Description:Brave crashes when print canceled after searching for printers

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should not crash 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.18 RC1

- Steps to reproduce:
    1. Open any page
    2. Tap on share and select print option
    3. Tap on Search printers, wait till it shows no air printers 
    4. Cancel print, Brave crashes

- Screenshot if needed:

- Any related issues:
#464

**Comment by jamesmudgett** [comment]
https://github.com/brave/browser-ios/pull/587
