### ISSUE TITLE
URL bar text selection is not smooth 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#582]
Description: 
URL bar text selection is not smooth. Gives a pause after the visible text and then jumps to the end. It appears to get stuck and then select

**Did you search for similar issues before submitting this one?** Yes

**Expected behavior:** 
Should have smooth UI when selecting text 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
Verified on 1.2.17/1.2.18

- Steps to reproduce:
    1. Open a site with long URL which goes beyond the visible URL bar
    2. Tap on it to select
    3. The visible URL text is selected and then gives a pause and then jumps to the end

- Screenshot if needed:

- Any related issues:

**Comment by jamesmudgett** [comment]
https://github.com/brave/browser-ios/issues/1106

**Comment by jamesmudgett** [comment]
https://github.com/brave/browser-ios/issues/1106
