### ISSUE TITLE
Empty tab overview shows localhost as tab title

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#583]
Description:

**Did you search for similar issues before submitting this one?**

**Expected behavior:**

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:

- Steps to reproduce:
    1. Do a clean install of the RC2 build
    2. Tap on the tab count to view tab overview
    3. Empty tab has localhost

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20399744/0ed9e8b4-acea-11e6-8f9e-a02ae216a56f.png)

- Any related issues:

**Comment by garvankeeley** [comment]
Good find! fixing now...
