### ISSUE TITLE
Navigating back from edit bookmark doesnt have smooth transition in UI

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#584]
Description:
Navigating back from edit bookmark doesnt have smooth transition in UI. The moment `<Bookmarks` is tapped the bookmark snaps in 

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should be a smooth transition in UI after tapping on `<Bookmarks`

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.18 RC2

- Steps to reproduce:
    1. Slide the bookmark and tap on edit 
    2. Tap on the `<Bookmarks` to go back to bookmark list
    3. The bookmark snaps to position rather than the smooth UI transition 

- Screenshot if needed:

- Any related issues:

**Comment by jamesmudgett** [comment]
Unable to reproduce.

**Comment by srirambv** [comment]
@jamesmudgett http://sendvid.com/cwgxqcmh

**Comment by srirambv** [comment]
Transition seems smooth on 1.4.2. Closing as DNR on 1.4.2
