### ISSUE TITLE
Database clearing on startup

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#585]
We hare seeing the same behaviour here: https://bugzilla.mozilla.org/show_bug.cgi?id=1317093
Also related is this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1316324

I can repro reliably in our code by delaying BrowserDB .createOrUpdate with a sleep call (createOrUpdate is called for each table), and then profile.shutdown() from the main thread, so in the middle of a createOrUpdate cycle for the tables the db is shutdown.

Applying the patches from the above bugs fixes the problem, pushing up now.

QA: In theory starting the app and quickly going to home screen should do this, but couldn't get it to happen.

**Comment by jamesmudgett** [comment]
wow
