### ISSUE TITLE
Fingerprinting defenses seem weak

### ISSUE THREAD

**Issue by unsystemizer** [brave/browser-ios#595]
Description:
Cannot see much difference with Fingeprinting Protection enabled.

**Did you search for similar issues before submitting this one?**
Yes.

**Expected behavior:**
At least some FP protection.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad Pro 9.7

- Brave Version:
1.2.18

- Steps to reproduce:
    1. https://panopticlick.eff.org/ - try enabled vs disabled FP protection

**Comment by garvankeeley** [comment]
If you click to show the details you should see the WebGL hash is blocked. The canvas fingerprint reports a fake value (rather than a real unique hash) also.

**Comment by jhreis** [comment]
In addition to what @garvankeeley said, this has more thoroughly be addressed here:
https://github.com/brave/browser-laptop/issues/5975

![Image from EFF saying: "Your browser fingerprint appears to be unique"](https://cloud.githubusercontent.com/assets/2781690/23079689/f17ddfee-f51b-11e6-808b-71fc23f0224d.jpg)

So going to go ahead and close this.
