### ISSUE TITLE
Reader mode icon shows then hides during page load

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#596]
Description: Reader mode icon is hidden when URL is too long

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should display the reader mode icon irrespective of the length of the URL

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.18 (16.11.25.15)

- Steps to reproduce:
    1. Visit a website with a long URL
    2. Wait for the page to load
    3. Shows the reader icon, once page is fully loaded reader icon is hidden

- Screenshot if needed:
http://sendvid.com/ihpmu53x

- Any related issues:

**Comment by garvankeeley** [comment]
Are you sure that is a readerable page? Does it show up in landscape?
I think this is due to bugs in the reader library we use, which seems to report pages as readerable during initial load, then later content comes in, and now it decides it isn't readerable.

**Comment by srirambv** [comment]
Its the same on landscape mode as well. It does come up and then the URL covers it up.  The same link loads up fine on Safari reader mode

**Comment by garvankeeley** [comment]
Good to know. Better comparison is against firefox iOS reader mode, we are using their component for this

**Comment by srirambv** [comment]
Same link works fine on Firefox too. One observation, opening any article on Yahoo doesn't show the reader option after the page load, but refreshing the same page shows the reader option. This is not happening on Firefox.

**Comment by garvankeeley** [comment]
The readability.js lib is first reporting page is *readerable* (correct), then during a later check during load it reports the page is not (incorrect). Thus the reader button shows, then hides during load.

**Comment by garvankeeley** [comment]
Fixed by 9e878cabf6cf9518aab020d41e27148315e05b94
