### ISSUE TITLE
Duplicate labels with broken constraints added to right (brave) panel after opening a number of times.

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#600]
Description:

After opening the right (Brave) panel a number of times, constraints fall apart and duplicate labels seem to be placed in the view.

**Did you search for similar issues before submitting this one?**

Yes

**Expected behavior:**

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 4s (9.3)
iPhone 6 (10.1)

- Brave Version:

1.2.18 (16.11.24.09)

- Steps to reproduce:
(There are a number of ways to reproduce but here is an easy one):
    1. Open right (Brave) panel on tab with a valid website (e.g. google.com)
    2. Switch to tab (or create one) with no URL (home panel)
    3. Open right (Brave) panel

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

(the black cropped label says "localhost")
![simulator screen shot dec 2 2016 8 11 59 pm](https://cloud.githubusercontent.com/assets/2781690/20855503/b8f67802-b8cb-11e6-97fc-7dbda77b3072.png)

- Any related issues:

**Comment by jhreis** [comment]
Using Git Bisect over the last handful of commits, and adjusting the code to allow the right panel to show, I have identified `f10435d7b2d3fa0d1c8dadf84da7a51b5d8b4502` is the problematic commit. At immediate glance I think it is the adjustment to `setupConstraints()` that is the issue.

This allows `setupUIElements()` to be called more frequently, which does not reset constraints, but seems to try to setup the view as if nothing was there.

If this issue is assigned to me, I can probably take a better look at it.

**Comment by garvankeeley** [comment]
Thanks for noticing this! And, well, since you so kindly offered :), it is now assigned to you
