### ISSUE TITLE
[Beta]  deadlock when tab overview is selected

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#608]
Description: App hangs when tab overview is selected

**Did you search for similar issues before submitting this one?** Yes

**Expected behavior:** Should not hang 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.19(16.12.12.13)

- Steps to reproduce:
    1. Open Brave 1.2.19
    2. Tap on report a problem, ensure new tab opens with communit.brave.com
    3. Tap on the tab count to show tab overview, try closing the second tab, app hangs, have to kill and restart the app

   Happens even with manually created tabs

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
This is a nasty thread deadlock. 
UIWebView has a mutex on its WebThread (an internal class). Property getters on the UIWebView ask for this mutex.
Problem is, we have a mutex on the tabManager getter/setters, for thread-safe access.

Deadlock flow is:
• thread A: locks tabManager during selectTab()
• thread B: UIWebView load happens,  locks WebThread mutex, calls tabManager, waits for that mutex to release
• thread A: selectTab() checks property of UIWebView, deadlocks on WebThread mutex

**Comment by garvankeeley** [comment]
Changing the bug title again, as 'Report a Problem' is not required to repro this. Just using the tab overview and selecting/swiping away tabs a few times will trigger the bug.
