### ISSUE TITLE
Opening a link from reader mode and closing it doesn't load the reader mode again

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#615]
Description:
Opening a link from reader mode and closing it doesn't load the reader mode again

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should load back the reader mode for the URL

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10)

- Brave Version:
v1.2.19 (16.12.13.09)

- Steps to reproduce:
    1. Open any article on http://theverge.com/ 
    2. Open the article in reader mode
    3. Open any of the link in a new private tab from reader mode
    4. Close the private tab and navigate back to the article opened in reader mode, doesn't load the article, shows loading content and shows error (screentshot 1)
    5. Swipe right to navigate back to the previous page all the way back to new tab, URL bar still retains the reader mode icon (screenshot 2)

** Website problems only: No
- did you check with Brave Shields down? NA
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? Checked against Firefox, closing the link opened in private tab doesn't make any difference on the article opened in the reader mode

- Screenshot if needed:
![readermode2](https://cloud.githubusercontent.com/assets/17010094/21147183/0f2ed1aa-c14c-11e6-8db9-6649fe5113a2.PNG)
   ![readermode](https://cloud.githubusercontent.com/assets/17010094/21146959/5ee70baa-c14b-11e6-8673-891067acddab.PNG)

- Any related issues:

**Comment by garvankeeley** [comment]
Exiting private mode clears the reader mode cache, which causes this problem. Fixing now to not remove that cache, as reader mode in private browsing is not cached to disk anyway.
