### ISSUE TITLE
Swipe back doesn't go back to article from reader mode

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#616]
Description: Swipe back doesn't go back to article from reader mode after opening a link in a private tab from reader mode

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should come out of the reader mode when swiped back after exiting the private tab

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.19 (16.12.13.17)

- Steps to reproduce:
    1. Open any link on https://theverge.com
    2. Open the article in reader mode
    3. Open any link in a new private tab from reader mode
    4. Exit the private tab and return to normal tab with the article in reader mode
    5. Swipe right to go back, doesn't exit reader mode and goes back to article
    6. Repeat stps 1-4 but open the link in normal tab instead of private tab,  swipe back exits reader mode and loads the article

- Screenshot if needed:

- Any related issues:
#615

**Comment by garvankeeley** [comment]
Finally have this diagnosed: UIWebView has a bug with the app's method of restoring history, whereby if the current page after restore is a reader page, and back is pressed, the page document.location changes but the page doesn't reload with the new location.
Working around this.
