### ISSUE TITLE
Ads Tracker count doesn't stop on https://www.yahoo.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#618]
Description: Ads Tracker count doesn't stop on https://www.yahoo.com

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should only show the number of items blocked

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.18/1.2.19 

- Steps to reproduce:
    1. Visit https://www.yahoo.com
    2. Watch the ad trackers count, keeps counting

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
Page keeps trying to reload the blocked resource, and we keep counting the blockage
