### ISSUE TITLE
Newtab flashes before loading a webpage 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#622]
Description: Newtab flashes before loading a webpage 

**Did you search for similar issues before submitting this one?** Yes

**Expected behavior:**
Should immediately load the webpage 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10)

- Brave Version:
1.2.19(16.12.16.13) 

- Steps to reproduce:
    1. Open a new tab
    2. Type in slashdot.org and tap on go
    3. Tab becomes blank and then new tab with stat counter flashes before loading the webpage

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
I think i have this looking better, fix on its way

**Comment by garvankeeley** [comment]
Still seeing this, working on it more
