### ISSUE TITLE
Stat count automatically increases after restarting the app

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#624]
Description: Stat count automatically increases after restarting the app

**Did you search for similar issues before submitting this one?** 
Yes

**Expected behavior:**
Should not increment stat count after relaunching the app

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.19 RC1 build

- Steps to reproduce:
    1. Open any site and a new tab, keep focus on new tab
    2. Kill the app
    3. Relaunch the app again, stat counts auto increment

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
This is correct if there are background tabs
