### ISSUE TITLE
Buggy transition to top sites screen (stats show then hide, fonts change for final layout)

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#627]
The show transition for the top sites screen is buggy:
• stats show
• stats hide, message "your frequently used sites will appear here"
• message hides, stats re-show along with top sites,
• tops sites font changes to final font

![toolbar-hide-ugly](https://cloud.githubusercontent.com/assets/5495083/21319255/8110d04c-c5da-11e6-911e-8be6dba01ac7.gif)

**Comment by jamesmudgett** [comment]
PR https://github.com/brave/browser-ios/pull/630

**Comment by srirambv** [comment]
@garvankeeley This becomes evident when you have more tabs open and when you create a new tab

**Comment by garvankeeley** [comment]
Bumping to next release.

**Comment by srirambv** [comment]
This is still an issue on iPhone 6(iOS 10.3.1). Works fine on iPhone 7+
