### ISSUE TITLE
URL text selection in PB mode needs to be lighter for readability 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#637]
Description: URL text selection in PB mode needs to be lighter for readability 

**Did you search for similar issues before submitting this one?** Yes

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.19(16.12.29.17)

- Steps to reproduce:
    1. Open PB mode
    2. Type a URL 
    3. It hard to read the auto-completed URL

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21557288/65cc3f9c-ce22-11e6-8d38-1d26014f75c3.png)

- Any related issues:

**Comment by jhreis** [comment]
Reopening because selection contrast does not cover partial selection (with side carets):

![image_uploaded_from_ios_720-1](https://cloud.githubusercontent.com/assets/2781690/22792165/dce45b5c-eeb9-11e6-95c7-bab822a9e58d.jpg)

**Comment by jhreis** [comment]
Fixed in 1.4.1
