### ISSUE TITLE
Shields settings reverts to global settings after relaunching the app

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#645]
Description:
From [Community ](https://community.brave.com/t/site-shield-settings-are-being-forgotten/607)
> When I make changes to the site specific shield settings they are reset to the global default when I relaunch the app.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should retain the site specific sheilds settings

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
>iPhone 5
iOS 10.2

Verified on iPhone 6 

- Brave Version:
>Brave 1.2.19 (16.12.29.17)

- Steps to reproduce:
    1. Open a site, change site shields settings
    2. Double tap on home button to kill the app and relaunch
    3. After relaunch, the shields settings is reverted to global settings

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment]
Is this reproducible? I tried and didn't see this, but didn't spend time digging.

**Comment by srirambv** [comment]
@garvankeeley This is reproducible on the latest beta build as well. Her's the recording.
http://sendvid.com/8n3jxetx

**Comment by garvankeeley** [comment]
Thanks! It seems to be timing related; that the db doesn't get a chance to write before the app kill.

BTW you can also record the screen with Quicktime: http://ioshacker.com/how-to/use-quicktime-record-screen-iphone-ipad-ipod-touch-running-ios-8

**Comment by garvankeeley** [comment]
Correction: even if I do that exact gesture sequence that you showed, and wait to kill the app, the settings changes aren't saved. Puzzling.

**Comment by SubstandardZeal** [comment]
Brave 1.2.20 seems to have fixed this. Thanks
