### ISSUE TITLE
 safebrowsing upgrade to v2

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#646]
@bbondy is there code that also needs to change? If I simply load V2 of this file (that is the only change I made):
https://s3.amazonaws.com/safe-browsing-data/2/SafeBrowsingData.dat
Then all sites I tried are coming back as positive hits (amazon, yahoo, etc).

**Comment by garvankeeley** [comment]
@bbondy double ping in case you have any idea about this. 
I can't simply change the file version to v2, or safe browsing breaks.

**Comment by bbondy** [comment]
Im pretty sure v2 is compatible with v1 so it should work.

**Comment by garvankeeley** [comment]
@jhreis maybe we'll look at this together, and you can give me a second set of eyes.

**Comment by garvankeeley** [comment]
@bbondy any idea what else might need to change? Joel and I both confirmed just changing the version from 1 to 2 for
`https://s3.amazonaws.com/safe-browsing-data/2/SafeBrowsingData.dat`
Is reporting every site as a match for blocking. It is like the logic is suddenly backwards.

**Comment by bbondy** [comment]
as per slack the correct URL is: https://s3.amazonaws.com/adblock-data/2/SafeBrowsingData.dat
