### ISSUE TITLE
Tracking protection doesn't seem to be working on iOS

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#649]
From the report here:
https://github.com/brave/ad-block/issues/44#event-918486778

It looks like these domains are getting through on iOS:
- scorecardresearch.com
- imrworldwide.com
- google-analytics.com
- googletagservices.com
- googlesyndication.com
- quantserve.com
- teads.tv
- netshelter.net
- viglink.com
- bluekai.com
- bkrtx.com
- truste.com
- tubemogul.com
- sitescout.com

You can see they are all listed in the disconnect list here so they should be blocked by tracking protection:
https://github.com/brave/tracking-protection/blob/master/data/disconnect.json

This is a bug on iOS only and the tracking protection library is blocking them correctly on desktop and Android.

**Comment by garvankeeley** [comment]
On this list, only truste.com did not get blocked in unit testing, so I'll look at that one further

**Comment by garvankeeley** [comment]
@SergeyZhukovsky can clarify, but `truste.com` is not supposed to be blocked, so we are 100% ok on unit testing this batch of URLs

I'll see if these are blocked on the original sites in the report

**Comment by garvankeeley** [comment]
serg explained it: in the TP JSON file, the 'Content' section is like a whitelist, and truste.com is in there

**Comment by SergeyZhukovsky** [comment]
Yep, we shouldn't block anything from 'Content' section, but if something is in there and on other section - we should block in that case. truste.com is only in the 'Content' section so we allow it.

**Comment by garvankeeley** [comment]
closing, problem is reported in https://github.com/brave/browser-ios/issues/647
