### ISSUE TITLE
adBlock isn't blocking some things it should be only in iOS

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#650]
This is a spin off of:
https://github.com/brave/ad-block/issues/44#event-918486778

The ad block library reports the following as should be blocked, but they are getting through on iOS.  Also the rules are very generalized so it's not something like iOS is detecting the wrong resource type.

- teads.tv: this has a generalized rule for just the host name so that is enough to diagnose this one.  The EasyList rule in question is: `||teads.tv^$third-party` and using check.js, it reports matching true which means it should be blocked. `node scripts/check.js  --host www.cnet.com --location https://teads.tv`.

- netshelter.net: this has a generalized rule for just the host name so that is enough to diagnose this one.  The EasyList rule in question is: `||netshelter.net^$third-party` and using check.js, it reports matching true which means it should be blocked. `node scripts/check.js  --host www.cnet.com --location https://netshelter.net`.

- tubemogul.com:  this has a generalized rule for just the host name so that is enough to diagnose this one.  The EasyList rule in question is: `||tubemogul.com^$third-party` and using check.js, it reports matching true which means it should be blocked. `node scripts/check.js  --host www.cnet.com --location https://tubemogul.com`.

- sitescout.com:  this has a generalized rule for just the host name so that is enough to diagnose this one.  The EasyList rule in question is: `||sitescout.com^$third-party` and using check.js, it reports matching true which means it should be blocked. `node scripts/check.js  --host www.cnet.com --location https://sitescout.com`.

- sharethrough.com:   this has a generalized rule for just the host name so that is enough to diagnose this one.  The EasyList rule in question is: `||sharethrough.com^$third-party` and using check.js, it reports matching true which means it should be blocked. `node scripts/check.js  --host www.cnet.com --location https://sharethrough.com`.

**Comment by garvankeeley** [comment]
I put the hosts listed above in a test page:
https://brave.github.io/browser-ios/index.html

In debugger output, I print the list of blocked items:
URLProtocol startLoading BLOCK: teads.tv
URLProtocol startLoading BLOCK: netshelter.net
URLProtocol startLoading BLOCK: tubemogul.com
URLProtocol startLoading BLOCK: sitescout.com
URLProtocol startLoading BLOCK: sharethrough.com

All are blocked by iOS network filter. 

Next, I'll use networking tools to see if these are still leaking somehow, which would mean either UIWebView is bypassing our URLProtocol or perhaps it is reported to URLProtocol in some malformed state (we require certain URL request fields to be set for filtering to work) although I am not seeing that.

**Comment by garvankeeley** [comment]
Back from testing with Charles proxy, none of those URLs leak, still looking good so far.

**Comment by garvankeeley** [comment]
closing, problem is reported in https://github.com/brave/browser-ios/issues/647
