### ISSUE TITLE
Add more search providers

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#654]
https://github.com/brave/browser-laptop/blob/master/js/data/searchProviders.js

In particular start page was asking.

**Comment by garvankeeley** [comment]
Seems like it should be easy to do

**Comment by garvankeeley** [comment]
Start has a 32x32 favicon available: 
https://www.startpage.com/graphics/favicon/sp-favicon-32x32.png

**Comment by jamesmudgett** [comment]
PR https://github.com/brave/browser-ios/pull/659

**Comment by srirambv** [comment]
QA Steps:
Quick Search Engine should contain Infogalactic, Qwant, Semantic SCholar, Stack Overlfow, StartPage, Wolfram Alpha along with the existing searchengines
