### ISSUE TITLE
Default search engine should not be shown in the suggested search engine list

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#660]
Description:
Default search engine is shown in the list of suggested search engine

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Default search engine should not be shown in the suggested search engine list

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.19

- Steps to reproduce:
    1. Set your default search engine  in settings
    2. Open a new tab and start typing to bring up the suggested search engine
    3. Default search engine set up in step 1 is shown in the suggested search engine which shouldn't be the case

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
According to this code and comment…
https://github.com/brave/browser-ios/blob/f0a46fbba92ffe5dc3ad612efaf2a207b853b291/Client/Frontend/Browser/SearchViewController.swift#L225-L229
…the default search engine should only be visible if the browser is in Private Mode or Search Suggestions is off. Based on testing, this appears to be the current behavior.

The current behavior makes sense: the user should be able to access the default search engine from the _search engine_ suggestions if _Search_ Suggestions is off.

**Comment by jhreis** [comment]
Yeah, this is intentional, going to close out.
