### ISSUE TITLE
How to Fix this Bug. 

### ISSUE THREAD

**Issue by shree007** [brave/browser-ios#674]
/Client/Frontend/Browser/BrowserTrayAnimators.swift
 Bug 1205464 - Top Sites tiles blow up or shrink after rotating
  Force the BVC's frame to match the tab trays since for some reason on iOS 9 and above the UILayoutContainer in the UINavigationController doesn't rotate the presenting view controller

**Comment by garvankeeley** [comment]
Can I close? I think this is for Firefox iOS, as Brave code has diverged from this and doesn't have this bug.

**Comment by shree007** [comment]
okay Sir

**Comment by jhreis** [comment]
Closing per above.
