### ISSUE TITLE
Filter.cc crashing: iOS adblock race cond

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#675]
Our top crashers with this release is a bunch in filter.cc
<img width="497" alt="screenshot 2017-02-01 10 24 37" src="https://cloud.githubusercontent.com/assets/5495083/22513004/d12cb64e-e868-11e6-9336-d449717e1be9.png">

**Comment by garvankeeley** [comment]
@serg @bbondy have you seen similar before?

**Comment by bbondy** [comment]
I suspect this is from a regional adblock being auto turned on that is causing problems.  Which regions are enabled. 
CC @SergeyZhukovsky to watch this thread as well.

**Comment by garvankeeley** [comment]
From https://github.com/brave/browser-android-tabs/blob/master/chrome/android/java/src/org/chromium/chrome/browser/init/ChromeBrowserInitializer.java#L84
On iOS:
```swift
    private let wellTestedAdblockRegions = ["ru", "uk", "be", "hi"]
```

**Comment by bbondy** [comment]
Did download of dat files change at all? @SergeyZhukovsky is this list matching yours?
@SergeyZhukovsky could you check for similar crashes on your end?

**Comment by bbondy** [comment]
@garvankeeley can you correlate these to a device locale maybe?

**Comment by SergeyZhukovsky** [comment]
@bbondy @garvankeeley I havn't seen exactly the same crashes, but probably it is related to the corrupted dat files I think. I don't see any crashes in adblock after I added regional ad block features. Ya that list matches mine list in Android browser. @garvankeeley could it be corruption on download? I had to redo it to download to .tmp file first and after that check on size and if it is the same as on server side, I rename it to .dat. With that I have 0 crashes in ad block.

**Comment by garvankeeley** [comment]
We haven't had that problem, we use a similar method to ensure the file is complete.

**Comment by bbondy** [comment]
> We haven't had that problem

The thing is there's no way to know that for sure, the lib expects a valid data file, and if it isn't then it probably will crash.  We talked about adding some hashing verification to the lib to make it safer but we haven't done that yet. 

Looking at the crashing lines:

filter.cc
```
    if (host) {
      hostLen = this->hostLen == -1 ?
        static_cast<int>(strlen(host)) : this->hostLen;
    }
```


And the other:
```
    if (host) {
      hostLen = this->hostLen == -1 ?
        static_cast<int>(strlen(host)) : this->hostLen;
    }
```

I checked how host is set from copy constructors, assignments and constructors and it seems fine.  

I think this is from the data file not being full.

Some ideas:
- Is it possible to send up crash keys with the crash? Like size of data file and which one in use?
- Can you look at crash page and determine locale in use to see if it's related to something in a single region only?
- Audit code for things like downloading data file but not checking for status code 200 (error xml message with 400 for example might be being saved as a data file?).  
- Make sure lib is fully initialized before it is being used if multi threaded.

**Comment by garvankeeley** [comment]
Clicking on the report in Fabric shows the crash itself is in strlen, not sure if that detail helps.

We have no additional data regarding the crash locale, but we can attach crash keys with Fabric, we should look at that.
The screenshot doesn't show a key piece of the puzzle, this crash is unusual in that it is 1x per device (vs. low device count with many crashes). Possibly that indicates a non-corrupt data file as we have no code to re-download a file so we should see the user trying more than once.

@jhreis can you review this code? Brian's audit questions are good ones to start with. Grab me on slack and we can go over it.

**Comment by bbondy** [comment]
I think it's more than coincidental that this is happening just after new code was added to support regional adblock too, there aren't any adblock lib changes in a weeks.  If I was looking at it blindly without your arguments in the last message though, I'd say it's definitely from deserializing a corrupt or partial data file.   

Maybe the 1 time thing indicates early use of uninitialized buffer of data or something like that.

**Comment by garvankeeley** [comment]
True, the crashes fit that scenario, we'll look closely at that

**Comment by garvankeeley** [comment]
@jhreis the major change was on the iOS side, for the 2nd regional adblock file. Changes were minor to load a second file, but this might have exposed a latent bug.

**Comment by garvankeeley** [comment]
I see a problem. The code looks racy if a *new* data file arrives while the code is running, we only seem to have the initialization case of adblock well-guarded.
