### ISSUE TITLE
ndrw.pw reported blocked by safe browsing

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#677]
Can't repro on 1.2.20 on english locale. 
User is in english locale, but it seems like a regional adblock issue.

**Comment by garvankeeley** [comment]
@bbondy @serg pinging for guesses?

**Comment by ndrwpw0** [comment]
Hi all, https://ndrw.pw is my little blog. It's a pretty new site and I recently changed IP's and datacenter. To rule out possible DNS issues, I confirmed it's working on Chrome for iOS just to make sure. Here's the Brave error:

![unnamed](https://cloud.githubusercontent.com/assets/25085994/22526188/e3b9fc78-e88f-11e6-83be-34dcbb0a9da5.jpg)

**Comment by ndrwpw0** [comment]
@garvankeeley - this can be closed. Just checked my site and it's not blocked today. Not sure what happened.

**Comment by garvankeeley** [comment]
Maybe the adblock data file was out-of-date and now you have the latest one? Anyway good to hear
