### ISSUE TITLE
skypsports.com bug from tester

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#68]
Here's another bug.. I'm not exactly sure if it's a real bug but the other browsers definitely don't do this! Here's the use case that I was going through:

- opened http://www.skysports.com/football/news
- Clicked and Hold on several articles that I wanted to read later on the subway and selected "Open in New Tab" (opened about 15ish)
  - articles loaded in the background
- once I went underground, mobile phone witched into "offline" mode
- switched to tab view and clicked on one of the articles that I opened and appear as they're already loaded
- article turns completely white...

This happened to all the articles and I couldn't read anything on the subway that I loaded and figured was already loaded into the cache in the background.

**Comment by garvankeeley** [comment]
Closing, I have seen similar behaviour, and it is indeed when memory warnings are happening (UIWebView has built-in low-mem handling)

**Comment by garvankeeley** [comment]
https://github.com/brave/browser-ios/commit/d948aa8f8d2850ab35a602dd3e8fb72c93bea721
Has handling for restoring main doc html for non-in-memory tabs, and vastly improves this use case.
(we have another bug that relates to offline tabs, need to find it)
