### ISSUE TITLE
cannot using brave on ios : No Connection To Any Website 

### ISSUE THREAD

**Issue by 243750496** [brave/browser-ios#684]
Did you search for similar issues before submitting this one?
no

Describe the issue you encountered:
2

Platform (Win7, 8, 10? macOS? Linux distro?):
ios newest version

Brave Version (revision SHA):
newest

Steps to reproduce:
1.download the app from app store
2.open it
3.try to open a page

Actual result:
cant access any website

Expected result:
working smoothly

Will the steps above reproduce in a fresh profile? If not what other info can be added?

Is this an issue in the currently released version?
dont know

Can this issue be consistently reproduced?
yes

Extra QA steps:
1.iphone 7 plus
2.chinese app store
3.access from china

Screenshot if needed:
![0204_1](https://cloud.githubusercontent.com/assets/6311930/22619012/f4e27fc8-eb25-11e6-9672-975c44b3f307.jpg)

Any related issues:

**Comment by jhreis** [comment]
Is this still an issue with the last update?
