### ISSUE TITLE
Bottom Tabs bar needs to be more opaque

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#687]
Description:
With low screen brightness, the bottom Tabs gets camoflagued on a dark background making it difficult to use it. 

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should be more opaque so that it is still visible on dark background of webpages

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.3.0(17.02.03.13)

- Steps to reproduce:
    1. Open any page which has a dark backgound
    2. Scroll down and scroll back up to bringup the bottom tabs bar
    3. With dark backgorund the tabs bar is not visible correctly on the device if the device brightness is low

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
On screenshot looks fine but on device it looks very bad
![image](https://cloud.githubusercontent.com/assets/17010094/22620024/8e0bd7de-eafa-11e6-9a6f-20778b7d76bd.png)

- Any related issues:

**Comment by jamesmudgett** [comment]
1.4.2
