### ISSUE TITLE
Keep bookmark icon color consistent when navigating between settings and webview

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#688]
Description:
The dark bookmark icon doesn't look good in settings mode when compared to the yellow bookmark icon which looks dull on the webview 

**Did you search for similar issues before submitting this one?**

**Expected behavior:**
Keep bookmark icon color consistent when navigating between settings and webview

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.3.0(17.02.03.13)

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22620072/5e665fda-eafb-11e6-8e7a-1841888b89e3.png)
![image](https://cloud.githubusercontent.com/assets/17010094/22620074/67d70326-eafb-11e6-9f4f-d08b28a3f247.png)
![image](https://cloud.githubusercontent.com/assets/17010094/22620078/801d79a6-eafb-11e6-8b7d-d7edd26257fd.png)

- Any related issues:
cc: @bradleyrichter

**Comment by jamesmudgett** [comment]
Having a colored icon would conflict with purpose of color on this nav which highlights active menu item. I think introducing color here would be more confusing. Solution likely to change bookmarked page icon to black in header?

**Comment by jamesmudgett** [comment]
To add, we're moving away from side panels in the near future, likely 1.5.

**Comment by jhreis** [comment]
Closing this issue per above 2 comments.
