### ISSUE TITLE
Overleaf.com banner blocks input field

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#694]
Description:
Overleaf.com banner blocks input field

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should not block the input field

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.0 & 1.3.0

- Steps to reproduce:
    1. Visit http://overleaf.com
    2. Tap on Signin button
    3. Banner blocks the login input field

** Website problems only: Yes
- did you check with Brave Shields down? NA
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? Verified on Puffin and Firefox, input not blocked by the banner

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22698793/7511fc18-ed4d-11e6-9eed-260d5912438c.png)

- Any related issues:

**Comment by jamesmudgett** [comment]
Looks like a site issue they fixed.

**Comment by jamesmudgett** [comment]
QA and Close

**Comment by srirambv** [comment]
DNR on 1.4.2. Closing as fixed
