### ISSUE TITLE
Tab restore bug: current tab not restoring, background tabs seem ok

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#695]
The first is before killing the app, and the second is after re-opening the app:

<img width="319" alt="screenshot 2017-02-07 14 56 04" src="https://cloud.githubusercontent.com/assets/5495083/22708832/c4b03616-ed45-11e6-92bf-19e19265a03b.png">

<img width="315" alt="screenshot 2017-02-07 14 56 27" src="https://cloud.githubusercontent.com/assets/5495083/22708837/c749912e-ed45-11e6-9425-246bbe4225f6.png">

**Comment by garvankeeley** [comment]
Not a new bug, repro'd on 1.2.19. The problem is actually that history isn't restored properly on the current tab, it will restore to the page before the previous. Not sure why this is only in certain cases it can be tricky to repro.

**Comment by jhreis** [comment]
This should be fixed with CD migration.
