### ISSUE TITLE
Tabs occasionally do not have favicons and titles 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#697]
Description:
When managing multiple tabs, they sometimes drop favicons and titles.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
A user should be able to know where the tab is pointing before they select it.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Discovered on iPhone 6s+

- Brave Version:
1.30

- Steps to reproduce:
    1. Open multiple tabs
    2. Close app
    3. Open app, open more tabs

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
![1 3 0 tabs](https://cloud.githubusercontent.com/assets/1434040/22714348/ac7f48d2-ed51-11e6-8e1b-fbbf96ce816a.jpg)

- Any related issues:

**Comment by jhreis** [comment]
@alexwykoff If you scroll up/down (so a "broken" tab goes out of view, and back in view), does it change what tabs have titles/icons?

**Comment by alexwykoff** [comment]
It did not appear to be the case. I am trying to repro with the latest build (1.3.0 / 17.02.08.09)

So far, tabs are behaving better.

**Comment by alexwykoff** [comment]
Closing DNR. Tried iPhone and iPad with latest build.

**Comment by garvankeeley** [comment]
This can happen on the old code also. The favicon and title are extracted from the webpage very late in the load process on readyState complete/interactive IIRC.
