### ISSUE TITLE
Folder names cannot be edited to have space-only titles

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#705]
Description:
New folders can be created with just spaces ' ' (expected behavior), but folders names cannot be edited with just spaces (input is rejected). The naming behavior/validation should be the same for creating and editing folder names.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Editing folder name should allow space-only names

- Brave Version:
1.3

- Steps to reproduce:
    1. Create folder with name (e.g. 'test')
    2. Edit bookmarks
    3. Select newly created folder
    4. Attempt to edit the folder name to only include spaces
    5. Go back and see the name did not change

- Any related issues:
#513 - Not allowing 'empty' folder names (but allowing spaces).

**Comment by garvankeeley** [comment]
Agreed with the space-only names, no reason a user can't do that if they don't feel like naming a folder.
