### ISSUE TITLE
Tab tray cells too tall for iPhone 5 screen

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#706]
The tops are cut off in portrait  when adding 2nd row of tabs. It should be able to show a 2nd row without cutting off top of 1st row.

![simulator screen shot feb 8 2017 3 14 34 pm](https://cloud.githubusercontent.com/assets/5495083/22755501/64d1cbca-ee11-11e6-8fb6-542e0a5e4bb0.png)

**Comment by srirambv** [comment]
![image](https://cloud.githubusercontent.com/assets/17010094/22755812/b083c0c0-ee3c-11e6-98cb-ac15b9350930.png)

Small cut off portion of the top row tabs are shown in tab tray. Can the tabs be sized based on the device scree size dynamically to show 4 tabs are a time?

**Comment by garvankeeley** [comment]
The second screenshot is a different bug though, that is whether we want to show partial rows to indicate scrollability. I think we actually want to do that.

**Comment by srirambv** [comment]
Can it be made like a small arrow on  top and bottom to indicate scrollability rather than cutting off and showing portions of tabs

**Comment by garvankeeley** [comment]
or fade the cut-off tabs. let's leave that indicator part to the first update

**Comment by jhreis** [comment]
For reference, fixed via: 1f8737d1beb29cd0023e484cf14e1e1ba37e9be6
