### ISSUE TITLE
Vertical spacing on shields menu is too sparse for iPhone5 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#711]
Description:
Vertical spacing on iPhone5 shield menu causes clipping of Fingerprint Protection toggle
**Did you search for similar issues before submitting this one?**

**Expected behavior:**

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
![image uploaded from ios 3](https://cloud.githubusercontent.com/assets/1434040/22798291/fb928170-eec6-11e6-8beb-20d2c1de5ff8.jpg)

- Any related issues:

**Comment by jhreis** [comment]
Fixed via: 94967452ed59782fd4364ac49572615b6f24db81
