### ISSUE TITLE
Tab text is not completely hidden when webview is scrolled up with always show tabsbar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#714]
Description:
Tab text is not completely hidden behind the top bar when webview is scrolled up with always show tabsbar

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Tab text should be hidden behind the top bar

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All 

- Brave Version:
1.2.20 & 1.3.0

- Steps to reproduce:
    1. Enable `Always show tabsbar` from settings
    2. Open bunch of tabs and open a page in them
    3. Scroll down so that the URL bar and tabsbar moves up 
    4. Once they move to the top of the screen, tabs bar text is visible behind the topbar 
Existing issue but previous builds had a dark UI which masked the tabs bar behind them. With the lighter UI of 1.3.0 this i clearly visible

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22802413/a1e1b690-ef08-11e6-9726-81166edebd0b.png)

- Any related issues:

**Comment by jhreis** [comment]
This is especially bad on iPad, where the status bar is always visible.

**Comment by garvankeeley** [comment]
a quick hotfix for this one would be good

**Comment by jamesmudgett** [comment]
PR https://github.com/brave/browser-ios/commit/59c669a6a5e1999b1011984082173a7ce907a64a
