### ISSUE TITLE
what are the roles for BrowserWebView & ContainerWebView 

### ISSUE THREAD

**Issue by hpsoar** [brave/browser-ios#715]
hello, this is not an issue on the app.

I'm reading the code of the app and attempting to do some customization.

And I'm curious about the usage of WKWebView.

Seems that WKWebView is only used to run javascript?

BrowserWebView & ContainerWebView seems not really used?

BR.

**Comment by garvankeeley** [comment]
ContainerWebView is a wrapper used to pass UIWebView into WKWebView-expecting protocols. It makes it easier to switch the code over to using WKWebView.

BrowserWebView -> not sure what you are referring to.
