### ISSUE TITLE
iPhone: setting>Tabs always on, the y position of the webview is under the tabs

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#721]
![simulator screen shot feb 14 2017 9 18 34 am](https://cloud.githubusercontent.com/assets/5495083/22932659/c128651c-f296-11e6-87f3-bed813c32a71.png)

Related:
#729

**Comment by garvankeeley** [comment]
In the above screenshot, I pulled down 40 pixels to reveal the top of the page, which also shows the reload indicator.

**Comment by jhreis** [comment]
Interestingly, this is only reproducible on the iPhone 6s, but not on the 6s+.
