### ISSUE TITLE
Tab count is retained momentarily before opening the tab tray

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#725]
Description: Tab count is retained momentarily before opening the tab tray. The transistion is not smooth and very evident of other items disappearing first before the tab count

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Fade in transition should happen on all items at once

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.3.1(17.02.14.11)

- Steps to reproduce:
    1. Tap on the tab count to load the tab tray
    2. `Back`, `Forward`, `Action` and `New tab` buttons fade out but the tab count is still retained before loading the tab tray
    3.

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:

- Any related issues:
cc: @jhreis

**Comment by jhreis** [comment]
Since we are removing tab tray count, closing this out.
