### ISSUE TITLE
Scroll gesture can trigger navigation

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#741]
This is hard to repro, but is very annoying when it does happen.

We could use BraveScrollController to track when the webview starts/stops scrolling, and block webview navigation during scroll.

EDIT: I think this code could cause this behaviour:
https://github.com/brave/browser-ios/blob/5f71693e6bc72bc899ab499deda99b47c166f0f2/brave/src/page-hooks/BraveContextMenu.swift#L23

This was part of a fix for #399.

**Comment by garvankeeley** [comment]
@jhreis added 1cfe625 on coredata (our new master) that should stop context menu touch detection from contributing to this bug.
The problem in #399 was that holding down on a link would trigger our context menu touch detection code after 250ms. At 250ms we cancel UIWebView touch detection. Then at 850ms the context menu is triggered. If the finger touch meets all these conditions:
- lifted between 250ms and 850ms,
- on a link,
- did not move,
then we need to trigger a link tapped event manually.

**Comment by jhreis** [comment]
This one is a bit tricky to test reliably IMO (I never experienced many issues related to this). We have had many reports of users accidentally clicking on a link when their intention was to perform a scroll. (e.g. scrolling on facebook, actually clicks a URL where their finger pressed down).

This was never the intention, and this logic has only been slightly modified to handle better timing of the gestures. The main thing for testing, would be to just visit a webpage with lots of scrolling (e.g. Twitter, Facebook), and verify that there are no issues related to *scrolling*, *clicking on links* (intentionally), or *opening the context menu* (e.g. open in new tab, copy link).

Just need to verify that this has not broken standard usage. This is just a subtle performance improvement. @alexwykoff mentioned that he felt scrolling had improved, which would most likely be related to this ticket.

**Comment by jhreis** [comment]
One report: https://twitter.com/gallegosart/status/844767626861563904
