### ISSUE TITLE
iTunes app details needs to update support information

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#742]
Since support is moved to community.brave.com, support information should also be updated.

![image](https://cloud.githubusercontent.com/assets/17010094/23565425/727efb8a-0045-11e7-9c52-7dec271b2eff.png)

**Comment by jhreis** [comment]
This has been updated:

![Updated screenshot of support information on iTunesConnect](https://cloud.githubusercontent.com/assets/2781690/24294510/1e8686fa-106d-11e7-9758-4edf4613527b.png)

**Comment by srirambv** [comment]
@jhreis Does the change gets reflected with the release of 1.3.2? I still see the original email support mentioned in the app store
