### ISSUE TITLE
theguardian.com crashes Brave consistently

### ISSUE THREAD

**Issue by artelse** [brave/browser-ios#749]
As the topic says, theguardian.com can hardly be used as going back to the home page crashes Brave consistently.
- iPad mini 3, iOS 9.0.1
- Brave Version: latest
- Steps to reproduce:
    1. go to theguardian.com
    2. click a link and hit back
    3. crash

Thanks for looking into this issue, it makes using Brave very hard.

**Comment by jamesmudgett** [comment]
@artelse are you still seeing this problem with more recent versions of Brave and iOS? Reopen if necessary.

**Comment by artelse** [comment]
Yes, just installed the new version the other day. It's still the Guardian that crashes. An additional observation is that it only crashes when it is the open tab. When I reload the Guardian and switch to another tab, it's all fine, no crash.
I also wonder why Brave loads all tabs not just the open tab, even the invisible ones. Takes much cpu and waiting time for anything appears.
