### ISSUE TITLE
SwiftKeys keyboard keeping first letter when using predictive text

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#750]
Description:

The SwiftKey keyboard has full access. After I type a few characters into the empty URL bar and then select a word suggested by SwiftKey the first letter remains in the URL.

For example if I type in "publi" into the empty URL bar, SwiftKey will suggest "public". When l select the suggestion "ppublic" is put in the URL bar instead of "public". I this only occurs for the first word in the URL.

https://community.brave.com/t/first-character-is-left-in-url-when-using-swiftkey-prediction/1688

**Did you search for similar issues before submitting this one?**

**Expected behavior:**

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:

- Steps to reproduce:
    1. Install SwiftKeys
    2. Open Brave
    3. Select URL Bar
    4. Type "T"
    5. Select recommended word (e.g. "The")
    6. The URL will now show "TThe" instead of just "The"

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Verified on iPhone 7+ running 1.6(18.04.17.16)

**Comment by jhreis** [comment]
Should be included in release notes as something like:
> Third-party keyboard improvements
