### ISSUE TITLE
Adding new file to Build

### ISSUE THREAD

**Issue by shree007** [brave/browser-ios#752]
I setup brave browser at my Xcode 8.0 . I want to add some swift file in my build. How should I proceed please let me know.

Thanks in advance.

**Comment by jhreis** [comment]
I am not entirely sure what you are asking exactly, if you could clarify that would be great.

You can create new files by just right clicking on the file navigator and click "new file" (see image below). This will add a new file to the build when you run. 

If you are wanting to add a file to master/production, you can fork this repo, add the files you want, and submit a pull request. 

<img width="211" alt="screenshot_29" src="https://cloud.githubusercontent.com/assets/2781690/24050968/f633559a-0b06-11e7-986b-68695e660400.png">

**Comment by shree007** [comment]
Thanks Sir I got that.I had a confusion because of this unique number " 0B2770491A893C9500CE7692" (Bookmarks.swift )  I thought I will have to create and add  manually for new file. I am newbie sir.

**Comment by shree007** [comment]
Hello Sir

I added some file to implement a functionality , I got error refer to image. i am using Xcode 8.
I tried to resolve it using  your answer . `http://stackoverflow.com/questions/29233317/swift-could-not-build-objective-c-module-when-using-cocoapods` i could not resolved . 
![screen shot 2017-03-18 at 12 40 18 pm](https://cloud.githubusercontent.com/assets/13500205/24069866/90569b6a-0bd8-11e7-8988-53e733d91048.png)

**Comment by jhreis** [comment]
Yeah, that unique ID is generated by Xcode when a new file is added.

Did you run the `./checkout` and `./setup.sh fake.id` from the README?

**Comment by shree007** [comment]
okay Sir .Thanks I got that.

**Comment by shree007** [comment]
Yes Sir I run ./checkout.sh and ./setup.sh fake.id according to Readme.

**Comment by jhreis** [comment]
No errors while running those?
Try doing a clean (`Cmd` + Shift` + `K`) and then build (`Cmd` + `b`)

**Comment by shree007** [comment]
Sir I tried clean and build 
**Details about Errors**                                                                                                                                                                    When I started building after adding files  initially I got the following error,

1.
	A. Required missing module "swiftTryCatch.h"
		I have fixed this error and ran a build again, then I got the following error. 

	B. In SQLiteBookmarksModel.swift, Use of undeclared type "SQLiteBookMarks"
  		I have gone through the code and I found that SQLiteBookMarks is declared in SQLiteBookmarksBase.swift file, and this file belongs to the shared module and we imported this file into the SQLiteBookmarksModel.swift file, but still I am getting this error. 

2. In X-Code Went to the option Product and clicked on "Clean" (It will regenerates all the build files from first), after that I ran a build, this time I got the two errors which are different from earlier. 
	A. Header 'Shared-Swift.h' not found
	B. Could not build Objective-C module 'Shared'

Some times I get the error's which I have mentinoed in the 1th point and some times I will get the errors which I have mentioned in the 2th. 

Our system configuration: 

X-Code version: 8.0

Xcode Build version: 8A218a

Swift version: 2.3

Node js: v6.9.3

**Comment by shree007** [comment]
I am trying to develop a feature that belongs to file downloading , i am unable to understand why errors are getting from Bookmarks(i mean SQLiteBookmarksModel.swift)  .I got following warning also in SQLiteBookmarksModel.swift 

"File 'SQLiteBookmarksModel.swift' is a part of module 'Shared' ignoring import"
I tried to resolve using this link
http://stackoverflow.com/questions/34889552/xcode-test-class-file-is-part-of-module-ignoring-import

I could not get success. May be since above link belongs to test class file.

Please provide me some guidance Sir.

**Comment by shree007** [comment]
**"No errors while running those?"**
When I run ./checkout.sh and ./setup.sh I did not get any error. I got some warnings.

**Comment by jhreis** [comment]
Try checking out the `coredata` branch (`git checkout coredata`)

Otherwise, I will need to investigate this a bit later. Regardless, really appreciate your interest in Brave Shree! We'll get this figured out ;)

**Comment by shree007** [comment]
Okay Sir , I'll .

**Comment by jhreis** [comment]
Oh, you will also need to rerun the `setup` and `checkout` scripts for changing branches.

**Comment by shree007** [comment]
Thanks A lot sir .  I fixed those errors ,  I cleaned build folder
(Option+Shift+Command+K) make few changes in Xcode  configuration.

Regards
Shree

**Comment by jhreis** [comment]
I would recommend using 1.4, as coredata branch has been deleted. Soon 1.4 will be merged to master and deleted.

**Comment by shree007** [comment]
okay Sir
