### ISSUE TITLE
 Add Iran add blocking filter

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#758]
{
  uuid: 'C3C2F394-D7BB-4BC2-9793-E0F13B2B5971',
  listURL: 'https://raw.githubusercontent.com/farrokhi/adblock-iran/master/filter.txt',
  title: 'IRN: AdBlock Iran Filter',
  lang: 'fa',
  supportURL: 'https://github.com/farrokhi/adblock-iran'
}

**Comment by srirambv** [comment]
Need QA steps for this as there is no Iran region available in phone settings to change and check for regional adblock

![image](https://cloud.githubusercontent.com/assets/17010094/25227173/86043bda-25bf-11e7-8770-b54ad10ac8e9.png)
