### ISSUE TITLE
 gifs being stored as jpegs.

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#760]

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/explanoit/status/965728840055181312

> still saves animated .gif as a single frame image.

**Comment by Liunkae** [comment]
PR: #1480

**Comment by LaurenWags** [comment]
iPad using iOS 10 - only jpeg is saved. Same behavior on FF, Dolphin, Chrome on same device.

**Comment by kjozwiak** [comment]
Same results as @LaurenWags mentioned above. Saving `.gifs` under iOS 10 saves them as `.jpg`. Works fine on iOS 11 devices.
