### ISSUE TITLE
Secret code word tiles should have numbering to help users enter it correctly

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#763]
Description:
Secret word tiles should have numbering to help users enter it correctly

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should make it easy to enter the secret words

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All

- Brave Version:
1.4.1

- Steps to reproduce:
    1. Enable Sync on desktop and generate the secret words
    2. Enable Sync on mobile, Scan or enter code-> Enter code
    3. There is no clear indication as to how to enter the secret words in tiles. Users can enter horizontally, vertically or add it randomly

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
Current UI
![image](https://cloud.githubusercontent.com/assets/17010094/24329719/b1564a98-1206-11e7-886f-438d884814e8.png)

  Suggested UI
  ![image](https://cloud.githubusercontent.com/assets/17010094/24329845/ee27ec08-1209-11e7-8b83-8327165d0d71.png)

- Any related issues:

**Comment by LaurenWags** [comment]
Removing milestone per standup call
