### ISSUE TITLE
Sync reset/disable option should be available

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#764]
**Description:**
No option to disable Sync or reset sync

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Sync reset/disable option should be available

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All

- Brave Version:
1.4.1

- Steps to reproduce:
    1. Sync option doesn't have a reset or disable button. Once sync'd there's no going back 

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
Fixed on: 697770e

**Comment by LaurenWags** [comment]
Removing milestone per standup call
