### ISSUE TITLE
Done button is non functional in Get a new sync code

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#765]
Description:
Done button is non functional in Get a new sync code

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Tapping on Done should close the code word screen and navigate back to settings

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10)

- Brave Version:
1.4.1

- Steps to reproduce:
    1. Open settings -> Get a new sync code -> Code Words/QR Code
    2. Tap on the done button nothing happens
    3.

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
Fixed per fcac706

**Comment by LaurenWags** [comment]
Removing milestone per standup call
