### ISSUE TITLE
Successive crash causes dead tabs [Intermittent issue]

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#767]
Description:
Successive crash causes dead tabs

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should not crash and cause dead tabs

- Device (iPhone5, iPhone6s plus, iPad 3, ?):iPhone 6 (iOS 10)

- Brave Version:
1.4.1 Beta

- Steps to reproduce:
    1. Open any twitter account and open the gif image 
    2. Play the gif image which opens up in new frame
    3. Once the gif is played and tapping on done button causes browser to crash
    4. Launch the browser, crashes again
    5. Relaunch the browser after the second crash, shows the `Start Browsing` welcome screen, all opened tabs are dead, cannot use, have to open a new tab and close the other ones
Happened once but not able to consistently reproduce the issue

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:
cc: @jhreis 
#644

**Comment by jamesmudgett** [comment]
Needs to be reporduced

**Comment by srirambv** [comment]
Cant reproduce with steps mentioned in original issue. Tried crashing app manually by toggling save password switch in ettings, still DNR. Closing as DNR on both iOS10 and iOS11.
