### ISSUE TITLE
Content lost after screen has closed

### ISSUE THREAD

**Issue by rajakvk** [brave/browser-ios#768]
Description:
After closing the mac screen the loaded website content is lost.

**Did you search for similar issues before submitting this one?**
Tried. But tricky to search in this case.

**Expected behavior:**
When reopen the closed mac screen, the content of all the tabs should persists. 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
NA

- Brave Version:
	0.13.5

- Steps to reproduce:
    1. Open a website
    2. Close the mac slid (screen)
    3. Open the slid (screen) again next day.
    4. Content in the webpage already loaded has been lost. Can see the text "Error" on all tabs

**Comment by jhreis** [comment]
Thanks for reporting. However, this is the Brave iOS repo. Please recreate the ticket on [Browser-Laptop](https://github.com/brave/browser-laptop/issues/new).

I would do it, but it would probably be good to have it associated with your name for tracking/clarifications.
