### ISSUE TITLE
Opening a empty title folder shows Bookmarks as the title 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#769]
Description:
Opening a empty title folder shows Bookmarks as the title 

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should not show the folder title as the folder title is empty

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All

- Brave Version:
1.4.1

- Steps to reproduce:
    1. Create a new bookmark folder called test
    2. Edit the folder and remove the name
    3. Tap on done to save the folder without name
    4. Open the folder, title changes to Bookmarks, should be blank as the folder name is empty

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/24349674/b141ba66-12d7-11e7-8f05-4326781eb3c6.png)

- Any related issues:
#705

**Comment by jhreis** [comment]
This has been fixed somewhere along the line of bookmark related commits.
