### ISSUE TITLE
Removing bookmark folder name causes it to show as root folder when trying to move a boomark

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#770]
Description:
Removing bookmark folder name causes it to show as root folder when trying to move a boomark

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should have a proper UI indication to show the bookmark folder name is empty/null

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.4.1

- Steps to reproduce:
    1. Create a bookmark folder test
    2. Edit the folder and remove the title to make the field empty and tap on done
    3. Visit any site and add as bookmark
    4. Edit the bookmark from step 3, folder lists two Root folder the second one being the folder created in step 1

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/24349967/7db6c42e-12d8-11e7-8ada-be5ef37e779b.png)

- Any related issues:
#450

**Comment by jhreis** [comment]
See above commit. Currently just removed this capability all together. Going to close this ticket and re-open a more general one. This will require some redesign for usability.

**Comment by jhreis** [comment]
Created: #785

**Comment by srirambv** [comment]
Adding as No-QA as the functionality is removed
