### ISSUE TITLE
Folder title is shown only after tapping on Done

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#778]
Description:
Folder title is shown only after tapping on Done

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should show the folder name immediately after the keyboard is hidden

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6  (iOS 10)

- Brave Version:
v1.4 (17.03.27.14)

- Steps to reproduce:
    1. Install/upgrade to v1.4 (17.03.27.14) beta
    2. Create a new folder and click on ok, folder name is not shown
    3. Tap on done, folder name slides in 

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/24462853/00059386-149d-11e7-85df-4c7319518baf.png)

- Any related issues:

**Comment by jamesmudgett** [comment]
Unable to reproduce this, are there other steps to reproduce from fresh open?

**Comment by jamesmudgett** [comment]
Seeing in nested folder creation, will work on fix.

**Comment by jhreis** [comment]
This issue (as a bug) has been fixed. There is still some folder creation UX that may be improved in the future, but unrelated to this specific issue.
