### ISSUE TITLE
Pull down reload shows reader mode on all pages

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#783]
Description:
Subsequent pull down reload shows reader mode on all pages

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should only show the reader mode option in URL for supported links

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10.3)

- Brave Version:
1.4.1

- Steps to reproduce:
    1. Visit google.com and search for any search term
    2. Pull down reload the page reader mode is not shown
    3. Pull down reload the page, reader mode is shown for google search

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by Jacalz** [comment]
Can not really reproduce, can't reproduce on other sites I tested but google searches always show reader mode for me 😅

**Comment by LaurenWags** [comment]
Running into this on 1.4 Beta (17.07.31.11)

**Comment by jhreis** [comment]
Removed pull to refresh, so shouldn't be an issue anymore 😄
