### ISSUE TITLE
Tab Restoration Fails

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#788]
Description:
Sometimes after re-opening the app all tabs are removed. More frequently happens after a crash.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:
1.3.1

- Steps to reproduce:
Unsure

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
This should be fixed: c089133

When storing active tabs to disk, all currently saved tab information was being deleted, before serializing new tab data. If this process was interrupted, it could result in all tabs being removed, and nothing saved.

**Comment by srirambv** [comment]
Steps to Reproduce
1. Open two tabs and visit sites
2. Kill the app 
3. Relaunch the app
4. Kill the app immediately after launch
5. Relaunch the app, tabs opened in step 1 are lost. App starts with a new tab

**Comment by FernandoMiguel** [comment]
i'm still on version 1.3.3 and this happens quite often.
to the point i'm using less and less Brave cause i fear i'll lose all the open pages I'm trying to read.

OTOH, safari is able to keep pages for months.
