### ISSUE TITLE
Secret code word tiles should be editable if a user makes a mistake

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#790]
Description:
When entering the secret code words I accidentally misspelled a word. I tried to tap, press & hold, backspace, nothing worked after I had moved to another tile.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
A user should be able to recover from mistakes. 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Tested on iPhone 6s+

- Brave Version:
1.4 (17.04.07.17)

- Steps to reproduce:
    1. Start to enter sync codes, misspell one.
    2. Hit 'Continue'.
    3. Try to edit a previously entered tile.

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by LaurenWags** [comment]
Removing milestone per standup call
