### ISSUE TITLE
When Un-toggling "Private Browsing Only", app should leave private browsing mode

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#801]
Description:
When toggling "Private Browsing Only", the user is auto-switched to PB. When de-selecting this, the user should be switched back to normal mode.

We have had a number of people confused to current behavior.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Leave private browsing mode.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:
1.3.1

- Steps to reproduce:
    1. Toggle on "Private Browsing Only"
    2. Browse for a bit
    3. Go back into settings and untoggle "Private Browsing Only"
    4. App stays in private browsing mode

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Same as #439?

**Comment by jhreis** [comment]
@srirambv Ah yes, odd I didn't see that one. Closing this issue as a duplicate.
