### ISSUE TITLE
Search in page option should not be shown on a new tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#808]
Description:
Search in page option is shown on a new tab which doesn't make sense.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Search in page option should not be shown on a new tab

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All

- Brave Version:
1.3.2(17.04.12.13)

- Steps to reproduce:
    1. Open a new tab and focus on URL
    2. Start typing, `Find in page` option is shown below search suggestion
    3. Tap on it nothing happens, URL bar is dismissed

- Screenshot if needed:

- Any related issues:
#804

**Comment by jhreis** [comment]
Fixed per above commit.
