### ISSUE TITLE
In Private Mode URL Bar should use Dark Keyboard

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#811]
Description:
Use the Dark Keyboard theme when in private mode

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:

- Steps to reproduce:
    1. Go into PM
    2. Click URL Bar
    3. See Light Keyboard with Dark Theme

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

![Brave Private Mode with Light Keyboard, Gross](https://cloud.githubusercontent.com/assets/2781690/25011222/a4c15092-203a-11e7-8b3b-103d02a90198.png)

- Any related issues:

**Comment by jamesmudgett** [comment]
Prefer dark keyboard always, the light keyboard has a bluish hue that doesn't work well with our gray, dark looks cooler and use it elsewhere (folder creation), PR: https://github.com/brave/browser-ios/pull/812
