### ISSUE TITLE
New tab switch doesn't happen on 0.13.2

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#815]
Description:
New tab switch doesn't happen on 0.13.2

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should switch to new tab when link is opened in a new tab

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10.3)

- Brave Version:
1.3.2 

- Steps to reproduce:
    1. Open https://news.google.com in a new tab
    2. Tap on any of the links to launch the article in a new tab
    3. Tab opens but doesn't switch tab

** Website problems only: N/A
- did you check with Brave Shields down? Yes
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
@jhreis  The default behaviour is changed with this fix. Links now open in the same tab. This causes the content test to fail 
> Test that news.google.com sites open in a new tab (due to target being _blank)

This needs to be reverted and the links should open in new tab and switch to the newly opened tabs.

**Comment by alexwykoff** [comment]
news.google.com has a new behavior so a new tab will not be opened anyways.
