### ISSUE TITLE
Make keyboard use dark theme across tabs 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#823]
Description:
Keyboard doesn't look like its using dark theme with white background
**Did you search for similar issues before submitting this one?**
Yes
**Expected behavior:**
Make keyboard use dark theme across tabs 
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All
- Brave Version:
1.3.2(17.04.19.13)

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25202831/b4765e60-254e-11e7-8184-b4965007c3ca.png)

- Any related issues:
#811

**Comment by jamesmudgett** [comment]
No, this would require adding a background on keyboard which would cause other ux bugs/issues. iOS keyboards are designed with background environment in mind, so will always appear darker on darker backgrounds. That said, the privacy mode could use some redesign entirely.
