### ISSUE TITLE
Editing bookmark should not allow only whitespace for URL or Title

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#832]
Description:
When editing a bookmark, if you use spaces for the URL it is accepted.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
If there is only whitespace in a field, it should be caught as an error. 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6s plus

- Brave Version:
1.3.2

- Steps to reproduce:
    1. Edit a bookmark.
    2. Delete the URL.
    3. Enter spaces and save.

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-ios/issues/806

**Comment by srirambv** [comment]
Same as #831
