### ISSUE TITLE
iOS device is not listed on laptop after sync

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#836]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Android device name is not shown upon sync
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, 
Brave  v 1.4.1  
Apple iOS  10.3.1
- Brave Version (revision SHA):
Brave	0.15.0
rev	8e63cc0
- Steps to reproduce:
    1. Enable Sync on laptop 
    2. Sync an iOS(v1.4) device using the QR Code
    3. Device gets listed but no name shown
    4. Restart browser, still no name
    5. Turn off and turn on Sync, still no name
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
N/A
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.
    
- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25341585/2ec3ad3e-2901-11e7-8933-3938d3a7abf3.png)

- Any related issues:
https://github.com/brave/browser-laptop/issues/8464
https://github.com/brave/browser-android-tabs/issues/222

**Comment by jhreis** [comment]
Just for additional clarification, this is _only_ an issue for using the sync keywords.

**Comment by LaurenWags** [comment]
Removing milestone per standup call
