### ISSUE TITLE
URL bar does not accept any character after the first from Swype keyboard when typing

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#850]
Description: When using the Swype keyboard to type individual characters in the URL bar, the second character of your URL is not displayed (neither are subsequent characters like the 3rd, 4th, etc). Note, you must be typing the characters individually, not using the swipe feature of the keyboard. 

Workaround: If you switch to the standard Apple keyboard without the swype functionality, this is not a problem.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
URL should be able to be typed out using the Swype keyboard just as if you were using the standard Apple keyboard.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS version 10.2.1)

- Brave Version:
1.3.1

- Steps to reproduce:
Pre-condition: Swype keyboard is installed on the iPhone.

1. Tap the URL bar, verify Swype is the keyboard being used, and begin to type something such as nytimes.com. (the URL bar suggests this site)
2. Navigate to the site and add it as a Bookmark.
3. Tap on the URL bar again.
4. This time, type something like 'philadelphia'.
5. You will see that 'pinterest.com' is pre-populated, but the 2nd, 3rd, etc characters you typed were not picked up in the URL bar.
6. Clear out pinterest.com and try something else like 'git', you will see the same results.

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:
#750

**Comment by srirambv** [comment]
Verified on iPhone 7+ running 16.(18.04.17.16)
