### ISSUE TITLE
Added bookmarks only sets the front page as the bookmark

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#861]
Description:
When adding github.com/brave/browser-laptop as a bookmark the bookmarks only sets the URL to github.com and so on with every site!
**Did you search for similar issues before submitting this one?**
Yes
**Expected behavior:**
Should show the exact page you are on
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 5s IOS 10.3.1
- Brave Version:
1.3.2
- Steps to reproduce:
    1. Add a bookmark on github.com/brave/browser-laptop
    2. Edit the bookmark and see that it say github.com as URL
    3. Click on the bookmark and see that it sends you to github.com

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Same as  #862 Closing  #861
