### ISSUE TITLE
Site-Settings Lost on Restart

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-ios#863]
Description:
Site-specific settings are lost when Brave restarts. [Reported on Community](https://community.brave.com/t/brave-no-longer-remembers-site-shield-settings-on-close-ios/2776).

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Site-specific settings are preserved across multiple app sessions.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6s

- Brave Version:
1.4 (17.03.27.14)

- Steps to reproduce:
1. Open Brave
2. Navigate to https://brave.com
3. Turn off all individual shield settings
4. Restart Brave (re-opens to https://brave.com)
5. Observe that individual shield settings are _turned on_

**Comment by acdha** [comment]
Let me know if I can help with testing

**Comment by srirambv** [comment]
This is a regression from https://github.com/brave/browser-ios/issues/645. This was fixed in the previous build.
