### ISSUE TITLE
Line separator overlaps with Brave logo in private tabs

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#875]
The text and logo in private tabs should be moved down to fit 4” screen like the ones seen on iPhone 5, 5s and SE. The line separator overlaps with the brave logo and it would in my opinion look better if you moved down both text and logo in private tabs.

## Original description
Description:
The description and the screenshot has you covered
**Did you search for similar issues before submitting this one?**
Yes
**Expected behavior:**
The line should probably be removed or as a suggestion the lion should be lowered...
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Iphone 5s but is not reproducable on devices with taller screen, thanks @srirambv for testing :slightly_smiling_face: 
- Brave Version:
1.3.2 and 1.3.3
- Steps to reproduce:
    1. Open a private tab on iphone 5s and maby 5

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/25466657/25961746/a9e2fd1c-367b-11e7-8406-32d952b1ecbd.png)

**Comment by jhreis** [comment]
This is due to the smaller device screen size. It is supposed to be a separator between the tracking stats and the main panel. This screen will need a bit of work for smaller device, as the spacing alone is too tight. 4s would even be worse.

**Comment by Jacalz** [comment]
cc @jamesmudgett
