### ISSUE TITLE
Outdated Desktop User-Agent String

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-ios#876]
Description:
Brave for iOS appears to have an outdated _desktop user-agent string_, which causes some sites to fallback to mobile layouts even when the user explicitly requests a desktop layout.

```
let kDesktopUserAgent = "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Version/5.0 Safari/537.36"
```
Source: [/brave/src/BraveApp.swift#L19](https://github.com/brave/browser-ios/blob/00c31d20bf1cc798d44093ad169ae7a3e7e18de4/brave/src/BraveApp.swift#L19)

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Brave should send a _up-to-date_ user-agent string when requesting desktop content.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6s plus

- Brave Version:
1.3.3

- Steps to reproduce:
    1. Open a desktop tab
    2. Navigate to twitter.com/brave
    3. Note message about outdated Safari version

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/815158/26089613/d7c6f886-39c4-11e7-8b4e-a476600fde77.png)

- Any related issues:

**Comment by Jacalz** [comment]
Same thing happens on github too btw 😅

**Comment by Jacalz** [comment]
Closed by https://github.com/brave/browser-ios/pull/941#event-1183849922
