### ISSUE TITLE
Site content doesn't load on gab.ai even with shields down

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#879]
Description: 
Site content doesn't load on gab.ai even with shields down. Issue reported on [community](https://community.brave.com/t/ios-hangs-on-gab-ai/3094). 

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should load the site contents properly

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Reported on iPhone 6s Plus (iOS 10.3.1)
Verified on iPhone 7+ (iOS 10.3.3)

- Brave Version:
1.3.3

- Steps to reproduce:
    1. Go to https://gab.ai/
    2. Log in or create a new account
    3. Tap one of the icons on the top row, e.g home or popular or notifications
    4. "Loading notifications" appears with a spinning circle, and it hangs.

** Website problems only: Yes
- did you check with Brave Shields down? Yes
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? Verified on Firefox works fine

- Screenshot if needed:

- Any related issues:
cc: @jonathansampson

**Comment by Jacalz** [comment]
Loads for me in the latest build of 1.4

**Comment by iccub** [comment]
Tested and it works for me also, let's close it.
