### ISSUE TITLE
Device id is not shown for laptop under sync

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#890]
Description:Device id is not shown for laptop after sync

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should show ID for all devices that are synced 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):iPhone 7+

- Brave Version:
1.4.(17.06.05.12)

- Steps to reproduce:
    1. Enable sync on laptop
    2. Sync iPhone using QR code, ensure bookmarks get synced 
    3. Close settings and go back to devices and settings, no device if shown for laptop

** Website problems only: No
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:
![img_0282](https://cloud.githubusercontent.com/assets/17010094/26815579/0ae67928-4a85-11e7-9144-6b8244ad0a5b.PNG)

- Any related issues:

**Comment by jhreis** [comment]
We have removed the `devices` section from iOS for now.

**Comment by srirambv** [comment]
Moving to 1.4.1 as device names are not part of 1.4
