### ISSUE TITLE
Splash screen not shown on launch

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#891]
Description: Splash screen is not shown upon launch

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should show the splash screen upon launch

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All

- Brave Version:
1.4(17.06.05.12)

- Steps to reproduce:
    1. Clean install 1.4
    2. Launch browser
    3. No splash screen shown, directly shows new tab

** Website problems only: No
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
This was actually intentional. I don't see a ticket for it though. cc'ing @jamesmudgett in case they want to share any details about the decision.

Please remove from any QA test runs.

**Comment by jhreis** [comment]
Created ticket for reference: #896
