### ISSUE TITLE
Bookmarks are not synced between iOS devices

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#892]
Description:
Bookmarks are not synced across iPhones 

**Did you search for similar issues before submitting this one?** 
Yes

**Expected behavior:**
Should sync all bookmarks 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Pyramid 0- Laptop
Pyramid 1 - iPhone 7+
Pyramid 2 - iPhone 6

- Brave Version:
Laptop: 0.16.100
iPhones: 1.4(17.06.05.12)

- Steps to reproduce:
    1. Sync iPhone 7+ with laptop using QR code
    2. Ensure bookmarks are synced on iPhone 
    3. Sync iPhone 6 with iPhone 7+ using QR code on iPhone 7+
    4. Bookmarks are not synced on iPhone 6, Only one bookmark folder synced for me 
    ~~5. Device name is not shown under both devices after sync~~ 
    Edit: Device name shows up after a while only on Pyramid 1 not on Pyraimid 2

** Website problems only: n/a
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:

- Any related issues:

**Comment by Jacalz** [comment]
Could not reproduce on the latest build (17.06.12.13) with iPhone 5s and IPad Air 2 👍

**Comment by srirambv** [comment]
This seems to work on 1.4(17.06.14.13). Was able to sync iPhone 7+ with Laptop using QR code, and iPhone 6 with iPhone 7+ using QR code. Closing the issue for now. Will have to test it once on RC build as well

**Comment by LaurenWags** [comment]
Removing milestone per standup call
