### ISSUE TITLE
Reset and resync doesn't show the device name 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#894]
Description: 
Reset and resync doesn't show the device name 

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should show the device name after sync is reset and resynced

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6, iPhone 7+

- Brave Version:
1.4 (17.06.05.12)

- Steps to reproduce:
    1. Enable sync on laptop and sync with iPhone
    2. Ensure device name is listed on both laptop and iPhone
    3. Reset sync on iPhone  and enable it again with a different name and sync to same laptop profile
    4. Device name is not shown on both iPhone and Laptop

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:
Laptop
![image](https://cloud.githubusercontent.com/assets/17010094/26819773/4131559e-4a98-11e7-9b47-0ba70f05ec83.png)
Mobile
![image](https://cloud.githubusercontent.com/assets/17010094/26819791/5f6fbfbe-4a98-11e7-8f0c-75ffd5fa4875.png)

- Any related issues:
https://github.com/brave/browser-android-tabs/issues/254

**Comment by srirambv** [comment]
Moving to 1.4.1 as device names are not part of 1.4

**Comment by LaurenWags** [comment]
Removing milestone per standup call
