### ISSUE TITLE
Device name doesn't show when synced using secret words

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#895]
Description:
Device name doesn't show when synced using secret words

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should show device name after entering secret word

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (iOS 10.3.3)

- Brave Version:
1.4 (17.06.05.12)

- Steps to reproduce:
    1. Enable Sync on Laptop 
    2. Enter a device name on iPhone Sync screen and tap on enter secret words
    3. Type in secret code and sync, Device name is not shown for iPhone

** Website problems only: N/A
- did you check with Brave Shields down?N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?N/A

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/26826417/f3466888-4ab0-11e7-8073-e61ff1384925.png)
![image](https://cloud.githubusercontent.com/assets/17010094/26826459/2811695a-4ab1-11e7-9a93-71575c8ddf96.png)

- Any related issues:

**Comment by jhreis** [comment]
We have removed the `devices` section from iOS for now.

**Comment by LaurenWags** [comment]
Removing milestone per standup call
