### ISSUE TITLE
TP: add whitelisted url connect.facebook.com

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#90]
@SergeyZhukovsky I am going to add this, what is the test case for this? thanks

**Comment by SergeyZhukovsky** [comment]
Sorry Garvan, I think I missed that notification :).
Test cases:
- go to https://www.khanacademy.org/;
- click Log in(in the right top);
- login using facebook.

**Comment by garvankeeley** [comment]
Sigh, just discovered the khanacademy site is quite broken on Brave iOS, investigating that first

**Comment by garvankeeley** [comment]
Looks like it is broken on Dolphin browser also

**Comment by SergeyZhukovsky** [comment]
Hm, just checked and it works on Android.

**Comment by garvankeeley** [comment]
Look to me like UIWebView-based browsers have site problems, the hamburger menu doesn't work, and the facebook connect link doesn't work
