### ISSUE TITLE
Bookmark name overlaps with the folder > indicator

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#902]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Bookmark name overlaps with the folder > indicator

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 7+ (iOS 10.3.3)

**Brave Version:**
1.3.3 & 1.4 (All versions before)

**Steps to reproduce:**
    1. Tap on settings 
    2. Tap on New folder
    3. Enter a extremly long name, tap on done, Name gets overlapped on `>` icon

**Actual Behavior**
Bookmark name overlaps with the folder > indicator

**Expected Behavior**
Should truncate the name and  show `...` before the `>` icon 

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Screenshot if needed:**
![image](https://user-images.githubusercontent.com/17010094/27046259-ac7f0e92-4f9b-11e7-9790-0fdafaf1e566.png)

**Any related issues:**

**Comment by LaurenWags** [comment]
Could not reproduce on iOS10 iPad or iPhone both using version 1.6.2 (18.05.29.10)
