### ISSUE TITLE
Tabs lost after re-launching the app

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#903]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Tabs lost after re-launching the app

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 6(iOS 10.3.3)
iPhone 7+(iOS 10.3.3)

**Brave Version:**
1.4(17.06.12.13)

**Steps to reproduce:**
    1. Browser for a while with lots of tabs open
    2. Double tap home button and kill the app
    3. Wait for a while before relaunching the app, all tabs are lost upon restart

**Actual Behavior**
All tabs are lost when app is killed and launched after a while 

**Expected Behavior**
Should retain all tabs irrespective of when the app is opened after closing it

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
Not that I have experienced, but it is as per https://github.com/brave/browser-ios/issues/788#issuecomment-307659178

**Can this issue be consistently reproduced?**
Yes on the beta build

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:** N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? N/A

**Screenshot if needed:**

**Any related issues:**
#788

**Comment by Jacalz** [comment]
With 100 tabs the latest version is really slow to open and 4 tabs got removed when trying to reproduce 😬

**Comment by Jacalz** [comment]
Yeah I could reproduce on the latest version 😬

**Comment by jhreis** [comment]
Closed per: https://github.com/brave/browser-ios/pull/925
