### ISSUE TITLE
Translation not working when device language is changed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#904]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Translation not working when device language is changed

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 6 (iOS 10.3.3.)
iPhone 7+ (iOS 10.3.3)

**Brave Version:**
1.4(17.06.12.13)

**Steps to reproduce:**
    1.  Install Brave beta 1.4(17.06.12.13)
    2.  Change device language to Hindi  (non supported language) , Wait for the device to make changes 
    3.  Open Brave, no text is translated, Only the stat counter numerical value is changed 

**Note: Changing language to Russian/Chinese/French/Spanish doesn't change any thing even the stats counter values are not changed and shows correct numerical values**

**Actual Behavior**
App translation is not working when phone language is changed 

**Expected Behavior**
App translations should work when the device language is set to one of the supported languages (Chinese, French, German, Indonesian, Italian, Japanese, Korean, Malay, Polish, Portuguese, Russian, Spanish, Swedish, Ukrainian)

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
N/A

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Screenshot if needed:**
Device language set to Hindi 
![image](https://user-images.githubusercontent.com/17010094/27069969-e7db46a4-500e-11e7-8dca-ac11cb90fa4e.png)
**Safari after device language set to Hindi**
![image](https://user-images.githubusercontent.com/17010094/27070008-0c96ed5e-500f-11e7-8699-0966a3dbf181.png)

**Any related issues:**

**Comment by jhreis** [comment]
This currently happens in production build too.

**Comment by srirambv** [comment]
Translation works. Verified for Russian.
