### ISSUE TITLE
not all code words are visible on iPad

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#910]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Code Words for Sync are not all visible on iPad.

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPad

**Brave Version:**
1.4 (17.06.12.13)

**Steps to reproduce:**
    1. Sync iPad with another device (my Pyramid 0 was iPhone, Pyramid 1 was iPad)
    2. Navigate to Settings > Devices & Settings
    3. Select the + sign in the Devices window
    4. Select Code Words
    5. Not all Code Words are visible. Turning the iPad to be landscape instead of portrait does not help.

**Actual Behavior**
Right hand column of code words is not able to be entirely seen

**Expected Behavior**
All code words should be visible or at least be able to be scrolled to so they can be read.

**Is this an issue with Beta build?**
Preview build

**Is this an issue in the currently released version?**
No

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Screenshot if needed:**
iPad held in Portrait 
![img_0006](https://user-images.githubusercontent.com/28145373/27088082-b7f91c3e-5024-11e7-9678-91c6d3794b76.PNG)

iPad held in Landscape
![img_0007](https://user-images.githubusercontent.com/28145373/27088166-f1bc8a96-5024-11e7-9539-aceb6176f300.PNG)

**Any related issues:**

**Comment by LaurenWags** [comment]
Seeing this again in 1.4 (17.07.13.15)

**Comment by jhreis** [comment]
Fixed again per ^ (see commit for additional details)
