### ISSUE TITLE
can't use 1Password on iPad

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#913]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Unable to use 1Password on iPad to login.

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPad

**Brave Version:**
version 1.4 (17.06.12.13)

**Steps to reproduce:**
    1. Install and configure 1Password on iPad.
    2. Open Brave.
    3. In Settings, select 1Password as the Password Manager.
    4. Navigate to a site that you have configured credentials for in 1Password.
    5. Attempt to use 1Password to login to the site.

**Actual Behavior**
Unable to access 1Password from slide out keyboard. Also unable to tap on the icon in the upper right corner.

**Expected Behavior**
Should be able to access 1Password credentials to login to site.

**Is this an issue with Beta build?**
Found in preview build.

**Is this an issue in the currently released version?**
Yes, checked version 1.3.3 (17.05.10.13)

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Screenshot if needed:**
![img_0009](https://user-images.githubusercontent.com/28145373/27094053-e0a8eee0-5036-11e7-8047-27f6019491e1.PNG)

**Any related issues:**

**Comment by LaurenWags** [comment]
seeing this issue again in 1.4 (17.07.13.11)

**Comment by jhreis** [comment]
Fixed per 1.4 (17.07.31.11)
