### ISSUE TITLE
Unable to connect error shown when sync with code screen is kept open for a while

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#914]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Unable to connect error shown when sync with code screen is kept open for a while

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 6 (iOS 10.3.3)

**Brave Version:**
1.4.(17.06.12.13)

**Steps to reproduce:**
     1. Enable sync on Laptop 
    2. Open sync menu in iPhone, select enter code words
    3. Enter all code words make couple of mistakes and tap on done
    4. Ensure the wrong word is shown in the error message and asks to correct 
    5. Enter the correct words and keep the screen open for a while without tapping on Done
    6. Tap on done button shows `Unable to connect` message 
    7. Go back to main settings page and open sync, sync is setup
    8. Check laptop for the synced device list, device name is not listed but its synced and bookmarks are synced on iPhone

**Actual Behavior**
Unable to connect error shown when sync with code screen is kept open for a while

**Expected Behavior**
Sync should work properly irrespective of the time taken to sync

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
N/A

**Can this issue be consistently reproduced?**
Tried twice on new install on iPhone 6 and was reproed both the time

**Extra QA steps:**
    1.  
    2. 
    3.

** Website problems only:** NA
- did you check with Brave Shields down?NA
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?NA

**Screenshot if needed:**

**Any related issues:**

**Comment by LaurenWags** [comment]
Removing milestone per standup call
