### ISSUE TITLE
first tab is lost when reopening Brave after it had been closed

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#916]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
First tab is lost when Brave is reopened. Several tabs had been open (6 with the most recently opened one as the active tab) when the browser was closed from running in the background. I waited 2-5 minutes and re-opened Brave. On re-open, the first tab was lost so I only had 5 tabs open instead of 6.

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPad and iPhone 6

**Brave Version:**
version 1.4 (17.06.12.13)

**Steps to reproduce:**
    1. Close any open tabs. Close Brave. Double tap the home button and close Brave from the background.
    2. Reopen Brave and open 6 tabs with 6 different sites. Leave the 6th tab as the active tab.
    3. Close Brave. Double tap the home button and close Brave from the background.
    4. Wait 2-5 minutes. Reopen Brave.

**Actual Behavior**
First tab is lost. You can see in the tab count 5 is displayed instead of 6. If you scroll/swipe to view the first tab, it is not displayed.

**Expected Behavior**
All tabs should be retained.

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
I could not reproduce in currently released version (1.3.3), but related issues (below) mention tab loss.

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Screenshot if needed:**

**Any related issues:**
https://github.com/brave/browser-ios/issues/903
https://github.com/brave/browser-ios/issues/788

**Comment by jhreis** [comment]
Closed per: https://github.com/brave/browser-ios/pull/925
