### ISSUE TITLE
iOS to iOS sync doesn't work

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#917]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
iOS to iOS sync doesn't work

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 7+ (iOS 10.3.3)
iPhone 6 (iOS 10.3.3)

**Brave Version:**
1.4 (17.06.12.13)

**Steps to reproduce:**
    1. Enable Sync on iPhone 7+
    2. Sync iPhone 6 using the secret codes, ensure both devices have the same sync codes
    3. Add bookmark on iPhone 6, doesn't get synced on iPhone 7+
    4. Add a bookmark folder on iPhone 7+ and add a bookmark in it, doesn't get synced on iPhone 6

**Actual Behavior**
iOS to iOS sync doesn't work

**Expected Behavior**
Should sync between iOS devices

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
N/A

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:** NA
- did you check with Brave Shields down? NA
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? NA

**Screenshot if needed:**

**Any related issues:**

**Comment by jhreis** [comment]
Closing as duplicate: #892

**Comment by jhreis** [comment]
My bad, other issue has pyramid 1 being laptop. This only relates to iOS issues. From a technical perspective, this is probably the same thing, but good to have tickets for testing verification.

**Comment by srirambv** [comment]
Works on 1.4(17.06.14.13). Bookmark added on both devices syn to each other. Closing the issue for now. Needs to be retested for RC build.

**Comment by LaurenWags** [comment]
Removing milestone per standup call
