### ISSUE TITLE
Moving bookmark location on other device is not synced on iOS

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#919]
**Did you search for similar issues before submitting this one?**
yes

**Description:**
Moving bookmark location on other device is not synced on iOS

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
Pyramid 0 - Laptop 
Pyramid 1  - iPhone 7+
Pyramid 2  - Android Tablet

**Brave Version:**
Laptop 0.17.3
iPhone 7+  1.4(17.06.14.13)
Android 1.0.22

**Steps to reproduce:**
    1. Enable Sync on Laptop, Sync iPhone and then Sync Android
    2. Add bookmark on laptop, ensure it syncs on all devices
    3. Move the synced bookmark into a new folder on Android device
    4. Bookmark is still on root folder, creates a new folder on iOS, but changes reflected on laptop 

**Actual Behavior**
Moving bookmark location on other device is not synced on iOS

**Expected Behavior**
Should sync changes correctly

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
N/A

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Screenshot if needed:**

**Any related issues:**

**Comment by jhreis** [comment]
Fixed per: https://github.com/brave/browser-ios/commit/62ffd2e2b867dc79210ef0da90ca9b84703ca669

**Comment by LaurenWags** [comment]
Removing milestone per standup call
