### ISSUE TITLE
Importing Bookmarks HTML file on Laptop after creating sync group puts some bookmarks on root folder

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#920]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Importing Bookmarks HTML file on Laptop after creating sync group puts some bookmarks on root folder

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 7+ (iOS 10.3.3)

**Brave Version:**
Laptop - 0.17.3
iPhone 7+ - 1.4(17.06.14.13)

**Steps to reproduce:**
    1. Enable Sync on Laptop and sync iPhone using QR code
    2. Import a large bookmark HTML file on Laptop 
    3. Some bookmarks are added under the root folder

**Actual Behavior**
Importing Bookmarks HTML file on Laptop after creating sync group puts some bookmarks on root folder

**Expected Behavior**
Sync import should be proper irrespective of sync group

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
N/A

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Screenshot if needed:**

**Any related issues:**

**Comment by LaurenWags** [comment]
Removing milestone per standup call
