### ISSUE TITLE
sync : importing a large group of bookmarks on laptop blocks iOS UI intermittently

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#921]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
While syncing a large set of imported bookmarks, the iOS ui will block in many places at random intervals.

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 6s Plus

**Brave Version:**
0.17.3 (laptop ((used Windows for test))) & 1.4 (17.06.15.13) iOS

**Steps to reproduce:**
    1. With clean profiles, configure sync between a laptop and a phone
    2. import a large amount of bookmarks (6000+ ) on laptop
    3. try to interact with the iOS app after the import folder first appears 

**Actual Behavior**
Interactions will randomly block (folder nav in bookmarks, text entry on urlbar, etc)

**Expected Behavior**
The sync should be backgrounded and non-blocking.

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
No

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Screenshot if needed:**

**Any related issues:**

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/sync/issues/105

**Comment by srirambv** [comment]
Reopening issue based on https://github.com/brave/sync/issues/105#issuecomment-309541865

**Comment by jhreis** [comment]
Should be fixed per: 9a8f179
