### ISSUE TITLE
sync : bookmark order inside of folders is not being maintained

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#923]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
When syncing a large data set, with nested subfolders, it was noticed that the order of bookmarks is not being maintained.

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 6s Plus

**Brave Version:**
laptop 0.17.3 & ios 1.4 (17.06.15.13)

**Steps to reproduce:**
    1. with clean profiles on both devices, configure for sync
    2. import a large amount of bookmarks
    3. check the order of bookmarks in folders after they sync to iOS

**Actual Behavior**
the order of the bookmarks is unintelligible

**Expected Behavior**
the order should match the order on laptop

**Is this an issue with Beta build?**
yes

**Is this an issue in the currently released version?**
no

**Can this issue be consistently reproduced?**
yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Screenshot if needed:**
<img width="1599" alt="screen shot 2017-06-15 at 3 00 23 pm" src="https://user-images.githubusercontent.com/1434040/27199576-22c8d51e-51dc-11e7-9a3e-efa2949ac913.png">

![image uploaded from ios](https://user-images.githubusercontent.com/1434040/27199664-75421a4e-51dc-11e7-9a56-01c1d4624c94.jpg)

**Any related issues:**

**Comment by srirambv** [comment]
Closed in favour of https://github.com/brave/sync/issues/104
