### ISSUE TITLE
Bookmarks are being sent to laptop when bookmark sync is off

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#924]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
When bookmark sync is off (not Remove this Device), bookmarks are being synced with laptop.

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
found with iPhone

**Brave Version:**
1.4 (17.06.15.13)

**Steps to reproduce:**
    1. have an iOS device that is part of an active sync group
    2. navigate to settings > Devices & Settings > toggle bookmarks to off (not Remove this Device)
    3. create a bookmark on iOS device.
    4. Bookmark is synced to laptop.

**Actual Behavior**
Bookmark created on iOS device is synced to laptop.

**Expected Behavior**
Bookmark created on iOS device should not be synced to laptop.

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
No

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?

**Screenshot if needed:**

**Any related issues:**

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/sync/issues/108
