### ISSUE TITLE
Crash When using "Open in Brave"

### ISSUE THREAD

**Issue by jhreis** [brave/browser-ios#926]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Some users are experiencing a hard crash where when long-pressing on a link inside of a 3rd party application (e.g. Twitter, Slack), and selecting the "Open in Brave" option when the action menu appears.

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**

**Brave Version:**
1.3.3

**Steps to reproduce:**
    1. Go to Twitter
    2. Find Link - Longpress
    3. Select "Open in Brave"
    4. Brave launches, followed by hard crash

**Actual Behavior**
Crash

**Expected Behavior**
Brave opens the URL it was launched with.

**Is this an issue with Beta build?**
Unknown

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
It is consistently reproducible for the users experiencing the crash.
(I am personally unable to repro)

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:**
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)?
NA

**Screenshot if needed:**

**Any related issues:**

**Comment by Jacalz** [comment]
Can not reproduce on 1.3.3 using iPhone 5s, iOS 10.3.2

**Comment by Jacalz** [comment]
Can reproduce on iPad running iOS 10.3.3 with Brave 1.4
STR:
1. Have brave closed (not running in background)
2. Long press on link and "open in Brave"
3.  Brave crashes with hard crash/ though sometimes I have seen a soft crash where brave restores to the last open tabs, the link I opened is dropped then.

**Comment by LaurenWags** [comment]
Can reproduce on iPad (10.3.1) and iPhone6 (10.3.2):
STR:
1. Have brave closed (not running in background)
2. From Twitter app or Slack app, long press on link and select "open in Brave" 
3. Brave crashes. I have only seen a soft crash where brave restores to the last open tabs (the first tab in the set is now the tab in focus), the link I tried to open is dropped.

**Comment by srirambv** [comment]
Initially didn't work on iPhone 7+/6. But now able to consistently reproduce soft crash on both devices
1. Open Twitter/Slack
2. Long press on any link and select open in brave
3. Brave launches, opens the tab and crashes but still running in background
4. Relaunch Brave, tabs are all restored

**Comment by kjozwiak** [comment]
I've ran into this again today but I don't have reliable STR. From my experience, Brave gets into a state where it basically becomes unstable. When this happens, opening any links via third party applications will crash it every time. These are the crash reports that I got from the device:

- [17.08.25.08 (1.4.1) - Current Release Crash](https://github.com/brave/browser-ios/files/1264631/currentReleaseCrash.txt)
- [17.08.28.10 (1.4.1) - Local Build Crash](https://github.com/brave/browser-ios/files/1264632/localBuildCrash.txt)

In this instance, I can only reproduce the issue when Brave is completely closed and I send a link to it from a third party application (Twitter, Slack etc..). However, I did run into this before where it happened even if Brave was opened in the background.

**Comment by jhreis** [comment]
Just wanted to add, this has been reported via many many sources over the last handful of releases. Definitely seems to be a moving target, but I think we have some solid info to work off of now. Many thanks @kjozwiak

**Comment by jhreis** [comment]
Should be fixed along with #1136

**Comment by LaurenWags** [comment]
Still able to reproduce in 1.4.2 (17.09.08.20) on iPad iOS 10 (10.3.1)

**Comment by jhreis** [comment]
This issue is still being seen. The fix was only partial apparently.

**Comment by Jacalz** [comment]
The initial fix seemed to fix the issue for me, have not hade a singe issue for a long time now

**Comment by Jacalz** [comment]
Has happened once now yesterday but not any more than that

**Comment by srirambv** [comment]
Work fine with latest beta. Although having both beta and  prod build, always opens the link in prod build irrespective of selecting either app to open.

Verified on iPad iOS 11 and iPhone 7+ iOS10
