### ISSUE TITLE
No network connection error message shown when trying to sync offline but enable sync

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#927]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
No network connection error message shown when trying to sync offline

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 7+ (iOS 10.3.3) - Pyramid 1
iPhone 6 (iOS 10.3.3) - Pyramid 0

**Brave Version:**
1.4(17.06.15.13)

**Steps to reproduce:**
    1. Enable Sync on device 1(iPhone 6) which is connected to internet
    2. On device 2(iPhone 7+) disconnect from internet and type in the code words shown on device 1(iPhone 6)
    3. Sync loading spinner is shown for ~40 seconds and then goes back to `Enter code words` screen, No network error message is shown
    4. Tap on Sync button,  Goes back to sync main menu and shows the sync is enabled

**Actual Behavior**
No network connection error message shown when trying to sync offline but enable sync

**Expected Behavior**
Should show network error message and should not sync

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
N/A

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Screenshot if needed:**

**Any related issues:**
cc: @ayumi @diracdeltas @jamesmudgett

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/sync/issues/103

**Comment by LaurenWags** [comment]
Removing milestone per standup call
