### ISSUE TITLE
Device gets synced even when offline 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#928]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Device gets synced even when offline

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10.3.3) - Pyramid 0
iPhone 7+ (iOS 10.3.3) - Pyramid 1 

 - Brave Version:
1.4 (17.06.15.13) on both devices

- Steps to reproduce:
    1. Enable Sync on device 1 (iPhone 6)
    2. Go offline in device 2 (iPhone 7+) and open sync and enter code words from device 1
      3. The sync spinner keeps rotating and then closes after ~40secs, tap on <kbd>< Sync </kbd> button, shows sync main screen which shows enabled bookmarks switch and <kbd>+</kbd> button on top right corner
      4.  Tap on <kbd>+</kbd>, select code words, shows the sync code words which was typed in in step 2
      5. Keep device 2 (iPhone 7+) offline and add a bookmark in device 1(iPhone 6), 
      6. Enable internet on device 2 (iPhone 7+), bookmark not synced
      7. Add another bookmark on device 1 (iPhone 6), still bookmark not shown on device 2 (iPhone 7+)
      8. Add a bookmark on device 2(iPhone 7+), shows instantly on device 1(iPhone 6)
      9. Close(kill) and reopen brave on device 2(iPhone 7+), bookmark added in step 5 still doesn't come up but bookmark added in step 7 shows up now. 

- Same behavior when synced using QR Code, QR code flashes red box but sync is still enabled and able to repeat bookmarks steps in similar fashion

- Actual Behavior
Device gets synced even when offline 

- Expected Behavior 
Sync should not work until both devices are online

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Screenshot if needed:

- Any related issues:
#927

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/sync/issues/102

**Comment by LaurenWags** [comment]
Removing milestone per standup call
