### ISSUE TITLE
Blocked colors in shield panel are different than laptop

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#932]
- Did you search for similar issues before submitting this one?
Yes
- Description:
The colors on the blocked count in the site shield settings panel is wrong on iOS vs browser-laptop
Browser-laptop:
![image](https://user-images.githubusercontent.com/25466657/27447468-618b4b1a-5781-11e7-98a9-44f53a6f14ce.png)
browser-ios:
![image uploaded from ios](https://user-images.githubusercontent.com/25466657/27449596-38e9df2a-5789-11e7-9ff3-cd02a8ab2c5d.jpg)

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Does not matter
- Brave Version:
1.3.3 and 1.4
- Steps to reproduce:
    1. Navigate to any site on iOS
    2. Open the shield panel

    1. Navigate to any site on browser-laptop
    2. Open the shield panel
- Actual Behavior
The colors on the blocked count is wrongs vs browser-laptop
- Expected Behavior
The colors should be the same
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yeah

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
cc @jamesmudgett for UI input.

**Comment by Jacalz** [comment]
Closed by https://github.com/brave/browser-ios/commit/a1dd6a9139d7c4a68f0781e3d272a436d0e92713
