### ISSUE TITLE
Move 'Private' and + to bottom of iOS screen

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#934]
- Did you search for similar issues before submitting this one?
Yes

- Description:
From Community (https://community.brave.com/t/ios-new-window-button-relocation/3157)

On iOS when you click the number on the lower right to view all open windows, it would be easier to click the "+" to open a new window if it were on the bottom of the screen instead of the top. The same goes for the "Private" button. With a big phone it is a pain to reach up to the top right corner to press these buttons when using the phone with one hand.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone

- Steps to reproduce:
    1. Open Brave.
    2. Tap on the box in the lower right corner that displays the number of tabs you have open.
    3. 'Private' and + options are at the top of the screen (upper right corner), user is suggesting they be brought to the bottom of the screen.

- Screenshot if needed:
![img_4327](https://user-images.githubusercontent.com/28145373/27484668-14e574a8-57f8-11e7-8227-6bf2c2c8a9b0.PNG)

**Comment by jamesmudgett** [comment]
This is in the works.

**Comment by Jacalz** [comment]
Yeah this is currently fixed in 1.4.3 🙂
