### ISSUE TITLE
Translation issues on 1.4

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#935]
- Description:
Below are the issues with translation on the beta build.

- **Stats counter text not translated for all languages**
- **No translations shown for Swedish**

- Screenshot if needed:
# French
![image](https://user-images.githubusercontent.com/17010094/27594762-9b65cb4c-5b52-11e7-8068-34284137be86.png) 
************************************
![image](https://user-images.githubusercontent.com/17010094/27594798-b5ff287c-5b52-11e7-8a73-3479b6aab5ef.png)
# 
# German
![image](https://user-images.githubusercontent.com/17010094/27594828-cdff5e4c-5b52-11e7-9c18-27f80fdfd2a5.png)

# Italian
![image](https://user-images.githubusercontent.com/17010094/27595379-6a6af8d0-5b54-11e7-832d-6b604440e287.png)

# Show Password Picker ( **ALL LANGUAGES**)
![image](https://user-images.githubusercontent.com/17010094/27595450-a223545c-5b54-11e7-9979-e21b70cfd4c4.png)

# Korean
![image](https://user-images.githubusercontent.com/17010094/27595499-bcaba43c-5b54-11e7-8d31-870331dd3973.png)

# Polish
![image](https://user-images.githubusercontent.com/17010094/27595690-4b76f6e4-5b55-11e7-9d03-af2d1a85bca4.png)
![image](https://user-images.githubusercontent.com/17010094/27595754-73753cdc-5b55-11e7-9147-eedea1ac113b.png)

# Portugese (Brasil) 
![image](https://user-images.githubusercontent.com/17010094/27595912-e9d0775c-5b55-11e7-91ab-4b2f41724a9e.png)

# Ukrainian 
![image](https://user-images.githubusercontent.com/17010094/27596178-ae9af684-5b56-11e7-80a9-1abdd1242946.png)
 
# Spanish
![image](https://user-images.githubusercontent.com/17010094/27596512-a9097a1e-5b57-11e7-8111-3ee162e6f88b.png)

# Indonesia 
![image](https://user-images.githubusercontent.com/17010094/27594845-d821c40a-5b52-11e7-803c-6cda8ac0e79d.png)
![image](https://user-images.githubusercontent.com/17010094/27595044-7005b902-5b53-11e7-89db-97fba319ac98.png)
![image](https://user-images.githubusercontent.com/17010094/27595031-69fada24-5b53-11e7-8e85-405f3b41e68d.png)
![image](https://user-images.githubusercontent.com/17010094/27595219-fd18f444-5b53-11e7-800a-db3b05a66066.png)
![image](https://user-images.githubusercontent.com/17010094/27595365-5a48c81a-5b54-11e7-943f-1c6d3424161a.png)

**Comment by jamesmudgett** [comment]
@jhreis string have been moved into strings localizable wrapper. Many of the others highlighted here are just missing translations.
