### ISSUE TITLE
Stats counter text in not translated

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#937]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Stats counter text in not translated

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All

- Brave Version:
1.4

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Still see some issue with Italian.

**Comment by Jacalz** [comment]
I don´t see the issue when using the Swedish language in 1.4

**Comment by Jacalz** [comment]
Italian has 11 strings that is not currently translated, maby thet is why?
