### ISSUE TITLE
Browser crashes when search opened from share menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#955]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Browser crashes when search opened from share menu

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (iOS 10.3.3)

- Brave Version:
1.4 (17.17.12.19)

- Steps to reproduce:
    1. Open any site in a new tab
    2. Tap on the share button 
    3. Tap on search button, browser crashes

- Actual Behavior
Browser crashes when search opened from share menu

- Expected Behavior
Should not crash, should open the search menu

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
Fixed per above.
