### ISSUE TITLE
Crash issues on iOS 1.4(17.07.12.19)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#956]
## Issues causing crash on iOS 1.4(17.07.12.19)

1. [x] Enter code words for sync causes crash
2. [x] Report bug causes crash
3. [x] Search from share causes crash (#955)
4. [x] Reopening browser immediately after crash causes a second crash
5. [x] Open a desktop site causes crash
6. [x] Clear browsing data causes crash

**Comment by srirambv** [comment]
No crash so far on the new build 1.4(17.07.13.11)

**Comment by Jacalz** [comment]
Yes, no crashes for me on that version too but on 14 (17.07.19.8) it crashes when switching to private tabs and pressing the + to open a new 😕

**Comment by Jacalz** [comment]
@sriram can this be closed?

**Comment by jhreis** [comment]
Closing. If new crashes arise, please create new tickets.
