### ISSUE TITLE
Sync - Get a new sync code button does not appear to work

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#960]
- Did you search for similar issues before submitting this one?
Yes

- Description:
When clicking on the get a new sync code button, there is no response from the UI

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6s +

- Brave Version:
1.4 

- Steps to reproduce:
    1. Click on the Get a new sync code button

- Actual Behavior
Nothing happens

- Expected Behavior
The user should have created a new sync group

- Is this an issue with Beta build?
yes

- Is this an issue in the currently released version?
no

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Worked for me on iPhone 7+

**Comment by LaurenWags** [comment]
Removing milestone per standup call
