### ISSUE TITLE
Auto fill password is not working

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#961]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Auto fill password is not working

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (iOS 10.3.3)

- Brave Version:
1.4 (17.07.12.19)

- Steps to reproduce:
    1. Visit http://trac.torproject.org/projects/tor/login
    2. Login with credentials, tap on save login for the password manager
    3. Revisit login page, userid/password isn't auto populated in the form

- Actual Behavior
Auto fill password is not working

- Expected Behavior
Should autofill credentials

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
Closed per referenced commit.
