### ISSUE TITLE
App unresponsive during sync

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#964]
- Did you search for similar issues before submitting this one?
Yes

- Description:
App unresponsive during sync

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All iOS device

- Brave Version:
1.4 (17.07.13.15)

- Steps to reproduce:
    1. Create Sync group on Laptop 
    2. Import a huge amount of bookmarks
    3. Sync iOS device, becomes unresponsive when sync is in progress

- Actual Behavior
App unresponsive during sync

- Expected Behavior
Sync should not impact app performance

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
Duplicate of #921

**Comment by LaurenWags** [comment]
Removing milestone per standup call
