### ISSUE TITLE
Crash sometimes occurs while bookmarks are syncing

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#968]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Sometimes iOS crashes while syncing bookmarks.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone

- Brave Version: 
1.4 (17.07.13.15)

- Steps to reproduce:
1. Laptop: Open and enable Sync.
2. iOS: Open and join Laptop's Sync profile. Close browser.
3. Laptop: Import  bookmarks. (I imported 1500)
4. Laptop: Wait for Sync uploads to finish (console shows "got 0 decrypted records in BOOKMARKS after {timestamp}"). Wait an additional 3 minutes.
5. iOS: Open and wait for Sync to begin.
6. iOS: monitor iOS device, crash may occur.

- Actual Behavior
iOS may crash.

- Expected Behavior
iOS should not crash while sync is occurring.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
No, seen by me and @srirambv but not consistently.

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
- STR for crash

   1. Enable Sync on Laptop
   2. Sync iPhone 6 with laptop with QR Code
   3. Import boookmarks from file on laptop (Used the 1000 bookmarks) 
   4. Wait for iPhone to start sync 
   5. When app hangs during sync tap on the bookmarks icon couple of times, browser crashes
   6. Restart app all open tabs are lost
