### ISSUE TITLE
Some elements not visable for a couple of seconds when starting

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#974]
- Did you search for similar issues before submitting this one?
Yes
- Description:
When starting the app some elements are not visible started to happen with the latest beta update (17.07.19.08)
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 5
- Brave Version:
1.4 (17.07.19.08)
- Steps to reproduce:
    1. Start Brave

- Actual Behavior
Elements not shown for a second
- Expected Behavior
Should show elements
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
[![IMG_3374.png](https://s22.postimg.org/91560uvc1/IMG_3374.png)](https://postimg.org/image/eck2lkhel/)
- Any related issues:

**Comment by Jacalz** [comment]
My computer acted weird that is why the milestones has a weird story 😂

**Comment by jamesmudgett** [comment]
Thank you for reporting.

**Comment by Jacalz** [comment]
No problem, always happy to help 🙂🦁
