### ISSUE TITLE
bookmarks dont appear in manager but are in toolbar

### ISSUE THREAD

**Issue by chronakazi** [brave/browser-ios#976]
- Did you search for similar issues before submitting this one? 
yes

- Description: 
bookmarks page at about:bookmarks is blank even though my bookmarks bar is full and the dropdown menu in finder has all my bookmarks.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
MacBooc Pro mid 2014 macOS Sierra 10.12.5

- Brave Version:
0.17.19 rev 4e46480

- Steps to reproduce:
n/a

- Actual Behavior
no bookmarks in bookmark manager

- Expected Behavior
my bookmarks and folder structure imported from sync

- Is this an issue with Beta build?
yes

- Is this an issue in the currently released version?
not sure

- Can this issue be consistently reproduced?
on this machine only yes

- Extra QA steps:
n/a

- Website problems only: 
no

- did you check with Brave Shields down? 
yes

- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 
no

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/25531854/28416782-1ee543f8-6cf1-11e7-81d8-ab204f4d02c5.png)

- Any related issues:

**Comment by srirambv** [comment]
This is a laptop issue and the fix is in 0.19.x (https://github.com/brave/browser-laptop/issues/9716)
