### ISSUE TITLE
Inconsistant empty bookmark folder bugs

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#978]
- Did you search for similar issues before submitting this one?
Yes
- Description:
Both @jhreis and I have noted that there are some inconsistant strange bugs regarding empty bookmark filders, these where the ones that I have run in to a couple of times:
- [x] Swipe to delete not working for empty folder
- [x] Remove folders in folders not working 
- [x] Edit bookmarks with only folders as bookmarks doesn't show a delete symbol
- [x] Renaming an empty folder within a folder gets hidden
- [x] Folders changed names but still show right name in them
- [x] Folders duplicate

- Device (iPhone5, iPhone6s plus, iPad 3, ?): IPhone 5s

- Brave Version:
1.4 (17.07.20.16)
- Steps to reproduce:
    The bugs listed above speaks for them selves and it is not always possible to replicate them 😅

- Actual Behavior
Strange bugs see above
- Expected Behavior
The bugs should not be able to be replicated
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
No
- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
Should all be fixed per: 9a8f1791b6011cbed74441f934d30b6ab87e1b07
