### ISSUE TITLE
[Request] Support customization of Dashboard background image

### ISSUE THREAD

**Issue by aleclarson** [brave/browser-ios#981]
#### Did you search for similar issues before submitting this one?
Yes

#### Description:
I'd like to have a customized background image for the Dashboard. Not a fan of the randomized images, not to mention the progressive loading of the interlaced image.

**Comment by Jacalz** [comment]
I would recommend you to open this issue in the right github repository 😉
github.com/brave/browser-laptop

**Comment by aleclarson** [comment]
Whoops. Sorry!

**Comment by Jacalz** [comment]
No problem 🙂
