### ISSUE TITLE
Swift 3 update takes more than 3 times as much space

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#982]
- Did you search for similar issues before submitting this one?
Yes
- Description:
Swift 3 beta takes 3 times as much data
- Device (iPhone5, iPhone6s plus, iPad 3, ?): IPhone 5s

- Brave Version:
1.4 (17.07.20.16)
- Steps to reproduce:
    1. Install
    2. Check in settings

- Actual Behavior
3x the size
- Expected Behavior
A tad bit more than 1.3.3
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes have reinstalled the app 2 times

- Screenshot if needed:
Brave:
[![IMG_3393.jpg](https://s17.postimg.org/8rsl09ynz/IMG_3393.jpg)](https://postimg.org/image/uqyznhfi3/)
BraveBeta:
[![IMG_3392.jpg](https://s1.postimg.org/oi3ihvmnj/IMG_3392.jpg)](https://postimg.org/image/8jusrqsff/)

**Comment by Jacalz** [comment]
Not only does this take more storage but it also makes it impossible to download on cellular data 😕

**Comment by jhreis** [comment]
This has been fixed, and further improved with bitcode enabled.

This will not be show an improvement to beta or local builds. It in fact, makes them much worse, but production versions are now sitting at around 65MB before first launch.
