### ISSUE TITLE
Added bookmarks/folders not shown until close and restart

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#983]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Added bookmarks/folders not shown until close and restart

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (iOS 10.3.3)

- Brave Version:
1.4 (17.07.20.16)

- Steps to reproduce:
    1. Install clean beta build
    2. Add a bookmark on the side panel
    3. Add a folder, doesn't show up, kill and restart the app, folder is shown 
    4. Add another bookmark, instantly shown
    5. Clean install beta build
    6. Add a folder on the side panel
    7. Add a bookmark, doesn't show up, kill and restart the app, bookmarks are shown
    8. Add a new folder, instantly shown

- Actual Behavior
Added bookmarks/folders not shown until close and restart

- Expected Behavior
Should show added items immediately

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jhreis** [comment]
Should be fixed per: 9a8f1791b6011cbed74441f934d30b6ab87e1b07
