### ISSUE TITLE
Long sync code gets truncated

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#985]
- Did you search for similar issues before submitting this one?
Yes

- Description:
Long sync code gets truncated making it hard to guess. Devices with smaller screen resolution will have be even more difficult

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (10.3.3) 

- Brave Version:
1.4 (17.07.20.16)

- Steps to reproduce:
    1. Install 1.4 beta
    2. Enable Sync(get code words), switch to code words
    3. Hope that none of the words are truncated 

- Actual Behavior
Long sync code gets truncated

- Expected Behavior
No words should be truncated

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/28535231-7e2d209e-709b-11e7-8dca-3fa27b7734b9.png)

- Any related issues:

**Comment by jhreis** [comment]
I think a simple, decent, temporary alternative would just to clip the other side of the word. Will won't display the entire thing, but at least the user could see the end of the word. 

Don't think this is a huge deal though, since sync will notify them of a mistyped word.

**Comment by jamesmudgett** [comment]
@jhreis How about autosizing font?  Otherwise, think it would make more sense to show the end of the word?
