### ISSUE TITLE
unable to open inbox on mail.google.com on iPad

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#998]
- Did you search for similar issues before submitting this one?
yes

- Description:
After logging into mail.google.com on iPad, inbox does not load. Only happens on iPad, iPhone works.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad

- Brave Version:
1.4 (17.07.27.15)

- Steps to reproduce:
    1. Open tab and navigate to mail.google.com.
    2. Login.
    3. Inbox does not load. 
    4. Repeat on iPhone, inbox loads without issue.

- Actual Behavior
Inbox does not load.

- Expected Behavior
Inbox should load.

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
no

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down?  Yes
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
Shield settings (when shields were up):
![img_0026](https://user-images.githubusercontent.com/28145373/28738135-c7b3f220-73bf-11e7-880b-c15092040320.PNG)

- Any related issues:

**Comment by srirambv** [comment]
I can open gmail on iPhone with the latest beta

**Comment by LaurenWags** [comment]
no longer an issue on 1.4 (17.07.31.11)
